// SPDX-License-Identifier: AGPL-3.0-or-later

// ── imports (generated by the split tooling; edit freely once the split is done)
import {
    LEFT_PROTRUSION, RIGHT_PROTRUSION, expandableSp, gW, nodeWidthSp, sumWidthSp,
} from './core.js';
// ── end of imports

// ── Protrusion ────────────────────────────────────────────────────────────────

// What LuaTeX steps over looking for the character at a line's edge
// (cp_skipable): penalties, empty glue, a font kern or an empty one, a math
// node without surround, an empty discretionary. An italic correction or an
// explicit kern stops the search, so the character before it does not hang.
export function protSkipable(n) {
    switch (n.type) {
        case 'penalty': case 'local_par': return true;
        case 'glue':    return !n.width && !n.stretch && !n.shrink;
        case 'kern':    return !n.kern || (n.subtype || 0) === 0;
        case 'math':    return !n.surround;
        case 'disc':    return !(n.pre || []).length && !(n.post || []).length && !(n.replace || []).length;
        default:        return false;
    }
}
// The character at the right edge of nodes[0..idx), as LuaTeX's
// find_protchar_right finds it: stepping back over what protSkipable allows,
// into a box to its last character, and over a box with nothing in it but
// such things (an anchor, an empty \hbox).
export function findLastGlyph(nodes, idx) {
    for (let k=idx-1;k>=0;k--) {
        const n=nodes[k];
        if (protSkipable(n)) continue;
        if (n.type==='hlist') {
            const kids=n.children||[];
            if (kids.every(protSkipable)) continue;
            return findLastGlyph(kids, kids.length);
        }
        return n.type==='glyph'?n:null;
    }
    return null;
}
// The character at the left edge from nodes[idx], as find_protchar_left
// finds it: past empty boxes, then over what protSkipable allows, into a box
// to its first character – but a box with nothing to protrude ends the
// search there.
export function findFirstGlyph(nodes, idx) {
    let k=idx;
    const emptyBox = n => n.type==='hlist' && !(n.children||[]).length && !n.width && !n.height && !n.depth;
    while (k<nodes.length-1 && emptyBox(nodes[k])) k++;
    for (;k<nodes.length;k++) {
        const n=nodes[k];
        if (protSkipable(n)) continue;
        if (n.type==='hlist' && (n.children||[]).length) return findFirstGlyph(n.children, 0);
        return n.type==='glyph'?n:null;
    }
    return null;
}

// TeX's round_xn_over_d: x·n/d rounded half away from zero, in integers.
export function roundXnOverD(x, n, d) {
    const s = x < 0 ? -1 : 1;
    return s * Math.floor((Math.abs(x) * n + Math.floor(d / 2)) / d);
}

// How far a character hangs into the margin. A bundle that records the
// fonts' quads carries what TeX had: the character's \lpcode/\rpcode in
// thousandths of its font's quad (LuaTeX's char_pw), and only when the
// paragraph was set with \protrudechars on – so a document without microtype
// does not protrude at all, just as in its PDF. An older bundle without that
// information keeps the viewer's own table of hanging punctuation.
export function protrusionOf(fontInfo, para, g, left) {
    if (!g) return 0;
    const fi = fontInfo && fontInfo[String(g.font)];
    if (fi && fi.quad > 0) {
        if (!(para && para.protrude_chars > 0)) return 0;
        const c = fi.codes && fi.codes.get(g.char);
        const code = c ? (left ? c.lp : c.rp) || 0 : 0;
        return code ? roundXnOverD(fi.quad, code, 1000) : 0;
    }
    return ((left ? LEFT_PROTRUSION : RIGHT_PROTRUSION)[g.char] || 0) * gW(g);
}

// ── Font expansion in the breaker ────────────────────────────────────────────

// LuaTeX's char_stretch/char_shrink and kern_stretch/kern_shrink: how much a
// glyph, or a font kern between two glyphs, widens (shrink: narrows) at its
// font's full \expandglyphsinfont limit, in sp, with TeX's rounding.
export function efCodeOf(fi, n) {
    const c = fi && fi.codes && fi.codes.get(n.char);
    return c && c.ef !== undefined ? c.ef : 1000;
}
export function expandLimit(fontInfo, n, shrink) {
    const fi = fontInfo && fontInfo[String(n.font)];
    return fi && fi.expand ? (shrink ? fi.expand.shrink : fi.expand.stretch) || 0 : 0;
}
export function fontStretchSp(fontInfo, ns, i, shrink) {
    const n = ns[i];
    if (n.type === 'glyph') {
        const m = expandLimit(fontInfo, n, shrink);
        if (!(m > 0) || n.text !== undefined) return 0;
        const ef = efCodeOf(fontInfo[String(n.font)], n);
        if (!(ef > 0)) return 0;
        const w = gW(n);
        const dw = shrink ? w - roundXnOverD(w, 1000 - m, 1000) : roundXnOverD(w, 1000 + m, 1000) - w;
        return dw > 0 ? roundXnOverD(dw, ef, 1000) : 0;
    }
    if (n.type === 'kern' && (n.subtype || 0) === 0 && n.kern) {
        const l = ns[i - 1], r = ns[i + 1];
        if (!l || !r || l.type !== 'glyph' || r.type !== 'glyph') return 0;
        const m = Math.trunc((expandLimit(fontInfo, l, shrink) + expandLimit(fontInfo, r, shrink)) / 2);
        if (!m) return 0;
        const w = n.kern, d = roundXnOverD(w, shrink ? 1000 - m : 1000 + m, 1000);
        const e = Math.trunc((efCodeOf(fontInfo[String(l.font)], l) + efCodeOf(fontInfo[String(r.font)], r)) / 2);
        const x = shrink ? w - d : d - w;
        return e === 1000 ? x : roundXnOverD(x, e, 1000);
    }
    return 0;
}

// \expandglyphsinfont's limits and step for a paragraph (LuaTeX insists they
// are the same for every font in it), or null when nothing in it expands.
export function paragraphExpansion(fontInfo, nodes) {
    const walk = ns => {
        for (const n of ns || []) {
            if (n.type === 'glyph') {
                const fi = fontInfo && fontInfo[String(n.font)];
                if (fi && fi.expand && fi.expand.step > 0) return fi.expand;
            } else if (n.type === 'disc') {
                const e = walk(n.pre) || walk(n.post) || walk(n.replace);
                if (e) return e;
            }
        }
        return null;
    };
    return walk(nodes);
}

// ── Knuth-Plass: break candidates ────────────────────────────────────────────

// Nodes after which glue is a legal breakpoint (TeX's precedes_break, plus
// the viewer's own drawn-box kinds).
export const PRECEDES_BREAK = new Set(['glyph', 'hlist', 'vlist', 'rule', 'disc', 'wdisc', 'picture', 'widget', 'transform']);

// Every candidate carries the running totals up to its node: natural width
// (cumW), finite stretch and shrink (cumS, cumZ), infinite fills (cumFill),
// *expandable* width (cumGlyphW, per unit of expansion as the renderer
// applies it – see expandableSp) and TeX's font stretch and shrink at the
// full expansion limit (cumFS, cumFZ); a discretionary has the same four
// widths for each of its three lists. `lead*` is what a break there discards
// at the start of the next line, `trail*` what it drops from the end of this
// one (TeX breaks *at* an explicit kern or a math node before glue, so they
// leave with the glue).
export function buildBreakCandidates(nodes, fontInfo, para) {
    para = para || {};
    const adjust = para.adjust_spacing || 0;
    const fsOf = (ns, i, shrink) => adjust > 0 ? fontStretchSp(fontInfo, ns, i, shrink) : 0;
    const part = ns => {
        const r = { w: 0, g: 0, fs: 0, fz: 0 };
        for (let i = 0; i < (ns || []).length; i++) {
            r.w += nodeWidthSp(ns[i]); r.g += expandableSp(fontInfo, ns, i);
            r.fs += fsOf(ns, i, false); r.fz += fsOf(ns, i, true);
        }
        return r;
    };
    const prot = (g, left) => protrusionOf(fontInfo, para, g, left);
    const NONE = { w: 0, g: 0, fs: 0, fz: 0 };
    let cumW=0, cumS=0, cumZ=0, cumGlyphW=0, cumFS=0, cumFZ=0, cumFill=0;
    const cand = (kind, i, penalty, extra) => ({
        kind, nodeIdx: i, penalty, pre: NONE, post: NONE, replace: NONE,
        leadW: 0, leadS: 0, leadZ: 0, trailW: 0, trailN: 0,
        cumW, cumS, cumZ, cumGlyphW, cumFS, cumFZ, cumFill,
        rightProtrusion: 0, leftProtrusion: 0, ...extra,
    });
    // What a break at node i discards after itself: glue, kerns and penalties
    // up to the next thing that is kept.
    const lead = from => {
        let W = 0, S = 0, Z = 0, k = from;
        for (; k < nodes.length; k++) {
            const m = nodes[k];
            if (m.type === 'kern') W += m.kern;
            else if (m.type === 'glue' && m.subtype !== 15) { W += m.width; S += !m.stretch_order ? m.stretch : 0; Z += !m.shrink_order ? m.shrink : 0; }
            else if (m.type !== 'penalty') break;
        }
        return { leadW: W, leadS: S, leadZ: Z, leftProtrusion: prot(findFirstGlyph(nodes, k), true) };
    };
    const bcs = [cand('start', -1, 0, { leftProtrusion: prot(findFirstGlyph(nodes, 0), true) })];
    bcs.expansion = adjust > 0 ? paragraphExpansion(fontInfo, nodes) : null;
    bcs.adjustSpacing = bcs.expansion ? adjust : 0;
    let inMath = false;

    for (let i=0; i<nodes.length; i++) {
        const n = nodes[i];
        if (n.type==='local_par') continue;

        // \parfillskip (LuaTeX subtype 15) terminates the paragraph, whatever its
        // stretch. The usual value is "0pt plus 1fil" (a ragged last line), but
        // \centering / \raggedleft set it rigid ("0pt") – and keying the end on
        // stretch>0, as before, gave a centred paragraph (a title, \begin{center})
        // no end candidate at all: kpPass then returned nothing and the greedy
        // fallback emitted no final line, so the whole paragraph vanished whenever
        // it happened to fit on one line. Key on the subtype instead. The last
        // line's right protrusion counts only when the line is packed: the
        // breaker (ext_try_break) has no character to look from at the end.
        if (n.type==='glue' && n.subtype===15) {
            // (the breaker leaves it out, but the line is packed with it)
            bcs.push(cand('end', i, -10000, { packRightProtrusion: prot(findLastGlyph(nodes, i), false) }));
            break;
        }
        // A mid-paragraph infinite fill (the \hfil that \\ inserts before its
        // forced break, or an explicit \hfill) is not the end: it marks the line
        // that contains it as "filled" (cumFill), so its slack is absorbed there
        // rather than justified, exactly like a last line. Treating the first such
        // fill as the end would silently drop everything after a \\.
        if (n.type==='glue' && n.stretch_order>0) {
            cumW+=n.width; cumFill+=1;
            continue;
        }
        if (n.type==='glue') {
            // Glue is a legal breakpoint outside maths when what precedes it is
            // kept at a break (a character, a box, a discretionary) or is a font
            // kern – so never after a penalty: ~ is \nobreak\ . After an explicit
            // kern (an italic correction, \,) or a math node TeX breaks at that
            // node instead, which drops it from the end of the line.
            const prev = nodes[i-1];
            let ok = false, trailN = 0;
            if (!inMath && prev) {
                if (PRECEDES_BREAK.has(prev.type)) ok = true;
                else if (prev.type==='kern' && ((prev.subtype||0)===0 || prev.subtype===2)) ok = true;
                else if ((prev.type==='kern' && (prev.subtype===1 || prev.subtype===3)) || prev.type==='math') { ok = true; trailN = 1; }
            }
            if (ok) {
                const trailW = trailN ? nodeWidthSp(prev) : 0;
                bcs.push(cand('space', i, 0, { trailW, trailN,
                    rightProtrusion: prot(findLastGlyph(nodes, i - trailN), false), ...lead(i) }));
            }
            cumW+=n.width; cumS+=!n.stretch_order?n.stretch:0; cumZ+=!n.shrink_order?n.shrink:0;
        } else if (n.type==='disc') {
            const pre=part(n.pre), post=part(n.post), replace=part(n.replace);
            const preGs=(n.pre||[]).filter(x=>x.type==='glyph'), postGs=(n.post||[]).filter(x=>x.type==='glyph');
            // LuaTeX subtypes 0–2 (\discretionary, \-, an explicit hyphen) were in
            // the source; 3 and up are its own hyphenation.
            bcs.push(cand('disc', i, n.penalty??50, { pre, post, replace, explicit: (n.subtype||0) <= 2,
                rightProtrusion: prot(preGs.length>0?preGs[preGs.length-1]:findLastGlyph(nodes,i), false),
                leftProtrusion: prot(postGs.length>0?postGs[0]:findFirstGlyph(nodes,i+1), true) }));
            cumW+=replace.w; cumGlyphW+=replace.g; cumFS+=replace.fs; cumFZ+=replace.fz;
        } else if (n.type==='wdisc') {
            // A widget that may be split (see Widgets): one candidate per split,
            // each carrying its own two parts – a discretionary with several
            // pre/post pairs over the one unbroken replacement.
            const replace={ ...NONE, w: sumWidthSp(n.replace) };
            for (const o of n.options) {
                bcs.push(cand('disc', i, o.penalty, { preNodes: o.pre, postNodes: o.post,
                    pre: { ...NONE, w: sumWidthSp(o.pre) }, post: { ...NONE, w: sumWidthSp(o.post) }, replace }));
            }
            cumW+=replace.w;
        } else if (n.type==='penalty' && n.penalty<10000) {
            bcs.push(cand('penalty', i, n.penalty, { rightProtrusion: prot(findLastGlyph(nodes,i), false), ...lead(i+1) }));
        } else {
            if (n.type==='math') inMath = (n.subtype||0) === 0;
            cumW+=nodeWidthSp(n);
            cumGlyphW+=expandableSp(fontInfo,nodes,i);
            cumFS+=fsOf(nodes,i,false); cumFZ+=fsOf(nodes,i,true);
        }
    }
    return bcs;
}

// A line from candidate a to candidate b, as TeX measures it: natural width
// (w, less the protrusion at both ends), finite glue stretch and shrink
// (s, z), font stretch and shrink (fs, fz) and the expandable width the
// renderer's expansion factor acts on (g).
export function lineMetrics(a, b, p) {
    const protrude = p.useProtrusion ? a.leftProtrusion + b.rightProtrusion : 0;
    // Where the line starts (after the break at a, less what that break
    // discards) and ends (at b, with a discretionary's pre-break text).
    const from = (key, lead) => a[key] + (a.kind==='disc' ? a.replace[lead] - a.post[lead] : 0);
    const upto = (key, part) => b[key] + (b.kind==='disc' ? b.pre[part] : 0);
    const on = p.useExpansion !== false;
    return {
        w:  upto('cumW', 'w') - b.trailW - from('cumW', 'w') - a.leadW - protrude,
        s:  b.cumS - a.cumS - a.leadS,
        z:  b.cumZ - a.cumZ - a.leadZ,
        g:  on ? upto('cumGlyphW', 'g') - from('cumGlyphW', 'g') : 0,
        fs: on ? upto('cumFS', 'fs') - from('cumFS', 'fs') : 0,
        fz: on ? upto('cumFZ', 'fz') - from('cumFZ', 'fz') : 0,
    };
}

// The emergency pass (threshold 10000) admits every line, and badness is
// capped at 10000, so every line past the cap would cost the same flat 1e8
// demerits: the breaker could then put the one unavoidable bad line anywhere –
// and does put it first, as a single-word line, since that lets every later
// line be perfect. In that pass lines are therefore weighed by their real,
// uncapped looseness, so a slightly loose line always beats a nearly empty one.
// (TeX avoids the same flatness in practice with \emergencystretch.)
export function rawBadness(shortage, total) {
    if (shortage === 0) return 0;
    if (total <= 0) return 1e7;
    const r = shortage / total;
    return Math.min(1e7, 100 * r * r * r);
}

// TeX's badness, in its own integer arithmetic (§108): about 100·(t/s)³, but
// the rounding decides where a line crosses the 12 and 99 of the fitness
// classes and the tolerances, so it has to be TeX's.
export function badness(t, s) {
    t = Math.round(t); s = Math.round(s);
    if (t <= 0) return 0;
    if (s <= 0) return 10000;
    let r;
    if (t <= 7230584) r = Math.floor(t * 297 / s);
    else if (s >= 1663497) r = Math.floor(t / Math.floor(s / 297));
    else r = t;
    return r > 1290 ? 10000 : Math.floor((r * r * r + 0x20000) / 0x40000);
}

// LuaTeX lets font expansion take up a line's shortfall before its glue does
// (ext_try_break): a line its glyphs can absorb entirely is scored as if half
// an expansion step were left over, and otherwise only what they cannot absorb
// is weighed against the glue. LuaTeX's shrinking branch comes out with the
// sign flipped – a line its glyphs can narrow enough counts as a hair short –
// and so does this one.
export function expansionShortfall(shortfall, m, ex) {
    if (!ex || shortfall === 0) return shortfall;
    if (shortfall > 0 && m.fs > 0)
        return m.fs > shortfall ? Math.trunc(Math.trunc(m.fs / Math.max(1, Math.trunc(ex.stretch / ex.step))) / 2)
                                : shortfall - m.fs;
    if (shortfall < 0 && m.fz > 0)
        return m.fz > -shortfall ? Math.trunc(Math.trunc(m.fz / Math.max(1, Math.trunc(ex.shrink / ex.step))) / 2)
                                 : shortfall + m.fz;
    return shortfall;
}

// ── KP DP (one pass) ─────────────────────────────────────────────────────────

// With `final` the pass is TeX's last one (§851–§855): a start from which a
// line has become overfull is dropped for good, and when the only start left
// dies with nothing feasible found yet, its overfull line is taken anyway at
// no cost (artificial demerits), so the pass always ends with a paragraph –
// as a PDF shows it, a line sticking out rather than a very loose one.
export function kpPass(bcs, lineWidthSp, threshold, firstPass, p, final) {
    const N=bcs.length;
    const dp=Array.from({length:N},()=>[null,null,null,null]);
    const alive=final ? dp.map(()=>[true,true,true,true]) : null;
    dp[0][2]={demerits:0,prev_j:-1,prev_fc:-1,hyphenated:false};
    let minRejectedBadness=null;
    // Font expansion enters the breaker only under \adjustspacing=2.
    const ex = bcs.adjustSpacing > 1 ? bcs.expansion : null;

    // A forced break (penalty <= -10000, e.g. from \\) is mandatory: no line may
    // span across it. lastForced[j] is the candidate index of the nearest forced
    // break before j, so a line from i to j is legal only when i >= lastForced[j].
    const lastForced=new Array(N).fill(-1);
    for (let k=1,lf=-1;k<N;k++){ lastForced[k]=lf; if(bcs[k].kind==='penalty'&&bcs[k].penalty<=-10000) lf=k; }

    for (let j=1;j<N;j++) {
        const bcJ=bcs[j];
        // TeX's first pass (\pretolerance) tries no hyphenation, but LuaTeX
        // has hyphenated already and still offers the discretionaries that
        // were in the source: explicit hyphens and \-.
        if (firstPass&&bcJ.kind==='disc'&&!bcJ.explicit) continue;
        if (bcJ.penalty>=10000) continue;
        const isEnd = bcJ.kind==='end';
        let feasibleAtJ = false;
        // Is (i, fc) the only start still in play for a line ending at j?
        const onlyStart = (i, fc) => {
            for (let k=Math.max(0,lastForced[j]);k<j;k++) for (let f=0;f<4;f++)
                if (dp[k][f] && alive[k][f] && !(k===i && f===fc)) return false;
            return true;
        };
        for (let i=0;i<j;i++) {
            if (i<lastForced[j]) continue;   // line would span a forced break
            // Two candidates at one node (a widget's alternative splits) are
            // one place: a line may not start and end there.
            if (bcs[i].nodeIdx===bcJ.nodeIdx) continue;
            let m=null;
            for (let fc_i=0;fc_i<4;fc_i++) {
                const si=dp[i][fc_i]; if(!si) continue;
                if (final && !alive[i][fc_i]) continue;
                if (!m) m=lineMetrics(bcs[i],bcJ,p);
                // A line carrying an infinite-order fill (\hfil from \\, \hfill,
                // the \parfillskip of the last line) absorbs positive slack
                // instead of justifying: badness 0. So does every line of a
                // paragraph that is not justified (p.ragged): \raggedright,
                // \centering and \raggedleft set \rightskip or \leftskip to 0pt
                // plus 1fil, so any line that fits costs nothing and TeX takes
                // the fewest lines, hyphenating only when it must.
                const hasFill = isEnd || p.ragged || bcJ.cumFill>bcs[i].cumFill;
                const shortfall = expansionShortfall(lineWidthSp-m.w, m, ex);
                let b, fc_j;
                if (shortfall>0) {
                    if (hasFill) { b=0; fc_j=2; }
                    else { b=badness(shortfall,m.s); fc_j=b>99?0:b>12?1:2; }
                } else if (shortfall<0) {
                    if (-shortfall>m.z) {                         // overfull
                        if (final) {
                            alive[i][fc_i] = false;
                            if (!feasibleAtJ && onlyStart(i, fc_i) && (!dp[j][3] || si.demerits<=dp[j][3].demerits))
                                dp[j][3]={demerits:si.demerits,prev_j:i,prev_fc:fc_i,hyphenated:bcJ.kind==='disc',overfull:true};
                        }
                        continue;
                    }
                    b=badness(-shortfall,m.z); fc_j=b>12?3:2;
                } else { b=0; fc_j=2; }
                if (b>threshold) { if(minRejectedBadness===null||b<minRejectedBadness) minRejectedBadness=b; continue; }
                feasibleAtJ = true;
                const emergency = threshold>=10000;
                const bd = emergency&&!(hasFill&&shortfall>=0) ? rawBadness(Math.abs(shortfall),shortfall>=0?m.s:m.z) : b;
                const lp=p.linePenalty+bd; let d=emergency ? lp*lp : (Math.abs(lp)>=10000?100000000:lp*lp);
                if(bcJ.penalty>0) d+=bcJ.penalty*bcJ.penalty;
                else if(bcJ.penalty>-10000) d-=bcJ.penalty*bcJ.penalty;
                if(si.hyphenated) {
                    if(bcJ.kind==='disc') d+=p.doubleHyphenDemerits;
                    else if(isEnd) d+=p.finalHyphenDemerits;
                }
                if(Math.abs(fc_j-fc_i)>1) d+=p.adjDemerits;
                // Not TeX, and off unless a page asks for it: a last line
                // shorter than lastLineMin of the measure costs lastLinePenalty.
                if(isEnd && p.lastLineMin>0 && m.w<p.lastLineMin*lineWidthSp) d+=p.lastLinePenalty;
                const td=si.demerits+d;
                // Ties go to the later start, as in TeX (`d <= minimal_demerits`,
                // scanning the active list in order): the earlier lines longer.
                if(!dp[j][fc_j]||td<=dp[j][fc_j].demerits) dp[j][fc_j]={demerits:td,prev_j:i,prev_fc:fc_i,hyphenated:bcJ.kind==='disc'};
            }
        }
    }
    const endIdx=N-1; if(bcs[endIdx].kind!=='end') return {breaks:null,minRejectedBadness};
    let bestFc=-1, bestD=Infinity;
    for(let fc=0;fc<4;fc++) if(dp[endIdx][fc]&&dp[endIdx][fc].demerits<bestD){bestD=dp[endIdx][fc].demerits;bestFc=fc;}
    if(bestFc===-1) return {breaks:null,minRejectedBadness};
    const breaks=[]; let j=endIdx,fc=bestFc,overfull=false;
    while(j>0){breaks.push({bcIdx:j,fc,demerits:dp[j][fc].demerits});if(dp[j][fc].overfull)overfull=true;const pj=dp[j][fc].prev_j,pfc=dp[j][fc].prev_fc;j=pj;fc=pfc;}
    // overfull: the final pass set a line it could not shrink to fit
    breaks.reverse(); return {breaks,minRejectedBadness,overfull};
}

// Set one line as TeX's hpack does with \adjustspacing: font expansion takes
// the slack first, as a whole number of steps up to the font's limit (LuaTeX's
// font_expand_ratio and fix_expand_value), and the glue takes the rest. A
// filled line (fil glue, a last line with room) neither expands nor stretches.
// Returns the glue ratio and the line's expansion (a fraction; the renderer
// widens each glyph by it, times the glyph's \efcode).
export function packLine(bcs, a, b, lineWidthSp, p, hasFill) {
    const m = lineMetrics(a, b, p);
    const x = lineWidthSp - m.w + (p.useProtrusion ? b.packRightProtrusion || 0 : 0);
    if (x === 0 || (hasFill && x > 0)) return { ratio: 0, expand: 0 };
    let expand = 0, rest = x;
    const ex = bcs.expansion;
    const f = x > 0 ? m.fs : m.fz;
    if (ex && f > 0 && m.g > 0) {
        const limit = x > 0 ? ex.stretch : ex.shrink;
        const r = Math.max(-1000, Math.min(1000, Math.round(x * 1000 / f)));   // font_expand_ratio
        let e = Math.abs(Math.round(r * limit / 1000));
        if (e > limit) e = limit;
        else if (ex.step > 1 && e % ex.step) e = ex.step * roundXnOverD(e, 1, ex.step);
        expand = (x > 0 ? e : -e) / 1000;
        rest = x - expand * m.g;
    }
    // What the expansion leaves goes to the glue. On a filled line (one
    // shrunk by its fonts, whose steps overshoot) a surplus goes to the fill,
    // as hpack's second pass gives it, and the spaces keep their width. An
    // overfull line shrinks its glue fully and no further (glue_set 1).
    const ratio = rest > 0 ? (hasFill || !(m.s > 0) ? 0 : rest / m.s)
                : rest < 0 ? (m.z > 0 ? Math.max(-1, rest / m.z) : 0) : 0;
    return { ratio, expand };
}

export function extractLineNodes(startBC, endBC, nodes) {
    const result=[]; let from;
    if(startBC.kind==='start'){from=0;}
    else{if(startBC.kind==='disc') for(const pn of (startBC.postNodes||nodes[startBC.nodeIdx].post)) result.push(pn); from=startBC.nodeIdx+1;}
    // Glue, kerns and penalties are discarded at a line break, but only at a
    // *break*: at the very start of a paragraph they are real content.
    // \subparagraph* and friends make this visible – \@xsect drops the usual
    // \parindent box and re-inserts the indent as \hskip\parindent glue, which
    // stripping here would delete from the render while the break candidates
    // still counted its width, leaving the first line short by exactly the indent.
    if(startBC.kind!=='start'&&result.length===0){while(from<endBC.nodeIdx&&(nodes[from].type==='glue'||nodes[from].type==='kern'||nodes[from].type==='penalty'))from++;}
    const to=endBC.nodeIdx-(endBC.trailN||0);
    for(let i=from;i<to;i++) if(nodes[i].type!=='local_par') result.push(nodes[i]);
    if(endBC.kind==='disc') for(const pn of (endBC.preNodes||nodes[endBC.nodeIdx].pre)) result.push(pn);
    return result;
}

export function greedyFallback(bcs, nodes, lineWidthSp, p) {
    const breaks=[]; let s=0;
    for(let j=1;j<bcs.length;j++){
        const {w}=lineMetrics(bcs[s],bcs[j],p);
        if(bcs[j].kind==='end'){breaks.push({bcIdx:j,fc:2,demerits:0});break;}
        if(w>lineWidthSp&&j>s+1){breaks.push({bcIdx:j-1,fc:2,demerits:0});s=j-1;}
    }
    return breaks;
}

export function kpBreak(bcs, nodes, lineWidthSp, p) {
    let breaks=null;
    if (p.pretolerance >= 0)
        breaks = kpPass(bcs,lineWidthSp,p.pretolerance,true,p).breaks;
    // TeX's second pass is its final one (\emergencystretch=0): when nothing
    // fits, it sets an overfull line. At the width TeX compiled for that is
    // TeX's own result, but at a narrower one a reader sees words run past
    // the right edge. So the viewer keeps the final pass's breaks unless they
    // hold an overfull line, and then tries its gentler passes – looser
    // tolerances, which leave a loose line instead – falling back on TeX's
    // breaks only if those find nothing either (a word wider than the
    // measure). data-tex-final-pass="strict" keeps TeX's breaks always, as a
    // replay against TeX needs; "false" skips the final pass altogether.
    let texBreaks=null;
    if(!breaks) {
        const r = kpPass(bcs,lineWidthSp,p.tolerance,false,p,!!p.texFinalPass);
        if (!r.overfull || p.texFinalPass === 'strict') breaks = r.breaks;
        else texBreaks = r.breaks;
    }
    if(!breaks) breaks = kpPass(bcs,lineWidthSp,p.tolerance2,false,p).breaks;
    if(!breaks) breaks = kpPass(bcs,lineWidthSp,p.emergencyTolerance,false,p).breaks;
    if(!breaks) breaks = texBreaks;
    if(!breaks) breaks = greedyFallback(bcs,nodes,lineWidthSp,p);
    const lines=[];
    for(let k=0;k<breaks.length;k++){
        const startBC=k===0?bcs[0]:bcs[breaks[k-1].bcIdx], endBC=bcs[breaks[k].bcIdx];
        const hasFill = endBC.kind==='end' || p.ragged || endBC.cumFill>startBC.cumFill;
        const { ratio, expand } = packLine(bcs, startBC, endBC, lineWidthSp, p, hasFill);
        const rightProtrusion = (endBC.kind==='end' ? endBC.packRightProtrusion : endBC.rightProtrusion) || 0;
        lines.push({nodes:extractLineNodes(startBC,endBC,nodes),ratio,expand,fitness:breaks[k].fc,leftProtrusion:startBC.leftProtrusion,rightProtrusion});
    }
    return lines;
}
