// SPDX-License-Identifier: AGPL-3.0-or-later

// ── imports (generated by the split tooling; edit freely once the split is done)
import { registerStreamSource } from '../defaults/footnotes.js';
import {
    RUNNING_RULE, SP_TO_PX, gD, gH, gW, glyphExpandScale, hlistGlueRatio, kernExpandScale,
    setGlue, useGlyphMetrics, vlistGlueRatio,
} from './core.js';
import { updateDisplayOverflowCue } from './layout/display.js';
import { materializeSegment } from './layout/document.js';
import { registerLinkGlyph, restoreLinkStates } from '../host/links.js';
import { colorFill } from '../runtime/colour.js';
import { renderPiece } from '../host/inline.ts';
import { applyMark } from '../host/marks.ts';
// ── end of imports

// ── SVG renderer ──────────────────────────────────────────────────────────────

export function svgEl(tag, attrs) {
    const el=document.createElementNS('http://www.w3.org/2000/svg',tag);
    for(const [k,v] of Object.entries(attrs)) el.setAttribute(k,String(v));
    return el;
}

// renderNodes emits glyphs, spaces, and rules through a sink object. The sink
// reconciles against the SVG elements of the previous render instead of
// recreating them: every element is keyed by the identity of the node-list
// object it renders (node objects are decoded once per block and never
// change). Because lines are contiguous slices of one fixed node sequence,
// the global emission order is break-invariant – a reflow can move elements
// between lines and toggle conditional ones (disc pre/post vs replace,
// boundary spaces) on and off, but never reorder them. So reconciliation is
// a single forward merge: reused elements in place cost two attribute writes,
// out-of-place ones a single insertBefore, and toggled-off ones are detached
// (kept in the byNode cache for later reattachment, so after both paths of a
// disc have been seen once, reflows allocate nothing at all).

// ── Transforms ────────────────────────────────────────────────────────────────
// A `transform` node (\rotatebox and friends) carries a PDF matrix applied
// about the current point; see the serializer, which folds TeX's save/setmatrix/
// restore whatsits into it. Two conversions are needed to get to SVG:
//
//   * PDF's y axis points up, SVG's points down. The SVG matrix is the PDF one
//     conjugated by the flip diag(1,-1), which negates the off-diagonal terms:
//     [a b c d] becomes matrix(a, -b, -c, d). Skip this and rotations come out
//     mirrored – 90° turns the wrong way.
//   * The matrix acts about the reference point, not the origin, so it is
//     wrapped in translate(±ref).
export function svgMatrixOf(n, x, y) {
    return { a: n.m_a ?? 1, b: -(n.m_b ?? 0), c: -(n.m_c ?? 0), d: n.m_d ?? 1, x, y };
}

// The affine (a,b,c,d,e,f) of a transform about its reference point, in the
// order SVG's matrix() takes: x' = a·x + c·y + e, y' = b·x + d·y + f.
export function affineOf(t) {
    return [t.a, t.b, t.c, t.d,
            t.x - (t.a * t.x + t.c * t.y),
            t.y - (t.b * t.x + t.d * t.y)];
}

// m1 ∘ m2 – apply m2, then m1.
export function affineMul(m1, m2) {
    if (!m1) return m2;
    if (!m2) return m1;
    const [a1,b1,c1,d1,e1,f1] = m1, [a2,b2,c2,d2,e2,f2] = m2;
    return [a1*a2 + c1*b2,       b1*a2 + d1*b2,
            a1*c2 + c1*d2,       b1*c2 + d1*d2,
            a1*e2 + c1*f2 + e1,  b1*e2 + d1*f2 + f1];
}

export function reconcileSink(byNode, used, stats, cache) {
    let textParent = null, auxParent = null, lastTspan = null, lastRect = null;
    const stack = [];
    const linkRuns = new Map();   // data-link key → { el, x0, x1, top, bottom }
    const markRuns = new Map();   // mark index → { el, x0, x1, top, bottom }
    const extend = (runs, key, el, x, n, y) => {
        const x1 = x + gW(n) * SP_TO_PX, top = y - gH(n) * SP_TO_PX, bottom = y + gD(n) * SP_TO_PX;
        const r = runs.get(key);
        if (!r) runs.set(key, { el, x0: x, x1, top, bottom });
        else {
            r.x0 = Math.min(r.x0, x); r.x1 = Math.max(r.x1, x1);
            r.top = Math.min(r.top, top); r.bottom = Math.max(r.bottom, bottom);
        }
    };

    function place(parent, last, el, isNew) {
        const expected = last ? last.nextSibling : parent.firstChild;
        if (el !== expected) {
            parent.insertBefore(el, expected);
            if (!isNew) stats.moved++;
        }
    }

    return {
        beginLine(textEl, auxEl) { textParent = textEl; auxParent = auxEl; lastTspan = null; lastRect = null; },
        // Rotated glyphs cannot go in the line's shared <text>: a tspan takes
        // no transform of its own (SVG 1.1), and x/y on a tspan would fight
        // the group's matrix anyway. So a transform gets its own <g> holding
        // its own <text>, and sits in the aux parent next to rules and
        // pictures. Nesting works because the parents are stacked.
        beginTransform(n, tf) {
            let g = byNode.get(n);
            const isNew = !g;
            if (isNew) {
                g = svgEl('g', {});
                const t = svgEl('text', {});
                t.style.cssText = 'font-weight:normal;font-style:normal';
                g.appendChild(t);
                byNode.set(n, g); stats.created++;
            } else { stats.repositioned++; }
            const [a,b,c,d,e,f] = affineOf(tf);
            g.setAttribute('transform', `matrix(${a} ${b} ${c} ${d} ${e} ${f})`);
            place(auxParent, lastRect, g, isNew);
            used.add(g); lastRect = g;
            stack.push({ textParent, auxParent, lastTspan, lastRect });
            textParent = g.firstChild; auxParent = g;
            // The group's own <text> is not in `used`: it lives and goes with
            // the group. Swept on its own, it was taken out of a group that a
            // later paint reused, empty (and g.firstChild null from then on).
            lastTspan = null; lastRect = g.firstChild;
        },
        endTransform() {
            const s = stack.pop();
            textParent = s.textParent; auxParent = s.auxParent;
            lastTspan = s.lastTspan; lastRect = s.lastRect;
        },
        glyph(n, x, y, fi) {
            // No loadable font for this glyph → draw its metric boxes instead of
            // an unshapeable character (see missing()).
            if (fi?.unresolved) { this.missing(n, x, y); return; }
            let el = byNode.get(n), isNew = !el;
            if (isNew) {
                el = svgEl('tspan', {x, y, 'font-family': fi?.family ?? 'serif', 'font-size': fi?.size_px ?? 12});
                // A \webtext slot's word (see Slots) is a whole word, as text.
                el.textContent = n.text !== undefined ? n.text : String.fromCodePoint(n.char);
                // Inline style so it wins over the page's `fill: currentColor`
                // rule; uncoloured glyphs keep currentColor (dark-mode aware).
                // Coloured ones go through the theme substitution maps.
                if (n.color) el.style.fill = colorFill(n.color);
                if (n.stream)     registerStreamSource(el, n.stream, cache);
                if (n.link)       registerLinkGlyph(el, n.link, cache);
                if (n.mark)       applyMark(el, n.mark, cache);
                // A \webtext's glyphs – TeX's default or a text the page gave
                // – carry its name, so a page can find (and style) where it is.
                if (n.slot && cache.slotNames && cache.slotNames[n.slot - 1] !== undefined)
                    el.dataset.slot = cache.slotNames[n.slot - 1];
                byNode.set(n, el); stats.created++;
            } else {
                el.setAttribute('x', x); el.setAttribute('y', y); stats.repositioned++;
            }
            place(textParent, lastTspan, el, isNew);
            used.add(el); lastTspan = el;
            // The extent of each reference on this line, for its hit area
            // (see paintLinkHits). Not inside a transform: that has its own
            // coordinates.
            if (el.dataset.link && !stack.length) extend(linkRuns, el.dataset.link, el, x, n, y);
            // And of each mark, for its band (see paintMarkBands).
            if (n.mark && !stack.length) extend(markRuns, n.mark, el, x, n, y);
        },
        // The references' extents on the line just drawn; starts afresh.
        takeLinkRuns() { const runs = [...linkRuns.values()]; linkRuns.clear(); return runs; },
        takeMarkRuns() { const runs = [...markRuns.entries()]; markRuns.clear(); return runs; },
        // A glyph whose font could not be loaded: draw its TeX metric boxes – the
        // advance width by the height above the baseline, and by the depth below –
        // as two outlined rects, so the missing ink's place and size are visible.
        missing(n, x, y) {
            let el = byNode.get(n), isNew = !el;
            const w = gW(n) * SP_TO_PX;
            const h = gH(n) * SP_TO_PX;                 // above the baseline
            const d = gD(n) * SP_TO_PX;                 // below the baseline
            const boxes = [];
            if (h > 0) boxes.push([x, y - h, w, h]);
            if (d > 0) boxes.push([x, y,     w, d]);
            if (isNew) {
                el = svgEl('g', { class: 'latex-missing-glyph' });
                for (const [bx, by, bw, bh] of boxes) {
                    const r = svgEl('rect', { x: bx, y: by, width: bw, height: bh });
                    r.style.fill = 'none';
                    r.style.stroke = 'var(--latex-color-ff0000, #cc0000)';
                    r.style.strokeWidth = '1';
                    r.style.opacity = '0.55';
                    el.appendChild(r);
                }
                byNode.set(n, el); stats.created++;
            } else {
                const rects = el.children;
                boxes.forEach(([bx, by, bw, bh], i) => {
                    rects[i].setAttribute('x', bx);     rects[i].setAttribute('y', by);
                    rects[i].setAttribute('width', bw); rects[i].setAttribute('height', bh);
                });
                stats.repositioned++;
            }
            place(auxParent, lastRect, el, isNew);
            used.add(el); lastRect = el;
        },
        space(n, x, y) {
            let el = byNode.get(n), isNew = !el;
            if (isNew) {
                el = svgEl('tspan', {x, y});
                el.textContent = ' ';
                // Not a target: the pointer between two words of a reference
                // must reach the reference's hit area below (paintLinkHits).
                el.style.pointerEvents = 'none';
                byNode.set(n, el); stats.created++;
            } else {
                el.setAttribute('x', x); el.setAttribute('y', y); stats.repositioned++;
            }
            place(textParent, lastTspan, el, isNew);
            used.add(el); lastTspan = el;
        },
        rule(n, x, y, w, h) {
            let el = byNode.get(n), isNew = !el;
            if (isNew) {
                el = svgEl('rect', {x, y, width: w, height: h});
                // Always set the fill inline rather than leaving it to page
                // CSS: a blanket `rect { fill: currentColor }` would also hit
                // the shapes inside a tikzpicture and flatten their colours,
                // since CSS outranks the presentation attributes dvisvgm emits.
                el.style.fill = n.color ? colorFill(n.color)
                                        : 'var(--latex-color-000000, currentColor)';
                byNode.set(n, el); stats.created++;
            } else {
                el.setAttribute('x', x); el.setAttribute('y', y);
                el.setAttribute('width', w); el.setAttribute('height', h);
                stats.repositioned++;
            }
            place(auxParent, lastRect, el, isNew);
            used.add(el); lastRect = el;
        },
        // Where a \webaside stood (see Asides): an empty rect at the pen
        // position on the baseline, drawing nothing, for aside.anchor().
        aside(n, x, y) {
            let el = byNode.get(n), isNew = !el;
            if (isNew) {
                el = svgEl('rect', { x, y, width: 0, height: 0 });
                el.setAttribute('class', 'latex-aside-mark');
                el.dataset.aside = n.aside;
                byNode.set(n, el); stats.created++;
            } else {
                el.setAttribute('x', x); el.setAttribute('y', y);
                stats.repositioned++;
            }
            place(auxParent, lastRect, el, isNew);
            used.add(el); lastRect = el;
        },
        // A widget part (see Widgets): HTML in a foreignObject over the part's
        // box, so it moves with the text on every reflow. Drawn by the widget
        // once, when the element is made: a new measurement makes new nodes.
        widget(n, x, y) {
            let el = byNode.get(n), isNew = !el;
            const h = n.height * SP_TO_PX, d = n.depth * SP_TO_PX, w = n.width * SP_TO_PX;
            if (isNew) {
                el = svgEl('foreignObject', { width: w, height: h + d });
                el.setAttribute('class', 'latex-widget');
                // every part of one widget shares a key, for the shared hover
                // and pressed states (installWidgetStates)
                el.dataset.widget = `${cache.blockKey}:${n.slot}`;
                el.style.overflow = 'visible';
                el.style.pointerEvents = 'auto';
                const box = document.createElementNS('http://www.w3.org/1999/xhtml', 'div');
                box.style.cssText = `width:${w}px;height:${h + d}px;font-size:${n.fontPx}px;` +
                    `line-height:normal;color:${n.color ? colorFill(n.color) : 'currentColor'};` +
                    // content aligned by baseline, as ctx.measure measured it: the
                    // highest-reaching element's top at the widget's top, so the
                    // shared baseline lands on the line's
                    'display:flex;align-items:baseline;user-select:none;-webkit-user-select:none';
                el.appendChild(box);
                renderPiece(n, el, box, cache);
                byNode.set(n, el); stats.created++;
            } else {
                stats.repositioned++;
            }
            el.setAttribute('x', x); el.setAttribute('y', y - h);
            place(auxParent, lastRect, el, isNew);
            used.add(el); lastRect = el;
        },
        // A precompiled TikZ box or included PDF page. Its markup never changes,
        // so reflowing is only a new transform – the drawing is built once.
        picture(n, x, y) {
            let el = byNode.get(n), isNew = !el;
            const pic = n.pic;
            if (isNew) {
                // A drawing carries its own colours (already rewritten to
                // the theme's custom properties), unlike glyph ink which is
                // themed wholesale. The class marks that boundary for page CSS
                // and for anyone inspecting the DOM.
                el = svgEl('g', { class: 'latex-picture' });
                if (pic) el.innerHTML = pic.svg;
                // dvisvgm omits fill on black paths (SVG's initial fill is
                // black), so the theme's default text colour is supplied here
                // by inheritance rather than rewritten into every path.
                el.setAttribute('fill', 'var(--latex-color-000000, currentColor)');
                byNode.set(n, el); stats.created++;
            } else {
                stats.repositioned++;
            }
            // The source viewBox is in bp; scaling it to the node's TeX width
            // makes the drawing fill its box exactly, at any zoom.
            const s = pic && pic.vb_w ? (n.width * SP_TO_PX) / pic.vb_w : 1;
            el.setAttribute('transform',
                `translate(${x} ${y - n.height * SP_TO_PX}) scale(${s})`);
            place(auxParent, lastRect, el, isNew);
            used.add(el); lastRect = el;
        },
    };
}

// ── Leaders ───────────────────────────────────────────────────────────────────
// Leader glue carries a box that TeX repeats across the glue's set width rather
// than leaving it blank; \xrightarrow is an arrow tail, a \cleaders run of
// en-dashes, and an arrowhead. The set width is whatever the enclosing box's
// glue setting produced, so the copies are laid out here rather than baked in.
//
// Placement follows TeX82 §626-627: as many whole copies as fit, then
//   \cleaders – the remainder is split evenly at the two ends (centred);
//   \xleaders – the remainder is spread evenly into count+1 gaps;
//   \leaders / \gleaders – copies align to a grid on the *enclosing* box rather
//     than to this glue, which is not information the node carries, so they are
//     packed from the left. Nothing in this pipeline uses them today.
export const GLUE_LEADERS = 100, GLUE_CLEADERS = 101, GLUE_XLEADERS = 102;

// The DOM reconciler is keyed by node identity, so every tiled copy needs its
// own node objects: drawing one leader box N times would look up the same
// element N times, move it, and leave a single copy at the last position. The
// clones are cached on the glue node and reused while the count holds, which
// keeps the elements – and the reconciler's work – stable across reflows.
export function deepCloneNode(o){
    if(Array.isArray(o)) return o.map(deepCloneNode);
    if(o&&typeof o==='object'){
        const r={};
        for(const k of Object.keys(o)) r[k]=deepCloneNode(o[k]);
        return r;
    }
    return o;
}

export function leaderCopies(n, count){
    if(!n._leaderCopies || n._leaderCopies.length!==count){
        n._leaderCopies=[];
        for(let i=0;i<count;i++) n._leaderCopies.push(deepCloneNode(n.leader));
    }
    return n._leaderCopies;
}

export function renderLeaders(fontInfo, sink, n, x, baselineY, wSp){
    const L=n.leader;
    if(!L || wSp<=0) return;

    // A rule leader is not tiled: TeX simply runs the rule the whole length
    // (\hrulefill). Running dimensions inherit from the enclosing box, which is
    // not reachable here, so they fall back to the rule's own.
    if(L.type==='rule'){
        const h=(L.height===RUNNING_RULE?0:(L.height??0))*SP_TO_PX;
        const d=(L.depth ===RUNNING_RULE?0:(L.depth ??0))*SP_TO_PX;
        if(h+d>0) sink.rule(L, x, baselineY-h, wSp*SP_TO_PX, h+d);
        return;
    }

    const Lw=L.width??0;
    if(Lw<=0) return;                     // would tile forever
    const count=Math.floor(wSp/Lw);
    if(count<1) return;                   // not even one copy fits: TeX draws nothing

    const slack=wSp-count*Lw;
    let start, step=Lw;
    if(n.subtype===GLUE_XLEADERS){ const gap=slack/(count+1); start=gap; step=Lw+gap; }
    else if(n.subtype===GLUE_CLEADERS){ start=slack/2; }
    else { start=0; }                     // \leaders / \gleaders – see note above

    const copies=leaderCopies(n,count);
    for(let i=0;i<count;i++){
        renderNodes(fontInfo,sink,[copies[i]],x+(start+i*step)*SP_TO_PX,baselineY,0,0,0);
    }
}

// Stack a vlist's children top-to-bottom. refY is the vlist's reference baseline
// and vlistX its left edge; both are supplied by the caller (already resolving any
// shift for the context the vlist appears in). Split out of renderNodes so a vlist
// nested inside another vlist can reuse it – without this, a vlist child was
// dropped, which silently deleted the inner half of a stacked construction
// (double math accents, \substack, nested roots, …), leaving one piece too high.
export function renderVlistBody(fontInfo, sink, n, vlistX, refY){
    const{ratio:vr,fillOrder:vfo}=vlistGlueRatio(n);
    const vlistW=n.width;
    let curY=refY-n.height*SP_TO_PX;
    for(const child of n.children){
        const y0=curY;
        if(child.type==='kern'){curY+=child.kern*SP_TO_PX;}
        else if(child.type==='glue'){curY+=setGlue(child,vr,vfo)*SP_TO_PX;}
        else if(child.type==='rule'){
            const rw=(child.width===RUNNING_RULE?vlistW:child.width)*SP_TO_PX;
            const rh=(child.height+child.depth)*SP_TO_PX;
            sink.rule(child,vlistX,curY,rw,rh);
            curY+=rh;
        } else if(child.type==='hlist'){
            const cb=curY+child.height*SP_TO_PX;
            const{ratio:hr,fillOrder:hfo}=hlistGlueRatio(child);
            renderNodes(fontInfo,sink,child.children,vlistX+(child.shift??0)*SP_TO_PX,cb,hr,0,hfo,child.height,child.depth);
            curY+=(child.height+child.depth)*SP_TO_PX;
        } else if(child.type==='vlist'){
            // Inside a vlist a box's shift is horizontal; the child's own baseline
            // sits child.height below the current pen, then we advance past it.
            renderVlistBody(fontInfo,sink,child,vlistX+(child.shift??0)*SP_TO_PX,curY+child.height*SP_TO_PX);
            curY+=(child.height+child.depth)*SP_TO_PX;
        }
        // Inspection: a vertical list item's top edge and advance.
        if(sink.vnode) sink.vnode(child, vlistX, y0, curY-y0);
    }
}

// runH/runD (sp) are the enclosing box's height and depth. A rule with a running
// dimension (the RUNNING_RULE sentinel) inherits it – that is how a \vrule stretches
// to the exact height of the \hbox it sits in (e.g. the two side edges of the amsthm
// QED box). Without this the rule is dropped and only the top/bottom edges show.
export function renderNodes(fontInfo, sink, nodes, x, baselineY, ratio, expandRatio, fillOrder, runH, runD) {
    ratio=ratio||0; expandRatio=expandRatio||0; fillOrder=fillOrder||0; runH=runH||0; runD=runD||0;
    for(let i=0;i<nodes.length;i++){
        const n=nodes[i], x0=x;
        switch(n.type){
            case 'rule':{
                // In an hlist a rule is a vrule: its width is set, its height/depth
                // run to the enclosing box. Draw it, then advance the pen by its width.
                const w =(n.width ===RUNNING_RULE?0:(n.width ??0));
                const h =(n.height===RUNNING_RULE?runH:(n.height??0));
                const d =(n.depth ===RUNNING_RULE?runD:(n.depth ??0));
                const hp=h*SP_TO_PX, dp=d*SP_TO_PX;
                if(w>0&&hp+dp>0) sink.rule(n, x, baselineY-hp, w*SP_TO_PX, hp+dp);
                x+=w*SP_TO_PX; break;
            }
            case 'glyph':{
                sink.glyph(n, x, baselineY, fontInfo[String(n.font)]);
                x+=gW(n)*glyphExpandScale(fontInfo,n,expandRatio)*SP_TO_PX; break;
            }
            case 'glue':{
                let w=n.width;
                if(ratio>0&&(n.stretch_order||0)===fillOrder&&n.stretch) w+=ratio*n.stretch;       // signed, as setGlue
                else if(ratio<0&&(n.shrink_order||0)===fillOrder&&n.shrink) w+=ratio*n.shrink;
                if(n.leader) renderLeaders(fontInfo,sink,n,x,baselineY,w);
                if(n.subtype===13) sink.space(n, x, baselineY);
                if(sink.gap) sink.gap(n,'width',x,w*SP_TO_PX);
                x+=w*SP_TO_PX; break;
            }
            case 'kern':{
                // Expansion stretches the font's own kerns (subtype 0) with the
                // glyphs, as an expanded font copy would; an explicit \kern,
                // an accent kern or an italic correction keeps its width.
                const w=n.kern*((n.subtype||0)===0?kernExpandScale(fontInfo,nodes[i-1],nodes[i+1],expandRatio):1)*SP_TO_PX;
                if(sink.gap) sink.gap(n,'kern',x,w);
                x+=w; break;
            }
            case 'picture':{
                // The picture fills its TeX box exactly; the box is what makes
                // it behave like any other box in text, math or an align row.
                sink.picture(n, x, baselineY);
                x+=n.width*SP_TO_PX; break;
            }
            case 'transform':{
                // The matrix is drawing-only: TeX advanced the pen by the
                // untransformed content and sized the *enclosing* box to the
                // rotated bbox, so the children still advance x exactly as
                // they did before the serializer grouped them. (graphicx makes
                // the content box zero-width, so in practice this is 0.) The
                // ratio/fillOrder pass through for the same reason – these
                // were siblings in the parent list and their glue is set by
                // the parent's packing.
                sink.beginTransform(n, svgMatrixOf(n, x, baselineY));
                x=renderNodes(fontInfo,sink,n.children,x,baselineY,ratio,expandRatio,fillOrder,runH,runD);
                sink.endTransform();
                break;
            }
            case 'disc':  x=renderNodes(fontInfo,sink,n.replace,x,baselineY,0,expandRatio,0,runH,runD); break;
            case 'wdisc': x=renderNodes(fontInfo,sink,n.replace,x,baselineY,0,0,0,runH,runD); break;
            case 'widget':
                if(sink.widget) sink.widget(n, x, baselineY);
                x+=n.width*SP_TO_PX; break;
            case 'math':{
                const w=n.surround*SP_TO_PX;
                if(sink.gap) sink.gap(n,'surround',x,w);
                x+=w; break;
            }
            case 'hlist':{
                if(n.aside&&sink.aside) sink.aside(n,x,baselineY);
                const{ratio:hr,fillOrder:hfo}=hlistGlueRatio(n);
                renderNodes(fontInfo,sink,n.children,x,baselineY+(n.shift??0)*SP_TO_PX,hr,0,hfo,n.height,n.depth);
                x+=n.width*SP_TO_PX; break;
            }
            case 'vlist':
                // A vlist encountered here sits in an hlist context, where a box's
                // shift is vertical (downward); renderVlistBody stacks its contents.
                renderVlistBody(fontInfo,sink,n,x,baselineY+(n.shift??0)*SP_TO_PX);
                x+=n.width*SP_TO_PX; break;
        }
        // Inspection (api.inspect.replay): every node's pen position and advance.
        if(sink.node) sink.node(n, x0, baselineY, x-x0);
    }
    return x;
}

export let paintCount = 0;

// Paint one segment: reconcile its lines' glyphs into its own <svg>. The reconcile
// is scoped to this segment (its own `live` set) because a node always lands in
// exactly one segment – segmentation is width-independent – so segments can be
// painted independently. That independence is what makes per-segment painting
// possible (see observeSegments / paintVisibleNow): a long document only pays the
// DOM cost for the segments that have been on screen, not for all of them at once.
export function paintSegment(fontInfo, cache, i) {
    paintCount++;
    restoreLinkStates();              // once this paint is done (a microtask)
    materializeSegment(cache, i);     // a deferred layout is only ever run here
    useGlyphMetrics(cache.metrics);   // a paint may run after another block laid out
    const dom = cache.dom;
    const L   = cache.layout.laid[i];
    const s   = dom.segs[i];
    const stats = cache.stats || (cache.stats = { created: 0, moved: 0, repositioned: 0, removed: 0 });
    const used  = new Set();
    const sink  = reconcileSink(dom.byNode, used, stats, cache);
    const linkRuns = [], markRuns = [];

    // Grow/shrink the pool of per-line group pairs. Detached pairs are kept for
    // later regrowth; their stale children are swept by the live set.
    while (s.pairs.length < L.lines.length) {
        const g = svgEl('g', {'aria-hidden':'true', style:'user-select:none;pointer-events:none'});
        const text = svgEl('text', {});
        text.style.cssText = 'font-weight:normal;font-style:normal';
        s.pairs.push({ g, text, attached: false });
    }
    for (let j = 0; j < s.pairs.length; j++) {
        const pair = s.pairs[j];
        if (j < L.lines.length && !pair.attached) {
            s.svg.appendChild(pair.g);
            s.svg.appendChild(pair.text);
            pair.attached = true;
        } else if (j >= L.lines.length && pair.attached) {
            pair.g.remove();
            pair.text.remove();
            pair.attached = false;
        }
    }

    for (let j = 0; j < L.lines.length; j++) {
        const { ratio, er, x0, fillRatio, fillOrder } = L.lrp[j];
        sink.beginLine(s.pairs[j].text, s.pairs[j].g);
        // On a fill line finite glue is already at natural width (ratio 0), so the
        // single ratio slot carries the fill ratio and fillOrder selects the fill.
        renderNodes(fontInfo, sink, L.lines[j].nodes, x0, L.baselineYs[j],
                    fillOrder ? fillRatio : ratio, er, fillOrder || 0);
        linkRuns.push(...sink.takeLinkRuns());
        markRuns.push(...sink.takeMarkRuns());
    }
    paintLinkHits(s, linkRuns);
    paintMarkBands(s, markRuns, cache);

    // Detach this segment's elements no longer rendered (disc paths toggled off,
    // spaces consumed by new break points). They stay cached in byNode.
    if (s.live) for (const el of s.live) if (!used.has(el)) { el.remove(); stats.removed++; }
    s.live = used;
    s.painted = true;
    s.dirty = false;

    // Overflow cues only. The wrapper's vertical geometry – the headroom padding
    // and the margins that take it back – is fixed at layout time (see
    // layoutDocument). Measuring painted ink here with getBBox was a trap: for
    // SVG text it returns the font's ascent/descent box, not the glyph outlines,
    // so the wrapper was padded for phantom overshoot and every scrollable
    // display carried visibly inflated space above and below.
    if (s.wrap && s.svg.parentNode === s.wrap) {
        updateDisplayOverflowCue(s.wrap);
    }
}

// A reference's hit area: one transparent rect per line it is on, from its
// first glyph to its last, as tall as its glyphs, carrying the reference's
// data-link attributes. The spaces inside a reference are glue, drawn as
// nothing, so without it the pointer between two words of "Section 2" is on
// no link: no underline, and a click does nothing. The rects lie under the
// glyphs (first in the <svg>), so a glyph still takes the pointer over its
// own ink. Rebuilt on every paint – a segment holds a handful at most.
export function paintLinkHits(s, runs) {
    if (!runs.length && !s.hits) return;
    if (!s.hits) {
        s.hits = svgEl('g', { 'aria-hidden': 'true' });
        s.svg.insertBefore(s.hits, s.svg.firstChild);
    }
    s.hits.replaceChildren(...runs.map(r => {
        const rect = svgEl('rect', { x: r.x0, y: r.top, width: Math.max(0, r.x1 - r.x0),
                                     height: Math.max(0, r.bottom - r.top) });
        rect.setAttribute('class', 'latex-link-hit');
        for (const k of ['link', 'linkHref', 'linkLabel', 'linkAction'])
            if (r.el.dataset[k] !== undefined) rect.dataset[k] = r.el.dataset[k];
        rect.style.cssText = 'fill:transparent;cursor:pointer';
        return rect;
    }));
}

// A mark's band: one rect per line it is on, from its first glyph to its
// last and as tall as its glyphs, under the text – the spaces between its
// words are glue, drawn as nothing, so a background on the glyphs alone
// would break at every space. Class latex-mark, the mark's classes in
// data-mark (not as classes: a page's rule for the glyphs, `.key { fill }`,
// would fill the band too) and its id in data-rtx-id. Transparent (as an
// attribute, which any CSS outranks) unless a page styles it:
//   .latex-block rect.latex-mark[data-mark~="key"] { fill: #fde68a; }
export function paintMarkBands(s, runs, cache) {
    if (!runs.length && !s.bands) return;
    if (!s.bands) {
        s.bands = svgEl('g', { 'aria-hidden': 'true', style: 'pointer-events:none' });
        s.svg.insertBefore(s.bands, s.svg.firstChild);
    }
    s.bands.replaceChildren(...runs.map(([index, r]) => {
        const m = (cache.marks && cache.marks[index - 1]) || {};
        const rect = svgEl('rect', { x: r.x0, y: r.top, width: Math.max(0, r.x1 - r.x0),
                                     height: Math.max(0, r.bottom - r.top) });
        rect.setAttribute('class', 'latex-mark');
        if (m.classes) rect.dataset.mark = m.classes;
        if (m.id) rect.dataset.rtxId = m.id;
        rect.setAttribute('fill', 'transparent');     // an attribute: any page rule wins
        return rect;
    }));
}

// Paint every segment regardless of the viewport – for printing, where nothing may
// be left as an empty placeholder.
export function paintDocument(fontInfo, cache) {
    if (!cache.layout) return;
    cache.stats = { created: 0, moved: 0, repositioned: 0, removed: 0 };
    for (let i = 0; i < cache.layout.laid.length; i++) {
        const s = cache.dom.segs[i];
        if (!s.svg) { if (s.sub) paintDocument(fontInfo, s.sub); continue; }
        paintSegment(fontInfo, cache, i);
    }
}
