// SPDX-License-Identifier: AGPL-3.0-or-later

// ── imports (generated by the split tooling; edit freely once the split is done)
import { DEFAULT_WIDTH_PT, ZOOM } from '../engine/core.js';
import { layoutDocument } from '../engine/layout/document.js';
import { paintDocument } from '../engine/paint.js';
import { announceLayout } from './block-data.js';
import { rerenderSurfaces } from '../host/surface.ts';
import { disposePieces } from '../host/inline.ts';
import { debugLog } from './page.js';
import { alignFromEl } from './params.js';
import { scheduleSettle } from './settle.js';
import { observedBlocks, paintVisibleNow, segIO } from './visibility.js';
// ── end of imports

// ── Per-page shared state ─────────────────────────────────────────────────────

// Per-block cache so ResizeObserver can re-render without re-decoding.
// cache holds width-independent layout state (break candidates) and the
// previously rendered SVG so resize can move elements instead of recreating.
export const blockData = new WeakMap(); // el → { doc, lastWidth, lastAlign, params, cache }
// Set while reflowBlock runs a quick reflow (a resize under way): layoutDocument
// then lets the segments far from the screen keep their boxes (see settleAll).
export let quickLayout = false;

// data-latex-width="natural": the block is as wide as its text set on one
// line, like a TeX \hbox – for a word or a label placed in the page's own
// HTML (a button, say). Laid out once at a measure no line of text reaches,
// where each paragraph stays one line at its natural spacing, painted, and
// measured from the left of the block to the farthest reach of its ink (in
// the block's own scale, whatever CSS zoom it sits under). The block then
// keeps that width; its element is given it as a CSS width. Meant for a line
// of text: a display would be centred in the probe and measured from there.
export const NATURAL_PROBE_PT = 5000;
export function naturalWidthPt(el, fontInfo, cache, probePt) {
    paintDocument(fontInfo, cache);
    const root = el.firstElementChild;
    if (!root) return probePt;
    const left = root.getBoundingClientRect().left;
    let right = 0;                                         // unzoomed px from the block's left
    for (const svg of root.querySelectorAll('svg')) {
        const ctm = svg.getScreenCTM();
        if (!ctm || !ctm.a) continue;
        const inv = ctm.inverse(), at = (svg.getBoundingClientRect().left - left) / ctm.a;
        for (const e of svg.querySelectorAll('text, foreignObject'))
            right = Math.max(right, at + new DOMPoint(e.getBoundingClientRect().right, 0).matrixTransform(inv).x);
    }
    // A hair more than the ink, so rounding never breaks the line again.
    return right ? right / ZOOM + 0.5 : probePt;
}

// Re-layout one block for its current width/alignment. Returns false if nothing
// needed doing (so the caller can stay quiet).
export function reflowBlock(el, quick = false) {
    const data = blockData.get(el);
    if (!data) return false;
    // A block inside a collapsed section is display:none and reports clientWidth
    // 0, which would fall through to DEFAULT_WIDTH_PT and re-lay-out the block at
    // a width it is never shown at – leaving that stale layout to be printed.
    // Keep the last good layout; being shown again resizes the element, which
    // fires the observer once more.
    if (el.clientWidth === 0 && !el.dataset.latexWidth) return false;
    const newWidth = data.naturalPt || (el.dataset.latexWidth
        ? parseInt(el.dataset.latexWidth)
        : (el.clientWidth / ZOOM) || DEFAULT_WIDTH_PT);
    // Re-read alignment every time: a media query may have changed --latex-align.
    const newAlign = alignFromEl(el);
    if (Math.abs(newWidth - data.lastWidth) < 0.5 && newAlign === data.lastAlign) return false;
    data.lastWidth = newWidth;
    data.lastAlign = newAlign;
    const params = { ...data.params, align: newAlign };
    const t0  = performance.now();
    // Layout covers the whole block so its height (and the page's scroll
    // geometry) stays correct. Painting, the DOM-heavy part, is then gated to
    // the visible segments. A quick reflow (a resize under way) lays out only
    // the segments near the viewport, and those whose height is cached; the
    // rest keep their boxes until the resize stops (settleBlock).
    quickLayout = quick && !!data.cache.layout;
    let root;
    try {
        root = layoutDocument(data.fontInfo, data.doc, newWidth, params, data.cache);
        if (root !== el.firstElementChild) el.replaceChildren(root);
        remeasureStreams(data.fontInfo, data.doc, newWidth, params, data.cache);
    } finally {
        if (quickLayout) scheduleSettle(el);
        quickLayout = false;
    }
    // Re-layout moved every line: painted segments now hold ink at stale positions.
    // Mark them dirty so they get re-drawn in place – the on-screen ones now (below),
    // each off-screen one when it next scrolls into view (segIO). They are never
    // hidden in the meantime: their <svg> keeps its new reserved size, only its
    // glyphs are stale until repainted.
    markDirty(data.cache);
    const tp = performance.now();
    const repainted = paintVisibleNow(data.fontInfo, data.cache);
    const st = data.cache.stats || {};
    const ls = data.cache.layoutStats || {};
    debugLog(`[latex-viewer] re-render at ${newWidth.toFixed(0)}pt: layout ${(tp - t0).toFixed(1)} ms, paint ${(performance.now() - tp).toFixed(1)} ms (${repainted} visible segment(s); ${st.repositioned||0} repositioned, ${st.created||0} created; segments: ${ls.computed||0} laid out, ${ls.reused||0} reused, ${ls.deferred||0} deferred to scroll)`);
    announceLayout(el);
    return true;
}

// Rebuild a block's DOM from scratch at its current width and repaint the visible
// segments. Used when webfonts finish loading after the first paint: the layout is
// unchanged (it is computed from the document's embedded glyph metrics, never the
// browser font), but discarding cache.dom forces layoutDocument to create fresh
// elements, which is what makes the browser rasterise the glyphs with the
// now-loaded face instead of the fallback it painted first. Break candidates
// (cache.bcs) survive, so this costs a layout pass and a visible-segment repaint,
// not a re-decode.
export function rerenderBlock(el) {
    const data = blockData.get(el);
    if (!data) return;
    // Rebuilding makes fresh <svg>s, so stop observing the old ones (segIO would
    // otherwise hold detached elements). layoutDocument observes the new ones.
    unobserveAll(data.cache);
    disposePieces(data.cache);
    data.cache.dom = null;
    data.cache.layout = null;
    const params = { ...data.params, align: data.lastAlign };
    el.replaceChildren(layoutDocument(data.fontInfo, data.doc, data.lastWidth, params, data.cache));
    remeasureStreams(data.fontInfo, data.doc, data.lastWidth, params, data.cache);
    paintVisibleNow(data.fontInfo, data.cache);
    // Parts the page has mounted elsewhere (host API surfaces) redraw too.
    rerenderSurfaces(el);
    announceLayout(el);
}

// Stream segments (see layoutStreamSegment) nest a whole layout, with its own
// cache, inside the segment's box. These walk a block's cache tree.
export function markDirty(cache) {
    if (!cache.dom) return;
    for (const s of cache.dom.segs) {
        if (s.painted) s.dirty = true;
        if (s.sub) markDirty(s.sub);
    }
}
export function unobserveAll(cache) {
    if (!cache.dom) return;
    for (const s of cache.dom.segs) {
        if (s.svg) segIO.unobserve(s.svg);
        if (s.sub) unobserveAll(s.sub);
    }
}
// A stream segment laid out while its box was not yet in the document could
// not measure the box's inner width and used the column's. Once the block is
// mounted, one more layout pass reads the real width; everything but the
// stream segments comes straight from the cache, so it is cheap.
export function remeasureStreams(fontInfo, doc, widthPt, params, cache) {
    if (!cache.streamsUnmeasured) return;
    cache.streamsUnmeasured = false;
    layoutDocument(fontInfo, doc, widthPt, params, cache);
}

// Repaint every block after a wave of webfonts finishes loading. On a cold cache
// faces arrive in waves *after* content has painted – at init, and lazily on
// scroll – and SVG <text> does not reliably re-rasterise when its face lands
// (Firefox especially). A one-shot repaint on document.fonts.ready is not enough:
// a heading below the first screen is not painted until scrolled to, so if it is
// reached while its (bold) face is still loading it paints in a fallback that the
// already-fired repaint never revisits. So repaint on every loadingdone wave, not
// just once. rerenderBlock also clears the cached elements, so segments painted
// later on scroll are fresh too. Coalesced to one frame; the listener detaches
// once every face has settled. Wired up (see init) only when a face was still
// pending at first paint, so a warm load does none of this.
export let fontRepaintScheduled = false;
export function scheduleFontRepaint() {
    if (fontRepaintScheduled) return;
    fontRepaintScheduled = true;
    requestAnimationFrame(() => {
        fontRepaintScheduled = false;
        for (const el of observedBlocks) rerenderBlock(el);
        if (document.fonts && document.fonts.status === 'loaded' && document.fonts.removeEventListener) {
            document.fonts.removeEventListener('loadingdone', scheduleFontRepaint);
        }
    });
}

// Re-layout runs in a rAF, not synchronously in the observer callback. Doing the
// work inline resizes the observed element (a new layout has a new height), which
// the observer then reports as "ResizeObserver loop completed with undelivered
// notifications" – harmless but noisy. Deferring to the next frame breaks that
// synchronous feedback loop and coalesces bursts of resizes into one pass.
export const roPending = new Set();
export let roScheduled = false;
export const ro = new ResizeObserver(entries => {
    for (const entry of entries) roPending.add(entry.target);
    if (roScheduled) return;
    roScheduled = true;
    requestAnimationFrame(() => {
        roScheduled = false;
        const els = [...roPending];
        roPending.clear();
        for (const el of els) reflowBlock(el, true);
    });
});
