// SPDX-License-Identifier: AGPL-3.0-or-later

// ── imports (generated by the split tooling; edit freely once the split is done)
import { BUILD } from './page.js';
// ── end of imports

// ── Colour maps (optional, page-supplied) ────────────────────────────────────
// reflowtex ships no palette of its own – colour substitution is entirely
// optional and driven by data an integration embeds on the page, so this file
// stays document-agnostic. A block opts in with [data-color-map="<name>"],
// naming one entry of an optional page-supplied JSON island:
//
//   <script id="latex-color-maps" type="application/json">
//     { "<name>": {
//         "colors": { "<theme>": { "<tex-hex>": "<displayed-hex>", … }, … },
//         "tints":  { "<baked-hex>": ["<base-hex>", <percent>], … }
//     }, … }
//   </script>
//
// colors – flat per-theme substitution, keyed by the hex TeX/tikz produced;
//   colours not listed render as-is. Each non-light theme is matched by a
//   class name on <html> (see this file's README's Theming section); adding a
//   theme to a map is just a new key here plus a class the page switcher sets.
//   Rendering reads these through CSS custom properties, so a theme switch
//   restyles already-rendered SVG with no re-render.
//
//   '#000000' is special: it is the DEFAULT text colour (the serializer omits
//   colour on black glyphs, so they carry no inline fill). Mapping it in a
//   theme recolours all default-coloured text there; leaving it unmapped
//   falls back to the page's currentColor, which is why basic dark mode keeps
//   working even for a block with no colour map at all. '#ffffff' is special
//   too, but is not something a map needs to set: it always tracks
//   --latex-page-bg (see below), because a flat white fill in a TikZ/PDF
//   picture means "the paper", not a deliberate colour choice – true with or
//   without a colour map, so it's a fixed default rather than map data.
//
// tints – colours TeX produced by mixing a base colour into the page, e.g.
//   `red!20!white` is red at 20% over the paper. TeX resolves that to flat
//   RGB at compile time, so what arrives is a baked hex with no trace of how
//   it was built – and a tint of a *white* page reads wrong on a dark one.
//   Re-deriving the mix at runtime, against whatever --latex-page-bg
//   currently is, keeps the intent: a tint follows both its base colour and
//   the current background. This is not the same as opacity, and must not be
//   reimplemented with it – these fills are opaque on purpose, masking the
//   drawing underneath. Each entry is baked-hex: [base-hex, percent-of-base].
//
// --latex-page-bg is deliberately not part of this data: TeX has no notion of
// the page's colour, so it is the *page's* responsibility (its own theme
// CSS), not a colour map's – e.g. `:root.dark { --latex-page-bg: #0c0a09; }`
// alongside wherever else that theme sets its background. Unset, it falls
// back to the CSS `Canvas` system colour, so tints and the viewer's own UI
// chrome (the display scrollbox, citation popovers) still land somewhere
// sane with zero configuration.

export function colorFill(c) {
    return `var(--latex-color-${c.slice(1)}, ${c})`;
}

export let colorMapsInstalled = false;
export function installColorMaps() {
    if (colorMapsInstalled) return;
    colorMapsInstalled = true;
    const island = document.getElementById('latex-color-maps');
    let maps = {};
    if (island) {
        try { maps = JSON.parse(island.textContent); }
        catch (e) { console.error('[latex-viewer] malformed #latex-color-maps JSON', e); }
    }

    // TeX has no notion of the page's colour, so a flat white fill in a
    // TikZ/PDF picture (the paper, not a deliberate colour choice) needs to
    // track whatever the page's background actually is. True for every
    // picture regardless of colour map, so – unlike the rest of this
    // function – this is not map data: it is a fixed, unconditional default,
    // on :root so a map's own '#ffffff' entry (if any) still wins by
    // specificity.
    let css = ':root { --latex-color-ffffff: var(--latex-page-bg, Canvas); }\n';
    for (const [name, map] of Object.entries(maps)) {
        const sel = `.latex-block[data-color-map=${JSON.stringify(name)}]`;
        for (const [theme, entries] of Object.entries(map.colors ?? {})) {
            const decls = Object.entries(entries)
                .map(([src, dst]) => `  --latex-color-${src.slice(1)}: ${dst};`);
            if (decls.length === 0) continue;
            const scoped = theme === 'light' ? sel : `:root.${theme} ${sel}`;
            css += scoped + ' {\n' + decls.join('\n') + '\n}\n';
        }
        // A theme scoped to part of the page: data-latex-theme="T" on any
        // ancestor gives the blocks inside theme T's colours whatever the
        // page's own theme is (a theme preview beside an example, say). Every
        // colour any theme of this map remaps is declared, so a scoped theme
        // also undoes the page theme's substitutions: a colour T leaves alone
        // goes back to itself, and default text back to currentColor. The
        // :root prefix outranks the page-theme rules above; being later wins
        // the tie with a page-theme rule of the same specificity.
        const allSrc = new Set();
        for (const entries of Object.values(map.colors ?? {})) for (const src of Object.keys(entries)) allSrc.add(src);
        if (allSrc.size) {
            const themes = new Set(['light', ...Object.keys(map.colors ?? {})]);
            for (const theme of themes) {
                const entries = (map.colors ?? {})[theme] ?? {};
                const decls = [...allSrc].map(src => `  --latex-color-${src.slice(1)}: `
                    + (entries[src] ?? (src === '#000000' ? 'currentColor' : src)) + ';');
                css += `:root [data-latex-theme=${JSON.stringify(theme)}] ${sel} {\n` + decls.join('\n') + '\n}\n';
            }
        }
        const tintDecls = Object.entries(map.tints ?? {}).map(([hex, [base, pct]]) =>
            `  --latex-color-${hex.slice(1)}: color-mix(in srgb, `
          + `var(--latex-color-${base.slice(1)}, ${base}) ${pct}%, `
          + `var(--latex-page-bg, Canvas));`);
        if (tintDecls.length) css += sel + ' {\n' + tintDecls.join('\n') + '\n}\n';
    }
    // Default-coloured glyphs carry no inline fill; route them through the
    // '#000000' variable with currentColor as fallback – works with zero
    // colour maps installed. The html prefix outranks the page's own
    // `.latex-block svg text` rule regardless of stylesheet order.
    //
    // Deliberately not 'rect': rules set their fill inline, and this rule's
    // specificity would otherwise reach inside a tikzpicture and repaint every
    // coloured shape in the drawing as text.
    css += 'html .latex-block svg text, html .latex-block svg tspan '
         + '{ fill: var(--latex-color-000000, currentColor); }\n';
    const s = document.createElement('style');
    s.textContent = css;
    document.head.appendChild(s);
    document.documentElement.setAttribute('data-latex-viewer', BUILD);
}
