// SPDX-License-Identifier: AGPL-3.0-or-later

// ── imports (generated by the split tooling; edit freely once the split is done)
import { ZOOM } from '../engine/core.js';
import { SCRIPT_URL, api } from './page.js';
// ── end of imports

// fontInfo is intentionally NOT global – font IDs are per-compilation and collide
// across blocks (e.g. both block 1 and block 2 may use ID 54 for different files).
// Each block gets its own map returned from registerFonts().
export const registeredFontFaces = new Set();

export let   fontUrlMap          = {};     // original font filename → served filename (see loadFontMap)
// Fonts are deployed beside this script. Resolving from the script URL keeps the
// viewer portable across a domain root, arbitrary subpaths, and local previews
// (including a page opened straight off disk over file://, where an absolute
// '/fonts/'-style path can't resolve at all – see loadFontMap's handling of
// data-fonts-base below, which must preserve this same resolution).
export let   fontBase            = SCRIPT_URL
    ? new URL('fonts/', SCRIPT_URL).href
    : '/fonts/';
export let   fontsPending        = false;  // a face still had to be fetched at first paint (see registerFonts / init)

// ── Font loading ──────────────────────────────────────────────────────────────

export async function registerFonts(fontsData) {
    const fontInfo = {};
    const fileToFamily = {};
    let css = '';
    for (const f of Object.values(fontsData)) {
        const file = f.filename;
        if (fileToFamily[file]) continue;
        // A font the serializer could not resolve to an OTF file (filename
        // 'unknown' – e.g. a Type1 math font with no OpenType form) has nothing to
        // fetch. Map it to a system serif so its glyphs fall back, rather than
        // emitting an @font-face that is guaranteed to 404.
        if (!file || file === 'unknown') { fileToFamily[file] = 'serif'; continue; }
        // The family is keyed off the font's *original* name (its stable identity
        // across blocks); the file it is fetched from comes from the font map,
        // which for a modified font is a renamed, content-hashed file (the map is
        // empty on pages that don't ship it, so it falls back to the name as-is).
        const family  = file.replace(/\.otf$/i, '').replace(/[^a-zA-Z0-9]/g, '_');
        const servedFile = fontUrlMap[file] || file;
        if (!registeredFontFaces.has(file)) {
            css += `@font-face { font-family: '${family}'; src: url('${fontBase}${servedFile}'); }\n`;
            registeredFontFaces.add(file);
        }
        fileToFamily[file] = family;
    }

    if (css) {
        const s = document.createElement('style');
        s.textContent = css;
        document.head.appendChild(s);
    }

    // No font-feature-settings are applied: glyphs that are not the cmap
    // default for their codepoint (script-size variants, accents, …) are
    // rewritten to dedicated PUA codepoints by prebuild.py, so every glyph
    // renders identically in every browser without relying on GSUB features.
    for (const [idStr, f] of Object.entries(fontsData)) {
        fontInfo[idStr] = {
            family:  fileToFamily[f.filename],
            size_px: (f.size_sp / 65536) * ZOOM,
            // A font with no OTF to load: its glyphs are drawn as metric boxes
            // (see the sink's glyph handler) so the missing ink is visible.
            unresolved: !f.filename || f.filename === 'unknown',
            // Microtypography as TeX had it (FontInfo in latex.proto): the
            // quad protrusion is relative to, \expandglyphsinfont's three
            // arguments (null = the font does not expand), and per-character
            // \lpcode/\rpcode/\efcode for the characters that have any. Handed
            // to an external breaker through the hook's helpers; the built-in
            // breaker keeps its own protrusion table and expansion limits.
            quad:   f.quad || 0,
            expand: (f.expand_stretch || f.expand_shrink)
                        ? { stretch: f.expand_stretch || 0, shrink: f.expand_shrink || 0,
                            step: f.expand_step || 0 }
                        : null,
            codes:  new Map((f.codes || []).map(c => [c.char, c])),
        };
    }

    const families = [...new Set(Object.values(fileToFamily))].filter(fam => fam !== 'serif');

    // A face that still has to be fetched (cold cache) can first paint as a
    // fallback, and SVG <text> – notably in Firefox – does not always re-rasterise
    // when the real face arrives. Note it so init() can force one repaint once the
    // faces have settled; a warm load (every face already cached, so the first
    // paint is already correct) leaves this false and pays for no second render.
    const check = fam => { try { return document.fonts.check(`12px '${fam}'`); } catch { return false; } };
    if (document.fonts && families.some(fam => !check(fam))) fontsPending = true;

    // allSettled, not all: a font that fails to load (a missing file, a network
    // blip) must not reject and blank the whole block – its glyphs fall back (or
    // are drawn as metric boxes; see the sink). 'serif' is a system family and
    // needs no loading.
    await Promise.allSettled(families.map(fam => document.fonts.load(`12px '${fam}'`)));
    // A face whose file could not be fetched settles with status 'error'
    // (load() itself still resolves). Tell the reader, once per page.
    if (document.fonts) {
        const failed = [];
        for (const face of document.fonts) {
            const fam = String(face.family).replace(/^['"]|['"]$/g, '');
            if (face.status === 'error' && families.includes(fam)) {
                const file = Object.keys(fileToFamily).find(k => fileToFamily[k] === fam);
                // by the font's own name: cmr12, not the served cmr12.reflowtex-dfb1fe6f.otf
                failed.push(file ? file.replace(/\.otf$/i, '').replace(/\.reflowtex-[0-9a-f]+$/, '') : fam);
            }
        }
        if (failed.length) reportFontFailure(failed);
    }
    return fontInfo;
}

// ── A warning when fonts fail ─────────────────────────────────────────────────
// Without its fonts a block still lays out (the metrics travel with the
// document) but draws its glyphs in a stand-in face, or not at all for the
// symbol fonts of mathematics – which a reader cannot tell from a broken page.
// So a failed download shows a bar at the bottom of the window, as a cookie
// notice does, naming the fonts and offering a reload. A page may style it
// (.latex-font-warning) or switch it off: window.reflowtex.fontWarning = false.
export const failedFonts = new Set();
export let fontWarning = null;
export function reportFontFailure(names) {
    for (const n of names) failedFonts.add(n);
    if (api.fontWarning === false || !document.body) return;
    if (!fontWarning) {
        const st = document.createElement('style');
        st.textContent = `
          .latex-font-warning { position: fixed; left: 50%; bottom: 16px; transform: translateX(-50%);
            z-index: 2147483000; box-sizing: border-box; width: min(44rem, calc(100vw - 32px));
            display: flex; align-items: center; gap: 12px; padding: 12px 14px 12px 18px;
            font: 14px/1.45 ui-sans-serif, system-ui, sans-serif; color: #fff; background: #2b2622;
            border-radius: 12px; box-shadow: 0 8px 28px rgba(0,0,0,.28); }
          .latex-font-warning p { margin: 0; flex: 1; }
          .latex-font-warning strong { color: #ffcf8a; }
          .latex-font-warning button { font: inherit; font-weight: 600; color: inherit; cursor: pointer;
            border: 1px solid rgba(255,255,255,.35); background: none; border-radius: 8px; padding: 6px 12px; }
          .latex-font-warning button:hover { background: rgba(255,255,255,.12); }
          .latex-font-warning button[data-act="close"] { border: 0; padding: 6px 8px; font-size: 18px; line-height: 1; opacity: .8; }
          @media print { .latex-font-warning { display: none; } }`;
        document.head.appendChild(st);
        fontWarning = document.createElement('div');
        fontWarning.className = 'latex-font-warning';
        fontWarning.setAttribute('role', 'alert');
        fontWarning.innerHTML = '<p></p><button type="button" data-act="reload">Reload</button>'
            + '<button type="button" data-act="close" aria-label="Dismiss">\u00d7</button>';
        fontWarning.addEventListener('click', e => {
            const act = e.target.closest('button')?.dataset.act;
            if (act === 'reload') location.reload();
            if (act === 'close') fontWarning.hidden = true;
        });
        document.body.appendChild(fontWarning);
    }
    const list = [...failedFonts];
    const shown = list.slice(0, 4).join(', ') + (list.length > 4 ? ` and ${list.length - 4} more` : '');
    fontWarning.querySelector('p').innerHTML = '<strong>Some fonts could not be downloaded</strong> '
        + `(${shown.replace(/[&<>]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' })[c])}). `
        + 'Text may appear in a stand-in font, and mathematics may be missing.';
}

// Optional: {original filename → served filename} written into the page as a JSON
// island (prebuild.py / build.py). Lets a modified font be fetched from its
// renamed, content-hashed file while blocks still refer to it by its original
// name. Absent → registerFonts falls back to the original name.
export function loadFontMap() {
    const el = document.getElementById('latex-font-map');
    if (!el) return;
    // Optional override for where @font-face URLs resolve from – a relative
    // value (e.g. 'fonts/') is resolved against the script's own URL, same as
    // the default above, so it stays file://-safe; an absolute one (a scheme,
    // or a leading '/') is used as-is, e.g. to point at a CDN. Malformed input
    // (or no SCRIPT_URL to resolve a relative one against) leaves the default.
    const base = el.getAttribute('data-fonts-base');
    if (base) {
        const withSlash = base.endsWith('/') ? base : base + '/';
        try { fontBase = new URL(withSlash, SCRIPT_URL).href; }
        catch { /* keep the default */ }
    }
    if (!el.textContent.trim()) return;
    try { fontUrlMap = JSON.parse(el.textContent); }
    catch { fontUrlMap = {}; }
}
