// SPDX-License-Identifier: AGPL-3.0-or-later

// ── imports (generated by the split tooling; edit freely once the split is done)
import { closeFootnote, installFootnotes } from '../defaults/footnotes.js';
import { DEFAULT_WIDTH_PT, ZOOM } from '../engine/core.js';
import { layoutDocument, newBlockKey } from '../engine/layout/document.js';
import { allData, announceLayout, docData } from './block-data.js';
import { registerBlock, unregisterBlock } from '../host/host.ts';
import { disposeSurfaces } from '../host/surface.ts';
import { disposeHosts } from '../host/block-hosts.ts';
import { disposePieces } from '../host/inline.ts';
import { removeMarginNotes } from '../defaults/margin-notes.ts';
import { inspectable } from '../host/inspect.js';
import { installLinks, installWidgetStates, pageLabels } from '../host/links.js';
import { applySlots, slotBlocks } from '../host/slots.js';
import { installViewerStyles } from '../index.js';
import {
    NATURAL_PROBE_PT, blockData, naturalWidthPt, reflowBlock, remeasureStreams, ro, scheduleFontRepaint, unobserveAll,
} from './blocks.js';
import { installColorMaps } from './colour.js';
import { decodeBlock, loadSchema } from './decode.js';
import { fontsPending, loadFontMap, registerFonts } from './fonts.js';
import { debugLog } from './page.js';
import { paramsFromEl } from './params.js';
import { observedBlocks, paintVisibleNow } from './visibility.js';
// ── end of imports

export let docSeq = 0;

// ── Initialisation ────────────────────────────────────────────────────────────

// Hang each picture's payload on the node that draws it, once per block, so
// the renderer never has to thread the document through every call.
export function resolvePictures(doc) {
    const pics = doc.pictures;
    if (!pics || !pics.length) return;
    const walk = nodes => {
        for (const n of nodes) {
            if (n.type === 'picture' && n.picture) n.pic = pics[n.picture - 1];
            for (const k of ['children', 'replace', 'pre', 'post']) {
                if (n[k]) walk(n[k]);
            }
        }
    };
    for (const p of doc.paragraphs) walk(p.nodes);
    for (const it of doc.content || []) if (it.box) walk(it.box.children || []);
    for (const st of doc.streams || []) {
        for (const it of st.content || []) if (it.box) walk(it.box.children || []);
    }
}


export async function initBlock(el) {
    const nodelistB64 = el.dataset.nodelistB64;
    if (!nodelistB64) throw new Error('Missing data-nodelist-b64 attribute');

    const t0        = performance.now();
    const doc       = decodeBlock(nodelistB64);
    resolvePictures(doc);
    // Declare this block's labels before anything of it is painted, so its own
    // references resolve without needing the page map at all. Blocks initialise
    // in order, so a reference to a label defined by a *later* block on the same
    // page still needs the map – which for a site that ships one, it has.
    for (const label of doc.anchors || []) pageLabels.add(label);
    const t1        = performance.now();
    const fontsData = Object.fromEntries(doc.fonts.map(f => [String(f.id), f]));
    const fontInfo  = await registerFonts(fontsData);
    const t2        = performance.now();

    const params  = paramsFromEl(el);
    const natural = el.dataset.latexWidth === 'natural';
    let widthPt = natural ? NATURAL_PROBE_PT : el.dataset.latexWidth
        ? parseInt(el.dataset.latexWidth)
        : (el.clientWidth / ZOOM) || DEFAULT_WIDTH_PT;
    // bcs: Map(paraIdx → break candidates), built lazily. blockEl and relayout
    // are for the host API (block-hosts.ts): the block the layout's instances
    // belong to, and how to lay it out again when a host's edges change.
    // blockKey now, not at the first layout: widgets and texts are applied
    // before it, and find their instances by it.
    const cache = { bcs: null, dom: null, layout: null, stats: null, blockEl: el, blockKey: newBlockKey(),
                    relayout: () => { if (blockData.get(el)) { blockData.get(el).lastWidth = -1; reflowBlock(el); } } };
    const data  = { doc, fontInfo, lastWidth: widthPt, lastAlign: params.align, params, cache, painted: false,
                    seq: ++docSeq, el };
    blockData.set(el, data);
    docData.set(doc, data);
    allData.push(data);
    inspectable.add(el);
    if (doc.slots && doc.slots.length) {
        slotBlocks.add(el);
        applySlots(fontInfo, doc);
    }
    // Layout first (this sets the svg's final height), then decide from the
    // block's resulting position whether to paint now or on approach. Blocks
    // are initialised top to bottom, so earlier blocks already have their
    // final heights when later ones measure their distance to the viewport.
    el.replaceChildren(layoutDocument(fontInfo, doc, widthPt, params, cache));
    if (natural) {
        widthPt = data.naturalPt = naturalWidthPt(el, fontInfo, cache, widthPt);
        data.lastWidth = widthPt;
        el.style.width = (widthPt * ZOOM) + 'px';
        el.replaceChildren(layoutDocument(fontInfo, doc, widthPt, params, cache));
    }
    remeasureStreams(fontInfo, doc, widthPt, params, cache);
    // The document's outline (sections, subsections, theorems), for a page to
    // build a table of contents from. Each entry's `id` is the id of its
    // anchor element, which exists once the block is laid out – now. Also
    // kept on the element for a script that attaches later.
    if (doc.outline && doc.outline.length) {
        const entries = doc.outline.map(e => ({
            kind: e.kind || '', env: e.env || '', level: e.level || 0,
            number: e.number || '', title: e.title || '',
            id: (doc.anchors || [])[(e.anchor || 0) - 1] || null,
        }));
        el.reflowtexOutline = entries;
        el.dispatchEvent(new CustomEvent('reflowtex:outline', { bubbles: true, detail: { block: el, entries } }));
    }
    const t3 = performance.now();
    // Paint the segments near the viewport now; layoutDocument has already set the
    // IntersectionObserver watching the rest, which paint (once, for good) as they
    // are scrolled toward. Never un-painted.
    paintVisibleNow(fontInfo, cache);
    data.painted = true;
    announceLayout(el);
    registerBlock(data);
    observedBlocks.add(el);
    const t4 = performance.now();
    ro.observe(el);
    // A segment is the paint unit: a run of consecutive text paragraphs, or a single
    // display. The rest are painted as they approach the viewport (segIO).
    const segTotal   = cache.dom.segs.length;
    const segPainted = cache.dom.segs.reduce((n, s) => n + (s.painted ? 1 : 0), 0);
    return { decode: t1 - t0, fonts: t2 - t1, layout: t3 - t2, paint: t4 - t3,
             total: t4 - t0, segTotal, segPainted };
}

// What the page needs once, before its first block: the schema, the font
// map, the viewer's styles and its page-wide handlers. Idempotent, so a block
// mounted later (host.mount) on a page that had none finds it done.
let installed = false;
export function installPage() {
    if (installed) return;
    installed = true;
    installColorMaps();
    installFootnotes();
    installViewerStyles();
    installLinks();
    installWidgetStates();
    loadSchema();
    loadFontMap();
}

// Cold cache: at least one face was still loading when we first painted, so
// some SVG glyphs may be showing in a fallback. Faces can finish in several
// waves, and content keeps painting as the reader scrolls, so repaint on every
// loadingdone wave (and once more when all faces settle) rather than a single
// time – see scheduleFontRepaint. Guarded by fontsPending so a warm load, where
// the first paint is already correct, does none of this.
let watchingFonts = false;
function watchFonts() {
    if (watchingFonts || !fontsPending || !document.fonts) return;
    watchingFonts = true;
    if (document.fonts.addEventListener) document.fonts.addEventListener('loadingdone', scheduleFontRepaint);
    if (document.fonts.ready) document.fonts.ready.then(scheduleFontRepaint);
}

// One block at a time: a block asked for twice (init and host.mount) is
// rendered once.
const rendering = new WeakMap();        // el → the promise of its initBlock
function renderOnce(el) {
    if (blockData.get(el)) return Promise.resolve(null);
    let p = rendering.get(el);
    if (!p) { p = initBlock(el).finally(() => rendering.delete(el)); rendering.set(el, p); }
    return p;
}

/** host.mount: render one block element, added after the page loaded. */
export async function mountBlock(el) {
    installPage();
    await renderOnce(el);
    watchFonts();
}

export async function init() {
    const blocks = [...document.querySelectorAll('[data-nodelist-b64]')];
    if (blocks.length === 0) return;

    const tStart = performance.now();
    installPage();

    // Sequential to avoid font registration races
    let idx = 0, segPainted = 0, segTotal = 0;
    for (const el of blocks) {
        try {
            const t = await renderOnce(el);
            if (!t) continue;
            segPainted += t.segPainted; segTotal += t.segTotal;
            debugLog(`[latex-viewer] block ${++idx}/${blocks.length}: ${t.total.toFixed(1)} ms `
                + `(decode ${t.decode.toFixed(1)}, fonts ${t.fonts.toFixed(1)}, layout ${t.layout.toFixed(1)}, paint ${t.paint.toFixed(1)}) `
                + `– ${t.segPainted}/${t.segTotal} segments painted`);
        }
        catch (e) { el.textContent = `Render error: ${e.message}`; console.error(e); }
    }
    const segDeferred = segTotal - segPainted;
    debugLog(`[latex-viewer] ${blocks.length} block(s) in ${(performance.now() - tStart).toFixed(1)} ms `
        + `· ${segPainted}/${segTotal} segments painted`
        + (segDeferred ? `, ${segDeferred} deferred (painted on scroll)` : ''));
    watchFonts();
}

/** block.destroy: undo everything the block was given, and forget it. */
export function destroyBlock(el) {
    const data = blockData.get(el);
    if (!data) return;
    closeFootnote();
    removeMarginNotes(data);
    disposeSurfaces(el);
    disposeHosts(data.cache);
    disposePieces(data.cache);
    unobserveAll(data.cache);
    ro.unobserve(el);
    observedBlocks.delete(el);
    slotBlocks.delete(el);
    inspectable.delete(el);
    const i = allData.indexOf(data);
    if (i >= 0) allData.splice(i, 1);
    docData.delete(data.doc);
    blockData.delete(el);
    unregisterBlock(el);
    el.replaceChildren();
    el.style.removeProperty('width');
    el.style.removeProperty('padding-bottom');
}
