// SPDX-License-Identifier: AGPL-3.0-or-later

// ── imports (generated by the split tooling; edit freely once the split is done)
import { layoutDocument } from '../engine/layout/document.js';
import { blockData } from './blocks.js';
import { debugLog } from './page.js';
import { paintVisibleNow } from './visibility.js';
// ── end of imports

// ── Settling after a resize ───────────────────────────────────────────────────
// A resize reflows quickly (see reflowBlock): only what is on or near the
// screen is re-broken, so a continuous drag stays cheap however long the page.
// Once the width has held still for SETTLE_MS, every segment that kept its old
// box is laid out at the new width. That changes heights off screen, above the
// reader as well as below, so the pass holds the scroll position itself: it
// notes where the first segment on screen is, turns the browser's scroll
// anchoring off for the pass (so the correction is not applied twice, and is
// applied in browsers without anchoring too), and scrolls by however far that
// segment moved.
export const SETTLE_MS = 150;
export const unsettled = new Set();
export let settleTimer = 0;
export function scheduleSettle(el) {
    unsettled.add(el);
    clearTimeout(settleTimer);
    settleTimer = setTimeout(settleAll, SETTLE_MS);
}
export function settleAll() {
    settleTimer = 0;
    const els = [...unsettled].filter(el => el.isConnected);
    unsettled.clear();
    if (!els.length) return;
    const t0 = performance.now();
    const scroller = scrollerOf(els[0]);
    const viewTop = scroller === document.scrollingElement ? 0 : scroller.getBoundingClientRect().top;
    let anchor = null;
    for (const el of els) {
        const data = blockData.get(el);
        const a = data && firstSegmentOnScreen(data.cache, viewTop);
        if (a && (!anchor || a.top < anchor.top)) anchor = a;
    }
    const restore = holdScrollAnchoring(scroller);
    for (const el of els) settleBlock(el);
    if (anchor) {
        const d = anchor.el.getBoundingClientRect().top - anchor.top;
        if (d) scroller.scrollTop += d;
    }
    requestAnimationFrame(restore);
    debugLog(`[latex-viewer] settled ${els.length} block(s) in ${(performance.now() - t0).toFixed(1)} ms`);
}
// Lay out, at the width it was last reflowed to, every segment of a block
// that a quick reflow left with its old box. The segments near the screen
// come straight from the cache, so nothing visible changes.
export function settleBlock(el) {
    const data = blockData.get(el);
    if (!data || !data.cache.layout) return;
    const params = { ...data.params, align: data.lastAlign };
    layoutDocument(data.fontInfo, data.doc, data.lastWidth, params, data.cache);
    paintVisibleNow(data.fontInfo, data.cache);
}
// The first segment box, in document order, that reaches below the top of
// the scroller's viewport – the innermost one, inside a stream – and where it
// is now. Holding its top still holds what the reader is looking at.
export function firstSegmentOnScreen(cache, viewTop) {
    if (!cache.dom) return null;
    for (const s of cache.dom.segs) {
        if (!s.box.getClientRects().length) continue;   // not rendered (a collapsed stream)
        const r = s.box.getBoundingClientRect();
        if (r.bottom <= viewTop) continue;
        if (r.top >= viewTop + (window.innerHeight || 800)) return null;
        return (s.sub && firstSegmentOnScreen(s.sub, viewTop)) || { el: s.box, top: r.top };
    }
    return null;
}
export function scrollerOf(el) {
    for (let p = el.parentElement; p && p !== document.body && p !== document.documentElement; p = p.parentElement) {
        const oy = getComputedStyle(p).overflowY;
        if ((oy === 'auto' || oy === 'scroll' || oy === 'overlay') && p.scrollHeight > p.clientHeight) return p;
    }
    return document.scrollingElement || document.documentElement;
}
// Turn the browser's scroll anchoring off on a scroller (for the page, on
// <html> and <body>); returns what turns it back on.
export function holdScrollAnchoring(scroller) {
    const els = scroller === document.scrollingElement
        ? [document.documentElement, document.body] : [scroller];
    const was = els.map(e => e.style.overflowAnchor);
    for (const e of els) e.style.overflowAnchor = 'none';
    return () => els.forEach((e, k) => { e.style.overflowAnchor = was[k]; });
}
