// SPDX-License-Identifier: AGPL-3.0-or-later

// ── imports (generated by the split tooling; edit freely once the split is done)
import { paintDocument, paintSegment } from '../engine/paint.js';
import { announceLayout } from '../host/asides.js';
import { blockData } from './blocks.js';
// ── end of imports

// ── Per-segment painting (grow-only) ──────────────────────────────────────────
// Layout always covers the whole block (cheap pure computation, and it must, so
// the block's height keeps scroll geometry exact). Painting – placing tens of
// thousands of glyph elements – is the DOM-heavy part, so a segment is painted
// only once it comes within a viewport of the screen. Which segments those are is
// tracked by an IntersectionObserver on each segment's own <svg>, i.e. from the
// real element positions. It is deliberately NOT computed from a running height
// model: a model would have to reproduce every margin and wrapper detail of the
// real layout (a scrollable display's headroom padding and compensating margins,
// say – see layoutDocument), so it drifts from it and, near the bottom of a long
// page, mis-gates segments that are in fact on screen. Observing the elements has
// no such drift and costs no per-frame measurement.
//
// Painting is grow-only: a segment, once painted, is never hidden. Scrolling can
// only ever add ink, never remove it, so text never vanishes as the page moves. A
// width change re-draws the painted segments in place (their glyphs move) – the
// visible ones at once, the rest when scrolled to – but still never blanks them.
export const observedBlocks = new Set();       // blocks (for font-repaint + print)
export const segRef = new WeakMap();           // a segment's <svg> → { cache, i }
export const segIO = new IntersectionObserver(entries => {
    const painted = new Set();
    for (const e of entries) {
        const ref = segRef.get(e.target);
        const s = ref && ref.cache.dom && ref.cache.dom.segs[ref.i];
        if (!s) continue;
        s.intersecting = e.isIntersecting;
        if (e.isIntersecting && (!s.painted || s.dirty)) {
            paintSegment(ref.cache.fontInfo, ref.cache, ref.i);
            const block = ref.cache.dom.root.closest('[data-nodelist-b64]');
            if (block) painted.add(block);
        }
    }
    // Newly drawn lines may hold aside marks a page places things by.
    for (const block of painted) announceLayout(block);
}, { rootMargin: '100% 0px' });         // one-viewport vertical lookahead

// Observe each not-yet-observed segment of a block. Idempotent: a segment's <svg>
// is created once and reused across reflows, so its observation persists (only a
// font rerender, which rebuilds the DOM, makes new ones – see rerenderBlock).
export function observeSegments(cache) {
    const segs = cache.dom.segs;
    for (let i = 0; i < segs.length; i++) {
        const s = segs[i];
        if (s.observed || !s.svg) continue;   // a stream segment has no <svg> of its own
        segRef.set(s.svg, { cache, i });
        segIO.observe(s.svg);
        s.observed = true;
    }
}

// Paint, synchronously, every segment that needs it (never painted, or dirtied by
// a reflow) and is within a viewport of the screen. Reads each segment's real box,
// so it shares the IntersectionObserver's immunity to height drift and is correct
// under page zoom (getBoundingClientRect and innerHeight are the same space). Two
// passes – measure all, then paint – because painting mutates the DOM and would
// otherwise force a fresh layout between measurements. Used for the first paint and
// after a reflow; the observer covers whatever scrolls into view later.
export function paintVisibleNow(fontInfo, cache) {
    if (!cache.dom) return 0;
    cache.stats = { created: 0, moved: 0, repositioned: 0, removed: 0 };
    const segs = cache.dom.segs;
    const vh = window.innerHeight || 800, M = vh;
    const todo = [], nested = [];
    for (let i = 0; i < segs.length; i++) {
        const s = segs[i];
        // A stream segment paints through its nested cache – after this pass,
        // so the measurements below are not interleaved with DOM writes.
        if (!s.svg) { if (s.sub) nested.push(s.sub); continue; }
        if (s.painted && !s.dirty) continue;
        // Not rendered at all (inside a collapsed stream, say): its rect is all
        // zeros, which would pass the test below. The IntersectionObserver
        // paints it once it is shown.
        if (!s.svg.getClientRects().length) continue;
        const r = s.svg.getBoundingClientRect();
        if (r.bottom > -M && r.top < vh + M) todo.push(i);
    }
    for (const i of todo) paintSegment(fontInfo, cache, i);
    let n = todo.length;
    for (const c of nested) n += paintVisibleNow(fontInfo, c);
    return n;
}

export let vpScheduled = false;
export function scheduleViewportPaint() {
    if (vpScheduled) return;
    vpScheduled = true;
    requestAnimationFrame(() => {
        vpScheduled = false;
        for (const el of observedBlocks) {
            const data = blockData.get(el);
            if (data) paintVisibleNow(data.fontInfo, data.cache);
        }
    });
}
// Scrolling is handled by the IntersectionObserver (no per-frame work). A viewport
// resize – or the synthetic resize the zoom control fires – can change which
// segments are on screen without the observer necessarily re-firing, so re-check
// the visible set then.
window.addEventListener('resize', scheduleViewportPaint, { passive: true });

// Print needs every segment painted (off-screen ones are empty until then). Grow-
// only means they simply stay painted afterwards, so there is nothing to restore.
window.addEventListener('beforeprint', () => {
    for (const el of observedBlocks) {
        const data = blockData.get(el);
        if (data) paintDocument(data.fontInfo, data.cache);
    }
});
