// SPDX-License-Identifier: AGPL-3.0-or-later
// latex-viewer.js – the viewer's entry module (bundled by build.sh)
// Finds every [data-nodelist-b64] element on the page and renders it as an
// inline SVG using Knuth-Plass line breaking.
//
// Data is embedded in the HTML at Hugo build time (via prebuild.py).
// No runtime fetching of binary files – works fully offline.
//
// Depends on protobuf.min.js being loaded first (exposes global `protobuf`).

// ── imports (generated by the split tooling; edit freely once the split is done)
import { ZOOM } from './engine/core.js';
import { init } from './runtime/init.js';
import { installHost } from './host/host.ts';
// ── end of imports

// The viewer's own styles: what it draws itself (margin notes, the unit
// TeX's sizes are given in) and what is true of every control on paper. The
// looks of the companion package's kinds – notes, hints, boxed theorems,
// accordions, Lean – are the companion's (src/companion/companion.css).
export function installViewerStyles() {
    const st = document.createElement('style');
    st.textContent = `
      /* One TeX point in CSS px, for styles that size by TeX's measures. */
      :root { --latex-pt: ${ZOOM}px; }
      /* Margin notes (placeMarginNotes): the layer is the block's, the notes
         beside it; where there is no room, a mark in the text opens one. */
      .latex-margin { position: absolute; left: 0; top: 0; width: 0; height: 0; }
      .latex-margin-note { position: absolute; }
      .latex-margin-note .latex-block { margin: 0; }
      .latex-margin-mark { position: absolute; transform: translate(-15%, -120%); margin: 0; padding: 0 .15em;
        border: 0; border-radius: 3px; background: none; color: inherit; opacity: .7; cursor: pointer;
        font: 600 .75em/1 ui-sans-serif, system-ui, sans-serif; }
      .latex-margin-mark:hover, .latex-margin-mark:focus-visible { opacity: 1; background: color-mix(in srgb, currentColor 10%, transparent); }
      .latex-margin-mark[hidden], .latex-margin-note[hidden] { display: none; }
      @media print {
        .latex-margin { display: none; }
        /* Controls do nothing on paper. More specific than the page's
           .latex-block svg .latex-link colour rule, which is also !important. */
        .latex-block svg .latex-link.latex-action { fill: transparent !important; }
      }
    `;
    document.head.appendChild(st);
}

installHost();
document.addEventListener('DOMContentLoaded', init);
