// SPDX-License-Identifier: AGPL-3.0-or-later
// latex-viewer.js – the viewer's entry module (bundled by build.sh)
// Finds every [data-nodelist-b64] element on the page and renders it as an
// inline SVG using Knuth-Plass line breaking.
//
// Data is embedded in the HTML at Hugo build time (via prebuild.py).
// No runtime fetching of binary files – works fully offline.
//
// Depends on protobuf.min.js being loaded first (exposes global `protobuf`).

// ── imports (generated by the split tooling; edit freely once the split is done)
import { ZOOM } from './engine/core.js';
import { init } from './runtime/init.js';
// ── end of imports

// Built-in stream kinds. What a kind *looks* like is CSS on its selector; what
// it *does* is `mount(box, ctx)`, called once per box after its first nested
// layout. `ctx.state` is an object that outlives the box (a font re-render
// rebuilds the DOM), so a kind keeps anything it must remember there and
// restores it in mount. A page adds or overrides kinds before or after this
// script loads:
//
//     window.reflowtex = { streamKinds: { callout: { mount(box, ctx) { … } } } };
//
// A kind with no entry here is still rendered – as a plain box the page can
// style – it just has no behaviour.
// A small Lean 4 highlighter: comments, strings, numbers and keywords, as
// spans the page colours (--code-* custom properties if it has them).
export const LEAN_KEYWORDS = new Set(('theorem lemma def example instance structure class inductive where by fun '
    + 'have show from at with match calc exact exacts intro intros induction cases rcases obtain simp simp_all '
    + 'rw rwa rfl apply refine use constructor omega norm_num linarith nlinarith ring ring_nf field_simp decide '
    + 'aesop sorry let in if then else do return namespace open section end variable noncomputable private '
    + 'protected theorem abbrev deriving universe mutual termination_by decreasing_by nat_cases positivity gcongr '
    + 'unfold subst specialize contradiction exfalso trivial assumption tauto push_neg by_contra by_cases').split(' '));
export function highlightLean(code) {
    const esc = t => t.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    const re = /(\/-[\s\S]*?-\/)|(--[^\n]*)|("(?:[^"\\]|\\.)*")|(\b\d+(?:\.\d+)?\b)|([A-Za-z_][A-Za-z0-9_'.!?]*)/g;
    let out = '', last = 0, m;
    while ((m = re.exec(code))) {
        out += esc(code.slice(last, m.index));
        const [t] = m;
        if (m[1] || m[2]) out += `<span class="lean-com">${esc(t)}</span>`;
        else if (m[3]) out += `<span class="lean-str">${esc(t)}</span>`;
        else if (m[4]) out += `<span class="lean-num">${esc(t)}</span>`;
        else if (LEAN_KEYWORDS.has(t)) out += `<span class="lean-kw">${esc(t)}</span>`;
        else out += esc(t);
        last = re.lastIndex;
    }
    return out + esc(code.slice(last));
}

// The Proof and Lean switches of leanproof and leantheorem: independent, so
// either part, both (side by side from 44rem, else stacked) or neither shows.
// `box` carries the state classes, `host` gets the switch row (appended: see
// leanproof). Every change lays the block out again: the TeX part's width
// changes.
export function leanSwitches(box, ctx, host, fallback) {
    if (!ctx.state.show) {
        const init = (ctx.attrs.show || fallback).toLowerCase();
        ctx.state.show = { proof: init === 'proof' || init === 'both', lean: init === 'lean' || init === 'both' };
    }
    const row = document.createElement('div');
    row.className = 'latex-lean-switches';
    row.setAttribute('role', 'group');
    row.setAttribute('aria-label', 'Show the proof, its Lean code, or both');
    const buttons = {};
    const apply = () => {
        for (const k of ['proof', 'lean']) {
            box.classList.toggle('latex-show-' + k, ctx.state.show[k]);
            buttons[k].setAttribute('aria-pressed', String(ctx.state.show[k]));
        }
    };
    // The space TeX put after the widget is the space after the *proof* (with
    // a display's below-skip, if the proof ends in one). While the proof is
    // hidden the widget should be followed by the space that followed the
    // statement (leantheorem) or preceded the widget (leanproof), so its
    // bottom margin takes back the difference. The spacers are the layout's
    // own elements, read after each layout.
    const heightOf = el => (el && parseFloat(el.style.height)) || 0;
    const adjust = () => {
        box.style.marginBottom = '';
        if (ctx.state.show.proof) return;
        let after = box.nextElementSibling;
        while (after && after.classList.contains('latex-anchor')) after = after.nextElementSibling;
        const stmt = box.firstElementChild && box.firstElementChild.querySelector(':scope > .latex-stream[data-kind="leanstatement"]');
        const want = heightOf(stmt ? stmt.nextElementSibling : box.previousElementSibling);
        const d = want - heightOf(after);
        if (d < 0) box.style.marginBottom = `${d}px`;
    };
    for (const [k, label] of [['proof', 'Proof'], ['lean', 'Lean']]) {
        const b = document.createElement('button');
        b.type = 'button';
        b.textContent = label;
        b.addEventListener('click', () => {
            ctx.state.show[k] = !ctx.state.show[k];
            apply(); ctx.relayout(); ctx.paint(); adjust();
        });
        buttons[k] = b;
        row.appendChild(b);
    }
    host.appendChild(row);
    apply();
    requestAnimationFrame(adjust);                 // once the parent has placed its spacers
    window.addEventListener('resize', () => requestAnimationFrame(adjust), { passive: true });
}

export const STREAM_KINDS = {
    // reflowtex.sty's leancode: Lean source carried as text (Stream.text),
    // shown as highlighted, selectable code under a small header naming the
    // declaration (linked when the author gave url=).
    leancode: {
        mount(box, ctx) {
            if (ctx.attrs.decl) {
                const head = document.createElement('div');
                head.className = 'latex-lean-head';
                const d = document.createElement(ctx.attrs.url ? 'a' : 'span');
                d.textContent = ctx.attrs.decl;
                if (ctx.attrs.url) { d.href = ctx.attrs.url; d.target = '_blank'; d.rel = 'noopener'; }
                head.appendChild(d);
                box.appendChild(head);
            }
            const pre = document.createElement('pre');
            const code = document.createElement('code');
            code.innerHTML = highlightLean(ctx.stream.text || '');
            pre.appendChild(code);
            box.appendChild(pre);
        },
    },
    // reflowtex.sty's leanproof: one frame (the proof's look) holding a TeX
    // part (leantex) and its Lean code (leancode), with Proof and Lean
    // switches on top (placed first by CSS order: the layout code takes a
    // stream box's first child for its content).
    leanproof: {
        mount(box, ctx) { leanSwitches(box, ctx, box, 'proof'); },
    },
    // reflowtex.sty's leantheorem: the statement (leanstatement), its proof
    // (leantex) and the code (leancode). The switches hang under the
    // theorem's frame, from its left edge, like tabs (under the statement
    // when theorems are not boxed); the proof and code open beneath them,
    // initially neither.
    leantheorem: {
        mount(box, ctx) {
            const root = box.firstElementChild;
            const stmt = root && root.querySelector(':scope > .latex-stream[data-kind="leanstatement"]');
            const thm = stmt && stmt.querySelector('.latex-stream[data-kind="theorem"]');
            leanSwitches(box, ctx, stmt || box, 'none');
            if (thm) {
                // In the theorem box's own colours, so a box with accent= or
                // background= of its own is matched too (the variables are
                // reset per stream, hence copied rather than inherited).
                const row = (stmt || box).lastElementChild;
                row.classList.add('latex-lean-hang');
                for (const v of ['--latex-box-accent', '--latex-box-background']) {
                    const val = thm.style.getPropertyValue(v);
                    if (val) row.style.setProperty(v, val);
                }
            }
        },
    },
    // reflowtex.sty's webhint: blurred (CSS) until the reader clicks it or
    // presses Enter/Space on it, and blurred again by the next click. Clicks
    // on a link inside, or that end a text selection, leave it as it is. The
    // state survives re-renders.
    hint: {
        mount(box, ctx) {
            const show = on => {
                ctx.state.revealed = on;
                box.classList.toggle('latex-revealed', on);
                box.setAttribute('aria-pressed', String(on));
                box.setAttribute('aria-label', on ? 'Hint, shown: press to hide' : 'Hint, hidden: press to reveal');
            };
            box.setAttribute('role', 'button');
            box.setAttribute('tabindex', '0');
            show(!!ctx.state.revealed);
            box.addEventListener('click', e => {
                if (e.target.closest && e.target.closest('[data-link]')) return;
                if (ctx.state.revealed && String(getSelection()).trim()) return;
                show(!ctx.state.revealed);
            });
            box.addEventListener('keydown', e => {
                if (e.target !== box || (e.key !== 'Enter' && e.key !== ' ')) return;
                e.preventDefault(); show(!ctx.state.revealed);
            });
        },
    },
    // One of several panes (reflowtex.sty's accordion): the child streams of
    // kind "pane", of which exactly one shows. The reader switches with
    // action links inside the panes – "pane:next", "pane:prev", "pane:first",
    // "pane:last", "pane:NAME" or "pane:NUMBER" (from 1). The hiding itself
    // is CSS (installStreamStyles); this keeps the current pane on the box as
    // data-pane and the pane's class latex-pane-active.
    accordion: {
        alternatives: true,          // panes replace one another (see layoutStreamSegment)
        mount(box, ctx) {
            const root = box.firstElementChild;
            const panes = root ? [...root.children].filter(e => e.matches('.latex-stream[data-kind="pane"]')) : [];
            if (!panes.length) return;
            const find = t => {
                if (t === 'first') return 0;
                if (t === 'last')  return panes.length - 1;
                if (t === 'next')  return Math.min(ctx.state.pane + 1, panes.length - 1);
                if (t === 'prev')  return Math.max(ctx.state.pane - 1, 0);
                const byName = panes.findIndex(p => p.dataset.name && p.dataset.name === t);
                if (byName >= 0) return byName;
                const n = parseInt(t, 10);
                return n >= 1 && n <= panes.length ? n - 1 : -1;
            };
            const show = i => {
                ctx.state.pane = i;
                panes.forEach((p, k) => p.classList.toggle('latex-pane-active', k === i));
                box.dataset.pane = panes[i].dataset.name || String(i + 1);
            };
            // What printing the page shows: the pane a PDF would (print=).
            const printAt = find(ctx.attrs.print || 'last');
            panes.forEach((p, k) => p.classList.toggle('latex-pane-print', k === printAt));
            if (ctx.state.pane === undefined) {
                const first = find(ctx.attrs.initial || '1');
                ctx.state.pane = first >= 0 ? first : 0;
            }
            show(ctx.state.pane);
            box.addEventListener('reflowtex:action', e => {
                const m = /^pane:(.+)$/.exec(e.detail.action);
                if (!m) return;                       // not ours: let it bubble on
                const i = find(m[1]);
                if (i < 0) return;
                e.stopPropagation();                  // an outer accordion must not act too
                // The tab stop is one glyph of the control's group, not
                // necessarily the one that sent the event: compare groups.
                const active = document.activeElement;
                // Only for keyboard focus: a mouse click focuses the glyph
                // too, and moving that would draw a focus ring nobody asked for.
                const hadFocus = !!(active && active.dataset && e.detail.source
                                    && active.dataset.link === e.detail.source.dataset.link
                                    && active.matches(':focus-visible'));
                show(i);
                ctx.paint();
                // Collapsing a long pane from its end would leave the reader
                // below the accordion; bring its top back into view.
                if (box.getBoundingClientRect().top < 0) box.scrollIntoView({ block: 'start' });
                // Keyboard: the control just pressed is now hidden, so move
                // focus to the first control of the pane now showing.
                if (hadFocus) {
                    const next = panes[i].querySelector('.latex-action[tabindex]');
                    if (next) next.focus({ preventScroll: true });
                }
            });
        },
    },
};

// The structural CSS the built-in kinds need (hidden or shown, a pointer, a
// disclosure marker). Appearance beyond that is the page's, on the same
// selectors; the marker glyphs are overridable through custom properties.
export function installStreamStyles() {
    const st = document.createElement('style');
    // Built-in looks for reflowtex.sty's note, hint and boxed theorems. Each
    // colour is a custom property a page (or a theme class) can set; the
    // tints are mixed with transparent, so they sit on any page background.
    // Boxes keep their padding small: a nested box (a claim in a proof) is
    // narrower by exactly that much per level.
    st.textContent = `
      /* Frames (note, hint, theorem, proof) grow outward: a top-level one
         reaches into the margin by its padding and border
         (--latex-outset-l/-r), so its text keeps the column's full measure
         and lines up with the text around it. Inside another frame a box
         stays within it, a little narrower per level. The outsets do not
         inherit, so a stream inside a frame (a pane, say) has none.
         A page's own framed kind can set the same two variables. */
      :where(.latex-stream) { --latex-outset-l: initial; --latex-outset-r: initial; }
      .latex-stream {
        margin-left: calc(-1 * var(--latex-outset-l, 0px));
        margin-right: calc(-1 * var(--latex-outset-r, 0px)); }
      :is(.latex-stream[data-kind="theorem"], .latex-stream[data-kind="proof"],
          .latex-stream[data-kind="note"], .latex-stream[data-kind="hint"],
          .latex-stream[data-kind="leancode"]) .latex-stream {
        margin-left: 0; margin-right: 0; }
      .latex-stream[data-kind="note"] {
        --latex-outset-l: calc(1rem + 3px); --latex-outset-r: 1rem;
        padding: .6rem 1rem;
        border-left: 3px solid var(--latex-note-accent, #2f6fb3);
        background: color-mix(in srgb, var(--latex-note-accent, #2f6fb3) 8%, transparent); }
      /* The hint's content is blurred, not the box, so a label can sit
         sharp over it while it is hidden (--latex-hint-label, a string). */
      .latex-stream[data-kind="hint"] { position: relative; cursor: pointer; }
      .latex-stream[data-kind="hint"] > * { filter: blur(5px); transition: filter .2s; }
      .latex-stream[data-kind="hint"].latex-revealed > * { filter: none; }
      .latex-stream[data-kind="hint"]:not(.latex-revealed)::after {
        content: var(--latex-hint-label, "Click to reveal");
        position: absolute; inset: 0; display: grid; place-items: center; pointer-events: none;
        font: 600 .8rem/1.2 ui-sans-serif, system-ui, sans-serif; letter-spacing: .01em; }
      .latex-stream[data-kind="hint"]:focus-visible { outline: 2px solid currentColor; outline-offset: 2px; }
      /* Vertical padding from the content's own edges: --latex-box-space
         (default one x-height of 10pt Latin Modern, 4.31pt) between the box
         and the top of a capital on the first line (cap height 6.83pt), and
         the same between the last baseline and the box. The viewer sets
         --latex-first-ascent / --latex-last-depth on every stream box. */
      :root { --latex-pt: ${ZOOM}px; }
      /* A box's colours are its own: do not inherit an enclosing box's
         (zero specificity, so a page's rule or the box's own inline value wins). */
      :where(.latex-stream) { --latex-box-accent: initial; --latex-box-background: initial; }
      .latex-stream[data-kind="theorem"], .latex-stream[data-kind="proof"] {
        --latex-outset-l: calc(.85rem + 3px); --latex-outset-r: .7rem;
        --latex-box-space: calc(4.31 * var(--latex-pt));
        --latex-cap-height: calc(6.83 * var(--latex-pt));
        padding: max(2px, calc(var(--latex-box-space) + var(--latex-cap-height) - var(--latex-first-ascent, 0px))) .7rem
                 max(2px, calc(var(--latex-box-space) - var(--latex-last-depth, 0px))) .85rem;
        /* --latex-box-accent / --latex-box-background: set per box (\DeclareWebBox
           accent=, background=) or by a page; else the kind's defaults – a
           page may give theorems a background of their own
           (--latex-theorem-background), else a tint of their accent. */
        border-left: 3px solid var(--latex-box-accent, var(--latex-theorem-accent, #2f6fb3));
        background: var(--latex-box-background, var(--latex-theorem-background,
          color-mix(in srgb, var(--latex-theorem-accent, #2f6fb3) 7%, transparent))); }
      /* A box with an accent of its own and no background: a tint of that accent. */
      .latex-stream[data-kind="theorem"][style*="--latex-box-accent"] {
        background: var(--latex-box-background,
          color-mix(in srgb, var(--latex-box-accent) 7%, transparent)); }
      .latex-stream[data-kind="proof"] {
        border-left-color: var(--latex-box-accent, var(--latex-proof-accent, #8a8f98));
        background: var(--latex-box-background,
          color-mix(in srgb, var(--latex-box-accent, var(--latex-proof-accent, #8a8f98)) 6%, transparent)); }
      /* Margin notes (placeMarginNotes): the layer is the block's, the notes
         beside it; where there is no room, a mark in the text opens one. */
      .latex-margin { position: absolute; left: 0; top: 0; width: 0; height: 0; }
      .latex-margin-note { position: absolute; }
      .latex-margin-note .latex-block { margin: 0; }
      .latex-margin-mark { position: absolute; transform: translate(-15%, -120%); margin: 0; padding: 0 .15em;
        border: 0; border-radius: 3px; background: none; color: inherit; opacity: .7; cursor: pointer;
        font: 600 .75em/1 ui-sans-serif, system-ui, sans-serif; }
      .latex-margin-mark:hover, .latex-margin-mark:focus-visible { opacity: 1; background: color-mix(in srgb, currentColor 10%, transparent); }
      .latex-margin-mark[hidden], .latex-margin-note[hidden] { display: none; }
      @media print {
        .latex-margin { display: none; }
        .latex-stream[data-kind="hint"] > * { filter: none; }
        .latex-stream[data-kind="hint"]::after { content: none; }
      }
      .latex-stream[data-kind="accordion"] > div > .latex-stream[data-kind="pane"]:not(.latex-pane-active) {
        display: none; }
      /* Lean beside a proof. leanproof: one frame (the proof's look), its
         switches on top, the proof box inside giving up its own frame.
         leantheorem: the switches in the theorem's frame, the proof (in its
         usual box) and the code beneath. The code has no background: just
         space from the proof. */
      .latex-stream[data-kind="leanproof"] { display: flex; flex-direction: column; container-type: inline-size; }
      .latex-stream[data-kind="leanproof"] > .latex-lean-switches { order: -1; margin-bottom: .6rem; }
      .latex-stream[data-kind="leanproof"]:not(.latex-show-proof):not(.latex-show-lean) > .latex-lean-switches { margin-bottom: 0; }
      .latex-stream[data-kind="leantheorem"] { container-type: inline-size; }
      .latex-stream[data-kind="leantheorem"] .latex-lean-switches { justify-content: flex-start; margin-top: .4rem; }
      /* Hanging from a boxed theorem: flush with the frame's bottom, starting
         where its text ("Theorem") starts, in the box's own colours (set by
         the script from the box). Only the label is dimmed, never the fill. */
      .latex-stream[data-kind="leantheorem"] .latex-lean-switches.latex-lean-hang {
        margin: 0; gap: 2px;
        --lt-accent: var(--latex-box-accent, var(--latex-theorem-accent, #2f6fb3));
        --lt-bg: var(--latex-box-background, var(--latex-theorem-background,
          color-mix(in srgb, var(--lt-accent) 7%, transparent))); }
      .latex-stream[data-kind="leantheorem"] .latex-lean-switches.latex-lean-hang[style*="--latex-box-accent"] {
        --lt-bg: var(--latex-box-background, color-mix(in srgb, var(--lt-accent) 7%, transparent)); }
      /* Borderless in every state, so nothing but colour changes on hover. */
      .latex-lean-switches.latex-lean-hang button,
      .latex-lean-switches.latex-lean-hang button:hover {
        border: 0; opacity: 1; color: color-mix(in srgb, currentColor 72%, transparent);
        background: linear-gradient(color-mix(in srgb, var(--lt-accent) 7%, transparent) 0 0), var(--lt-bg); }
      .latex-lean-switches.latex-lean-hang button:hover { color: inherit; }
      .latex-lean-switches.latex-lean-hang button[aria-pressed="true"] {
        color: inherit; background: linear-gradient(color-mix(in srgb, var(--lt-accent) 20%, transparent) 0 0), var(--lt-bg); }
      .latex-lean-switches { display: flex; gap: .3rem; }
      .latex-lean-switches button {
        font: 500 .72rem/1 ui-sans-serif, system-ui, sans-serif; letter-spacing: .02em; color: inherit;
        padding: .34rem .7rem; border-radius: 0; cursor: pointer; opacity: .75;
        background: none; border: 1px solid color-mix(in srgb, currentColor 24%, transparent); }
      .latex-lean-switches button:hover { opacity: 1; }
      .latex-lean-switches button[aria-pressed="true"] {
        opacity: 1; border-color: transparent; background: color-mix(in srgb, currentColor 13%, transparent); }
      .latex-lean-switches button:focus-visible { outline: 2px solid currentColor; outline-offset: 2px; }
      :is(.latex-stream[data-kind="leanproof"], .latex-stream[data-kind="leantheorem"]) > div:first-child {
        display: grid; grid-template-columns: minmax(0, 1fr); gap: 1rem 2rem; align-items: start; }
      :is(.latex-stream[data-kind="leanproof"], .latex-stream[data-kind="leantheorem"]) > div:first-child > :not(.latex-stream) { display: none; }
      .latex-stream[data-kind="leantheorem"] > div:first-child > .latex-stream[data-kind="leanstatement"] { grid-column: 1 / -1; }
      :is(.latex-stream[data-kind="leanproof"], .latex-stream[data-kind="leantheorem"]):not(.latex-show-proof) > div:first-child > .latex-stream[data-kind="leantex"],
      :is(.latex-stream[data-kind="leanproof"], .latex-stream[data-kind="leantheorem"]):not(.latex-show-lean) > div:first-child > .latex-stream[data-kind="leancode"] { display: none; }
      /* Side by side, the proof and the code are one height: the row
         stretches both, and the proof's own box (inside leantex) with it. */
      @container (min-width: 44rem) {
        :is(.latex-stream[data-kind="leanproof"], .latex-stream[data-kind="leantheorem"]).latex-show-proof.latex-show-lean > div:first-child {
          grid-template-columns: minmax(0, 1fr) minmax(0, 1fr); column-gap: 3.2rem; align-items: stretch; }
        :is(.latex-stream[data-kind="leanproof"], .latex-stream[data-kind="leantheorem"]).latex-show-proof.latex-show-lean .latex-stream[data-kind="leantex"] {
          display: flex; flex-direction: column; }
        :is(.latex-stream[data-kind="leanproof"], .latex-stream[data-kind="leantheorem"]).latex-show-proof.latex-show-lean .latex-stream[data-kind="leantex"] > div {
          flex: 1 0 auto; display: flex; flex-direction: column; }
        :is(.latex-stream[data-kind="leanproof"], .latex-stream[data-kind="leantheorem"]).latex-show-proof.latex-show-lean .latex-stream[data-kind="leantex"] > div > .latex-stream {
          flex: 1 0 auto; } }
      /* The code's frame: the proof's, in the Lean colour (--latex-lean-accent). */
      .latex-stream[data-kind="leancode"] {
        --latex-outset-l: calc(.85rem + 3px); --latex-outset-r: .7rem;
        padding: .6rem .7rem .7rem .85rem;
        border-left: 3px solid var(--latex-lean-accent, #2e8b7a);
        background: color-mix(in srgb, var(--latex-lean-accent, #2e8b7a) 7%, transparent); }
      .latex-lean-head { padding: 0 0 .35rem; opacity: .65; font: .72rem ui-monospace, "SF Mono", Menlo, monospace; }
      .latex-lean-head a { color: inherit; }
      .latex-stream[data-kind="leancode"] pre {
        margin: 0; padding: 0; border: 0; border-radius: 0; background: none; overflow-x: auto;
        font: .8rem/1.55 ui-monospace, "SF Mono", Menlo, "DejaVu Sans Mono", monospace; white-space: pre; }
      .latex-stream[data-kind="leancode"] pre code { font: inherit; }
      .lean-kw  { color: var(--code-kw, #1f5fa8); }
      .lean-com { color: var(--code-com, #7b7f86); font-style: italic; }
      .lean-str { color: var(--code-str, #2a7a3b); }
      .lean-num { color: var(--code-num, #a0522d); }
      @media print {
        .latex-lean-switches { display: none; }
        :is(.latex-stream[data-kind="leanproof"], .latex-stream[data-kind="leantheorem"]) > div:first-child > .latex-stream { display: block !important; }
      }
      @media print {
        .latex-stream[data-kind="accordion"] > div > .latex-stream[data-kind="pane"] { display: none; }
        .latex-stream[data-kind="accordion"] > div > .latex-stream[data-kind="pane"].latex-pane-print {
          display: block; }
        /* Controls do nothing on paper. More specific than the page's
           .latex-block svg .latex-link colour rule, which is also !important. */
        .latex-block svg .latex-link.latex-action { fill: transparent !important; }
      }
    `;
    document.head.appendChild(st);
}

document.addEventListener('DOMContentLoaded', init);
