// SPDX-License-Identifier: AGPL-3.0-or-later

// ── imports (generated by the split tooling; edit freely once the split is done)
import {
    RUNNING_RULE, SP_TO_PX, ZOOM, gD, gH, gW, glyphExpandScale, kernExpandScale, nodeWidthSp,
} from '../core.js';
import { texInterlineGlue } from './lines.js';
import { HL_ALIGNMENT, HL_EQUATION } from './text.js';
import { affineMul, affineOf, renderNodes } from '../paint.js';
// ── end of imports

// Where a box's ink ends, used only to size its horizontal scroll area.
// Placement comes exclusively from TeX's (possibly affine-evaluated) geometry;
// ink bounds must never feed back into centring or alignment.
export function inkExtentOf(fontInfo, box) {
    let min = Infinity, max = -Infinity;
    // Transform-aware: under a rotation it is the box's *height* that spans x,
    // so the horizontal extent has to be taken from the mapped corners rather
    // than from the node's width. Hence the full box rather than just (x, w).
    let M = null;
    const stack = [];
    const note = (x, w, yTop, yBot) => {
        if (!M) {
            if (x < min) min = x;
            if (x + w > max) max = x + w;
            return;
        }
        const [a,b,c,d,e,f] = M;
        for (const [px, py] of [[x,yTop],[x+w,yTop],[x,yBot],[x+w,yBot]]) {
            const tx = a*px + c*py + e;
            if (tx < min) min = tx;
            if (tx > max) max = tx;
        }
    };
    renderNodes(fontInfo, {
        beginLine() {},
        beginTransform(n, tf) { stack.push(M); M = affineMul(M, affineOf(tf)); },
        endTransform()        { M = stack.pop(); },
        glyph(n, x, y) { note(x, gW(n) * SP_TO_PX, y - gH(n) * SP_TO_PX, y + gD(n) * SP_TO_PX); },
        space()        {},                    // inter-word glue is not ink
        rule(n, x, y, w, h) { note(x, w, y, y + h); },
        picture(n, x, y) { note(x, n.width * SP_TO_PX, y - n.height * SP_TO_PX, y + n.depth * SP_TO_PX); },
    }, [box], 0, 0, 0, 0, 0);
    return isFinite(min) ? { min, max } : { min: 0, max: 0 };
}

// Evaluate sparse affine geometry recovered from several increasingly wide
// LuaTeX compilations. This is deliberately oblivious to display type:
// equation, \[...\], align, gather, multline, and package-defined displays all
// arrive as the same recursively matched finished node tree.
export const AFFINE_NODE_FIELDS = [
    'width', 'height', 'depth', 'stretch', 'shrink', 'kern', 'shift',
    'glue_set', 'surround', 'm_a', 'm_b', 'm_c', 'm_d',
];
export const AFFINE_CHILD_LISTS = ['children', 'pre', 'post', 'replace'];
export function affineDisplayNode(n, deltaSp) {
    let out = n, changed = false;
    // A copy remembers the node it was evaluated from (for api.inspect: the
    // compiled values, and the gap classification, which is keyed by it).
    const edit = () => { if (!changed) { out = { ...n }; Object.defineProperty(out, 'affineSource', { value: n.affineSource || n }); changed = true; } };
    for (const field of AFFINE_NODE_FIELDS) {
        const rate = n[`${field}_rate`];
        if (rate !== undefined) {
            edit();
            out[field] = (n[field] || 0) + rate * deltaSp;
        }
    }
    for (const key of AFFINE_CHILD_LISTS) {
        if (!n[key]?.length) continue;
        const children = n[key].map(child => affineDisplayNode(child, deltaSp));
        if (children.some((child, i) => child !== n[key][i])) {
            edit(); out[key] = children;
        }
    }
    if (n.leader) {
        const leader = affineDisplayNode(n.leader, deltaSp);
        if (leader !== n.leader) { edit(); out.leader = leader; }
    }
    return out;
}

export function affineDisplayItem(item, deltaSp) {
    const out = { ...item, box: affineDisplayNode(item.box, deltaSp) };
    for (const field of ['display_width', 'display_indent', 'display_shift']) {
        const rate = item[`${field}_rate`];
        if (rate !== undefined) out[field] = (item[field] || 0) + rate * deltaSp;
    }
    return out;
}

// Which of a display's affine gaps must keep a minimum, and which may close.
//
// The finished tree holds two kinds of horizontal space that shrink with the
// measure, and they are not the same thing. Space with ink on *both* sides is
// internal: it separates two pieces of the formula – the gap between an align's
// columns, or between the last column and its equation number – and closing it
// would run them together, so it stops at the configurable minimum. Space with
// ink on only one side is outer: the centring glue of an align row, the margin
// left of a short display. It belongs to the column, not to the formula, and
// may close completely. Squeezing it to nothing is exactly right – a display
// should be as narrow as its own ink before it starts to scroll.
//
// The test is geometric, not structural, so it holds for whatever tree TeX
// produced rather than for the environments we happened to think of: place the
// display with the renderer's own traversal, note where ink lands and where each
// floor-bearing gap lands, then ask whether ink falls on both sides of the gap.
// It reads only the compiled tree, so it is computed once per display and cached
// – the answer cannot change with the reader's width.
export const displayGapKinds = new WeakMap();   // display item → Map(node → {field: isInternal})

export function classifyDisplayGaps(fontInfo, item) {
    const cached = displayGapKinds.get(item);
    if (cached) return cached;
    const kinds = new Map();
    const gaps = [];
    let inkMin = Infinity, inkMax = -Infinity;
    const ink = (x, w) => {
        if (x < inkMin) inkMin = x;
        if (x + w > inkMax) inkMax = x + w;
    };
    renderNodes(fontInfo, {
        beginLine() {},
        // A gap's kind is about horizontal neighbours, and a transform's children
        // advance the pen untransformed (see renderNodes), so the plain pen
        // positions are the ones to compare. No matrix bookkeeping is needed.
        beginTransform() {}, endTransform() {},
        glyph(n, x)         { ink(x, gW(n) * SP_TO_PX); },
        space()             {},
        // Zero-width rules never reach this sink (renderNodes skips them), so a
        // strut – which is exactly that – correctly does not count as ink.
        rule(n, x, y, w)    { ink(x, w); },
        picture(n, x)       { ink(x, n.width * SP_TO_PX); },
        gap(n, field, x, w) { if (n[`${field}_floor`]) gaps.push({ n, field, x1: x, x2: x + w }); },
    }, [item.box], 0, 0, 0, 0, 0);

    // Ink that ends within a scaled point of a gap's edge abuts it. TeX's own
    // dimensions are integral scaled points, so anything finer is arithmetic
    // noise from accumulating two different sums to the same place – and an
    // equation number, whose box is pulled back onto its own right edge, lands
    // exactly there.
    const ABUT = SP_TO_PX;
    for (const g of gaps) {
        const internal = inkMin <= g.x1 + ABUT && inkMax >= g.x2 - ABUT;
        let fields = kinds.get(g.n);
        if (!fields) kinds.set(g.n, fields = {});
        fields[g.field] = internal;
    }
    displayGapKinds.set(item, kinds);
    return kinds;
}

// The narrowest measure this node's gaps may be evaluated at. Only nodes the
// classifier saw are considered, which is what keeps the floor to genuine gaps:
// a box's `width` also carries a rate, but a box is not space – it is however
// wide its contents came out – so it never fences off a measure of its own.
export function affineFloorWidthNode(n, sourceWidthSp, floorSp, kinds) {
    let minimum = 0;
    const fields = kinds.get(n);
    if (fields) {
        for (const field of ['width', 'kern', 'surround']) {
            const rate = n[`${field}_rate`];
            if (fields[field] === undefined || !(rate > 0)) continue;
            const floor = fields[field] ? floorSp : 0;
            minimum = Math.max(minimum,
                sourceWidthSp + (floor - (n[field] || 0)) / rate);
        }
    }
    for (const key of AFFINE_CHILD_LISTS) {
        for (const child of n[key] || []) {
            minimum = Math.max(minimum, affineFloorWidthNode(child, sourceWidthSp, floorSp, kinds));
        }
    }
    if (n.leader) minimum = Math.max(minimum, affineFloorWidthNode(n.leader, sourceWidthSp, floorSp, kinds));
    return minimum;
}

export function affineFloorWidthItem(fontInfo, item, sourceWidthSp, floorSp) {
    const kinds = classifyDisplayGaps(fontInfo, item);
    let minimum = affineFloorWidthNode(item.box, sourceWidthSp, floorSp, kinds);
    // display_shift places the whole display inside the column – centring for an
    // ordinary display, a fixed indent under fleqn. That is outer space by
    // construction: there is no ink on its far side to protect, so it closes to
    // zero and the display sits flush left before it starts to scroll.
    if (item.display_shift_floor && item.display_shift_rate > 0) {
        minimum = Math.max(minimum,
            sourceWidthSp - (item.display_shift || 0) / item.display_shift_rate);
    }
    // Never freeze *wider* than the measure the tree was compiled at. A gap that
    // was already below the minimum when TeX set it would otherwise ask for a
    // wider display than TeX itself produced; at the compiled width TeX's own
    // layout stands, whatever the minimum would prefer.
    return Math.min(minimum, sourceWidthSp);
}

// Lay a display segment out. The affine model updates the finished tree's
// geometry for the reader's width; placement is always the display_shift
// supplied by TeX – there is no ink-centering fallback. Every row of the segment
// is evaluated at the same measure, so an alignment's columns stay in step and
// the display freezes as one at the first gap to reach its floor.
// The makings of TeX's \predisplaysize for a display that would follow this
// segment's last line (TeX §1146): w, the line's shift plus the widths of
// everything up to and including its last piece of ink (a glyph, box, rule
// or leaders) – \maxdimen when glue set by the line's own ratio lies before
// that ink, so the end cannot be told, -\maxdimen for a line with no ink –
// and the quad of the line's last text font, the fallback for the 2em TeX
// adds (of the font current at the display, which the bundle records).
// Measured on the line as laid out here, so the choice TeX makes with it
// (displaySkipsFull) follows the reader's width.
export function preDisplaySizeSp(fontInfo, lines, lrp) {
    const k = lines.length - 1;
    if (k < 0) return null;
    const ln = lines[k], L = lrp[k];
    const MAX = 1073741823;
    let x = L.x0, w = null, unknown = false, mathOn = false, font = null, anyFont = null;
    const found = () => { w = unknown ? MAX : x; };
    const walk = (ns, glueSet) => {
        for (let i = 0; i < ns.length; i++) {
            const n = ns[i];
            switch (n.type) {
                case 'glyph':
                    x += gW(n) * glyphExpandScale(fontInfo, n, L.er) * SP_TO_PX; found();
                    if (!mathOn) font = n.font;
                    anyFont = n.font; break;
                case 'hlist': case 'vlist': case 'picture':
                    x += (n.width ?? 0) * SP_TO_PX; found(); break;
                case 'rule':
                    x += (n.width === RUNNING_RULE ? 0 : (n.width ?? 0)) * SP_TO_PX; found(); break;
                case 'glue': {
                    let g = n.width;
                    const so = n.stretch_order || 0, sho = n.shrink_order || 0;
                    if (glueSet) {
                        if (L.ratio > 0 && !so && n.stretch) { g += L.ratio * n.stretch; unknown = true; }
                        else if (L.ratio < 0 && !sho && n.shrink) { g += L.ratio * n.shrink; unknown = true; }
                        else if (L.fillRatio > 0 && so === L.fillOrder && n.stretch) unknown = true;
                    }
                    x += g * SP_TO_PX;
                    if (n.leader) found();
                    break;
                }
                case 'kern':
                    x += n.kern * ((n.subtype || 0) === 0 ? kernExpandScale(fontInfo, ns[i-1], ns[i+1], L.er) : 1) * SP_TO_PX;
                    break;
                case 'math': x += (n.surround || 0) * SP_TO_PX; mathOn = n.subtype === 0; break;
                case 'disc': walk(n.replace || [], false); break;
            }
        }
    };
    walk(ln.nodes, true);
    const fi = fontInfo[String(font ?? anyFont)];
    return { w: w === null ? -MAX : w === MAX ? MAX : Math.round(w / SP_TO_PX), quad: (fi && fi.quad) || 0 };
}

// Whether TeX would set this display with the full display skips, redone at
// the reader's width: the full pair when the display's left edge (its shift,
// plus the kern LuaTeX puts before a numbered formula) is at or left of
// \predisplaysize, taken from the segment before when a set line stood
// directly before the display, and as TeX captured it otherwise (a display
// that opened its paragraph: -\maxdimen, or the indent box's end). An
// alignment is always set with the full pair. null when the bundle carries
// no skip data – the captured spacing then stands.
export function displaySkipsFull(L, prev) {
    const rows = L.seg.rows;
    const item = rows && rows[0] && rows[0].item;
    if (!item || item.display_above === undefined || item.display_above === null) return null;
    // an alignment always gets the full pair (TeX §1206)
    if (item.box && item.box.subtype === HL_ALIGNMENT) return true;
    if (!item.box || item.box.subtype !== HL_EQUATION) return null;
    // At the width the document was set at, TeX's own choice stands: the
    // measure below follows TeX's to a fraction of a point, and a display
    // sitting within that of the threshold must not flip where the page is
    // meant to be the document.
    if (L.atSourceWidth && item.display_used_above != null) return item.display_used_above === item.display_above;
    const MAX = 1073741823;
    const captured = item.display_pre_size ?? 0;
    const pre = prev && prev.preDisplaySizeSp;
    let pds = captured;
    if (item.display_after_line && captured > -MAX && pre) {
        pds = Math.abs(pre.w) === MAX ? pre.w : pre.w + 2 * (item.display_quad || pre.quad);
    }
    const left = L.displayLeftSp ?? (item.display_shift || 0);
    return left <= pds;
}

// The change to the space above segment L (px) from redoing the skip choice:
// the display's own above skip, and the below skip of a display just before
// L. Records the display's choice on its layout for the segment after it.
export function displaySkipAdjust(L, prev) {
    let delta = 0;
    if (L.seg.kind === 'display') {
        const full = displaySkipsFull(L, prev);
        L.displayFull = full;
        if (full !== null) {
            const it = L.seg.rows[0].item;
            delta += ((full ? it.display_above : it.display_above_short) - (it.display_used_above || 0)) * SP_TO_PX;
            // and the interline glue TeX set above the display, redone for
            // the line now above it and the display's height at this width
            const meta = it.display_baselineskip != null
                ? { bskip: it.display_baselineskip * SP_TO_PX, lskip: (it.display_lineskip || 0) * SP_TO_PX,
                    lskiplimit: (it.display_lineskiplimit || 0) * SP_TO_PX }
                : (prev && prev.firstMeta);
            // A display that opened an empty paragraph (display_after_line
            // false) had that paragraph's empty line above it, of depth 0,
            // not the last line of the text before – when TeX set one. A
            // paragraph with nothing in it at all (\noindent, or the indent
            // box \@doendpe removes after a list or verbatim) gets no line
            // (§1145), which is what \predisplaysize = -\maxdimen records;
            // the glue above then comes from the text before, as usual.
            if (it.display_interline_above != null && prev && meta && L.firstAscent != null) {
                const blankLine = !it.display_after_line && it.display_pre_size !== -1073741823;
                const depthAbove = blankLine ? 0 : prev.lastDepth;
                delta += texInterlineGlue(depthAbove, L.firstAscent, meta) - it.display_interline_above * SP_TO_PX;
            }
        }
    }
    if (prev && prev.seg.kind === 'display' && prev.displayFull !== null && prev.displayFull !== undefined) {
        const it = prev.seg.rows[prev.seg.rows.length - 1].item;
        // LaTeX's \addvspace below the display asks for at least display_after_min
        const floor = it.display_after_min || 0;
        const below = Math.max(prev.displayFull ? it.display_below : it.display_below_short, floor);
        delta += (below - Math.max(it.display_used_below || 0, floor)) * SP_TO_PX;
        if (it.display_interline_below != null && L.firstMeta && L.firstAscent != null) {
            delta += texInterlineGlue(prev.lastDepth, L.firstAscent, L.firstMeta) - it.display_interline_below * SP_TO_PX;
        }
    }
    return delta;
}

// A numbered equation, as LuaTeX packs it: [kern d][formula][kern][number],
// z wide, placed by TeX §1199 from the formula's natural width w and the
// number's e: when formula and number do not both fit (w + e + 1em > z) the
// formula is shrunk to z − e − 1em if its glue can give that much (a
// formula that cannot gets its number on a line of its own, which is not
// modelled: the captured tree stands); then the formula is centred in the
// measure (d = (z − w)/2) unless the number would overlap it – d < 2e –
// when it is centred in what is left of the number (d = (z − w − e)/2, or
// 0 for a formula opening with glue). Each branch is affine in z with the
// same slope, so the affine model carries whichever branch the source
// measure was on across the switches; redoing the rule from the evaluated
// widths puts the formula where TeX puts it at every measure.
export function placeEquationNumber(item) {
    const b = item.box;
    if (!b || b.subtype !== HL_EQUATION || !b.children || b.children.length !== 4) return item;
    const [k0, f0, k1, num] = b.children;
    if (k0.type !== 'kern' || f0.type !== 'hlist' || k1.type !== 'kern' || num.type !== 'hlist' || num.subtype !== 7) return item;
    const z = item.display_width || 0, e = num.width || 0;
    if (!(z > 0) || !(e > 0)) return item;
    let f = f0, w = 0;
    const shrink = [0, 0, 0, 0];
    for (const n of f0.children || []) {
        w += nodeWidthSp(n);
        if (n.type === 'glue') shrink[n.shrink_order || 0] += n.shrink || 0;
    }
    const q = e + (item.display_quad || 0);       // TeX's math quad at text size
    if (w + q > z) {
        const order = shrink[3] ? 3 : shrink[2] ? 2 : shrink[1] ? 1 : 0;
        if (!(order > 0) && w - shrink[0] + q > z) return item;
        const target = z - q;
        f = { ...f0, width: target, glue_sign: 2, glue_order: order,
              glue_set: shrink[order] > 0 ? Math.min(order > 0 ? Infinity : 1, (w - target) / shrink[order]) : 0 };
        w = target;
    } else if (f0.glue_sign || Math.abs((f0.width || 0) - w) > 2) {
        f = { ...f0, width: w, glue_sign: 0, glue_order: 0, glue_set: 0 };
    }
    let d = Math.round((z - w) / 2);
    if (d < 2 * e) {
        d = Math.round((z - w - e) / 2);
        const first = f.children && f.children[0];
        if (first && first.type === 'glue') d = 0;
    }
    const children = [{ ...k0, kern: d }, f, { ...k1, kern: z - w - e - d }, num];
    return { ...item, box: { ...b, children } };
}

// The form of a display to draw at a measure, and the width its rates are
// anchored at. A display TeX set another way at the document's width (amsmath
// moved its tag, or had no room to centre the body) carries the wider regime
// as a second form, from the width where TeX switches (display_wide_from).
export function displayForm(item, targetSp, sourceWidthSp) {
    if (item.display_wide && item.display_wide_from && targetSp >= item.display_wide_from)
        return { item: item.display_wide, anchorSp: item.display_wide_width || sourceWidthSp };
    return { item, anchorSp: sourceWidthSp };
}

export function layoutDisplaySegment(fontInfo, seg, widthPt, displayModel) {
    const targetSp = Math.round(widthPt * 65536);
    const floorSp = Math.max(0, displayModel.minSpacePt) * 65536;
    const forms = seg.rows.map(r => displayForm(r.item, targetSp, displayModel.sourceWidthSp));
    const minWidthSp = Math.max(0, ...forms.map(f =>
        affineFloorWidthItem(fontInfo, f.item, f.anchorSp, floorSp)));
    const evaluatedSp = Math.max(targetSp, minWidthSp);
    const kinds = forms.map(f => classifyDisplayGaps(fontInfo, f.item));   // cached; for api.inspect
    seg = { ...seg, rows: seg.rows.map((r, i) => ({
        ...r, item: placeEquationNumber(affineDisplayItem(forms[i].item, evaluatedSp - forms[i].anchorSp)),
    })) };
    const columnPx = widthPt * ZOOM;
    const rows = seg.rows.map(r => ({
        ...r,
        x0:  (r.item.display_shift || 0) * SP_TO_PX,
        ink: inkExtentOf(fontInfo, r.item.box),
    }));
    // The surface has to cover the measure the display was evaluated at *and*
    // whatever ink hangs past it, so a frozen display can be panned to its last
    // glyph rather than having it clipped by the scroll box.
    let right = Math.max(columnPx, evaluatedSp * SP_TO_PX);
    for (const r of rows) right = Math.max(right, r.x0 + r.ink.max);
    return {
        lines: rows.map(r => ({ nodes: [r.item.box], ratio: 0, fitness: 2, leftProtrusion: 0 })),
        lrp:   rows.map(r => ({ ratio: 0, er: 0, x0: r.x0 })),
        gaps:  rows.map(r => r.gap || null),
        W:     Math.ceil(right),
        // the display's left edge at this width, for displaySkipsFull: the
        // shift plus the kern LuaTeX opens a numbered formula's box with
        displayLeftSp: (rows[0].item.display_shift || 0)
            + ((c => c && c.type === 'kern' ? (c.kern || 0) : 0)((rows[0].item.box.children || [])[0])),
        atSourceWidth: Math.abs(evaluatedSp - displayModel.sourceWidthSp) < 32768,
        // How the width model was applied, for api.inspect: the measure TeX
        // compiled at, the one asked for, the narrowest the gaps allow, and
        // the one evaluated at (the larger); each row's gap kinds, and each
        // row's item as evaluated (its display_width and indent at this width).
        affine: { sourceWidthSp: displayModel.sourceWidthSp, targetSp, minWidthSp, evaluatedSp, floorSp,
                  kinds, items: seg.rows.map(r => r.item) },
    };
}

export function updateDisplayOverflowCue(wrap) {
    const EPS = 1;
    wrap.classList.toggle('latex-overflow-left', wrap.scrollLeft > EPS);
    wrap.classList.toggle('latex-overflow-right',
        wrap.scrollLeft + wrap.clientWidth < wrap.scrollWidth - EPS);
}
