// SPDX-License-Identifier: AGPL-3.0-or-later

// ── imports (generated by the split tooling; edit freely once the split is done)
import { ZOOM, useGlyphMetrics } from '../core.js';
import {
    displaySkipAdjust, layoutDisplaySegment, preDisplaySizeSp, updateDisplayOverflowCue,
} from './display.js';
import { lineProfile, minRequiredAdvance, texInterlineAdvance, texInterlineGlue } from './lines.js';
import { layoutStreamSegment } from './stream.js';
import { keptHostBox } from '../../host/block-hosts.ts';
import { blockKeyOf } from '../../host/host.ts';
import { layoutTextSegment, segmentsOf } from './text.js';
import { svgEl } from '../paint.js';
import { held, linkTargets } from '../../host/links.js';
import { quickLayout } from '../../runtime/blocks.js';
import { observeSegments } from '../../runtime/visibility.js';
// ── end of imports

export let blockSeq = 0;              // per-block prefix, so ids from two blocks differ

// Text and stream segments join with TeX's interline glue (a stream's outer
// edges are its first and last lines); a display keeps its captured spacing.
export const isTextLike = kind => kind === 'text' || kind === 'stream';

export const onLayoutGrid = px => Math.round(px * 64) / 64;

// Heights and gaps go on that grid one after another down the document, so
// each is rounded together with what the ones above it lost: the remainder
// travels on the layout (L.gridCarry, what is left after its box) to the gap
// below. Rounded one by one, the ±1/128 px of each of some thousand gaps and
// boxes adds up – a random walk that had testmath's last lines 0.15 pt below
// TeX's; carried, no line is ever more than half a grid step from its place.
export function onGridCarried(px, carry) {
    const exact = px + carry;
    const r = onLayoutGrid(exact);
    return { r, carry: exact - r };
}

// Between two text segments TeX inserts interline (baselineskip) glue on
// top of any explicit \vspace, exactly as it does between the lines of a
// paragraph. Reproduce it so a heading sits the LaTeX distance above its
// body – and independently of the heading's descender depth, since the
// glue absorbs that. Displays keep their own captured spacing.
export function spaceAbove(L, prev) {
    let margin = L.gapBefore || 0;
    if (prev && L.seg.kind === 'text' && isTextLike(prev.seg.kind) && L.firstMeta
        && !(prev.frameBottom && L.gapBefore)) {           // see the stream branch of sizeSegment
        margin += texInterlineGlue(prev.lastDepth, L.firstAscent, L.firstMeta);
    }
    return margin + displaySkipAdjust(L, prev);
}

export function sizeSegment(s, L, prev, columnPx, p) {
    if (L.seg.kind === 'stream') {
        // The box already holds the nested layout, which sized itself. Only
        // the spacer above is this level's: the explicit gap plus, after
        // text, the interline glue the first nested line would have had.
        let margin = L.gapBefore || 0;
        // Across a frame edge the author's explicit space replaces TeX's
        // interline glue; where there is none, the glue stays, so a frame
        // never touches its neighbour.
        const framed = L.frameTop || prev?.frameBottom;
        if (prev && isTextLike(prev.seg.kind) && L.firstMeta && !(framed && L.gapBefore)) {
            margin += texInterlineGlue(prev.lastDepth, L.firstAscent, L.firstMeta);
        }
        margin += displaySkipAdjust(L, prev);
        const g = onGridCarried(margin, prev?.gridCarry || 0);
        setStyle(s.gap, 'height', `${g.r}px`);
        L.gridCarry = g.carry;          // the nested layout sized its own box
        return { mount: s.box.firstElementChild, overflows: false };
    }
    // Do not create a scrollbar for scaled-point rounding or a tiny italic
    // overhang. A bare SVG uses the column as its viewport and overflow:
    // visible lets that ink bleed naturally without scaling the display.
    const tolerancePx = Math.max(0, p.displayOverflowTolerancePx || 0);
    // A figure paragraph (isFigureParagraph) is exactly one unbreakable,
    // unshrinkable picture box, so it can overflow the column precisely the
    // way a display can – and gets the same scroll-box treatment.
    const scrollable = L.seg.kind === 'display' || L.seg.isFigure;
    const overflows = scrollable && L.W > columnPx + tolerancePx;
    // columnPx unless genuinely overflowing: an ordinary (non-scrollable)
    // text segment's own L.W is now real ink width (see layoutTextSegment),
    // not always exactly columnPx – a paragraph with, say, one line 0.3px
    // narrower than another must still get the *same* surface as every
    // other non-overflowing segment, or adjacent paragraphs visibly render
    // at slightly different widths.
    const surfaceW = overflows ? L.W : columnPx;
    // Heights go on the browser's layout grid (1/64 px in Blink and WebKit)
    // rounded to nearest: laid out as given, a fractional height is floored
    // to the grid, and over hundreds of stacked segments those floors add up
    // to a drift of a few points against TeX's own galley.
    // (the gap above, set further down, is rounded first: see onGridCarried)
    const margin = spaceAbove(L, prev);
    const gap = onGridCarried(margin, prev?.gridCarry || 0);
    const box = onGridCarried(L.H, gap.carry);
    const H = box.r;
    L.gridCarry = box.carry;
    // A segment held over by a quick reflow (see layoutDocument) keeps its
    // <svg> exactly as it is. Resizing it would make the browser lay out all
    // the text it holds again – once painted, a segment keeps its glyphs – and
    // once a reader has scrolled down a long page, that is most of the page,
    // on every frame of a drag. Its box clips it horizontally meanwhile, so the
    // old, wider surface cannot widen the page. The box is far from the screen,
    // so it is never the scroll anchor whose style must not change.
    if (!L.held) {
        s.svg.setAttribute('width', surfaceW);
        s.svg.setAttribute('height', H);
        s.svg.setAttribute('viewBox', `0 0 ${surfaceW} ${H}`);
    }
    setStyle(s.box, 'overflowX', L.held ? 'clip' : '');

    // Only a display that genuinely overflows gets a scroll box, because a
    // scroll box is also a *clipping* box: CSS forces overflow-y to 'auto'
    // once overflow-x is set, and there is no way to scroll one axis while
    // letting the other bleed. Ink that legitimately hangs outside its box
    // – accents, protrusion, delimiter overshoot – would be cut off. So a
    // display that fits is mounted bare and can bleed freely; only one that
    // must pan pays for it, and its wrapper gets a little self-cancelling
    // headroom for the bleed (see the margin block below).
    let mount = s.svg;
    if (overflows) {
        if (!s.wrap) {
            s.wrap = document.createElement('div');
            s.wrap.addEventListener('scroll', () => updateDisplayOverflowCue(s.wrap),
                                    { passive: true });
        }
        // It genuinely exceeds the column, so show a right cue immediately.
        // Later paint/scroll measurements refine both directional classes.
        s.wrap.classList.add('latex-display', 'latex-overflow-right');
        if (s.svg.parentNode !== s.wrap) s.wrap.replaceChildren(s.svg);
        mount = s.wrap;
    } else if (s.wrap && s.svg.parentNode === s.wrap) {
        s.wrap.classList.remove('latex-overflow-left', 'latex-overflow-right');
        s.svg.remove();          // no longer overflowing: shed the scroll box
    }
    // The space above the segment lives in its spacer, not in a margin on the
    // element itself (scroll anchoring again, see layoutDocument).
    setStyle(s.gap, 'height', `${gap.r}px`);
    setStyle(s.svg, 'marginTop', '');
    if (s.wrap) { setStyle(s.wrap, 'marginTop', ''); setStyle(s.wrap, 'marginBottom', ''); }
    if (mount === s.wrap) {
        // A scroll box clips (overflow-x forces overflow-y), so give the ink
        // a little vertical headroom – but reserve no space for it: negative
        // margins take the padding straight back (the space above the display
        // itself is in the spacer), so a wrapped display occupies exactly the
        // vertical band the bare SVG would, and a small
        // overshoot (accents, delimiter overshoot) overlaps the adjacent
        // glue the same way it does in print. Fixed rather than measured:
        // getBBox on SVG text reports the font's ascent/descent box, not
        // glyph ink, and the converted CM faces carry ascents far beyond any
        // outline – padding by that phantom measure visibly inflated the
        // space around every scrollable display.
        const BLEED_PAD = 6;
        setStyle(mount, 'paddingTop', `${BLEED_PAD}px`);
        setStyle(mount, 'paddingBottom', `${BLEED_PAD}px`);
        setStyle(mount, 'marginTop', `${-BLEED_PAD}px`);
        setStyle(mount, 'marginBottom', `${-BLEED_PAD}px`);
        setStyle(mount, 'overflowAnchor', 'none');
    } else {
        setStyle(mount, 'marginTop', '');
    }
    // Scroll destinations for the labels this segment owns. Their own
    // element rather than an id on the segment: a segment can own several
    // labels, and an element has only one id. Zero height, so it takes part
    // in nothing – scroll-margin-top is left to the page, which is the only
    // thing that knows whether it has a sticky header.
    return { mount, overflows };
}

/** A new block key, unique on the page (a layout's links and widgets are
 *  keyed by it, and a block's instance ids start with it). */
export const newBlockKey = () => `b${++blockSeq}`;

export function layoutDocument(fontInfo, doc, widthPt, p, cache) {
    // Point the glyph-metrics reader at this document's table, and stash it on the
    // cache so paintDocument (which is handed only the cache) reads the same one.
    // fontInfo is stashed too, so the IntersectionObserver – which is handed only a
    // segment reference – can repaint it (see observeSegments / segIO).
    useGlyphMetrics(doc.glyph_metrics);
    cache.metrics = doc.glyph_metrics;
    cache.sourceWidthSp = doc.source_width || 0;   // the \hsize the paragraphs' widths refer to
    cache.fontInfo = fontInfo;
    const columnPx = widthPt * ZOOM;
    const displayModel = {
        sourceWidthSp: doc.source_width || 0,
        minSpacePt: p.displayMinSpacePt,
    };
    // paintSegment is handed only the cache, so the reference tables and this
    // block's id prefix travel on it.
    cache.links   = doc.links   || [];
    cache.marks   = doc.marks   || [];              // \webid / \webclass (host/marks.ts)
    cache.slotNames = (doc.slots || []).map(x => x.name);   // Node.slot → its name, for data-slot
    cache.anchors = doc.anchors || [];
    cache.streams = doc.streams || [];
    // The hosts of block instances a page draws (host/block-hosts.ts), by
    // stream index; shared down into nested layouts, kept across rebuilds.
    cache.hosts = cache.hosts || new Map();
    cache.blockKey = cache.blockKey || newBlockKey();
    const minGapPx = p.minGapPt * ZOOM;
    const padPx    = p.padPt    * ZOOM;

    // Break candidates depend only on the node list, never on width or params,
    // so they are cached per paragraph across every reflow.
    cache.bcs = cache.bcs || new Map();
    const segs = segmentsOf(doc);

    if (!cache.dom) {
        const root = document.createElement('div');
        cache.dom = { root, segs: [], byNode: new Map(), live: new Set(),
                      anchors: new Map() };
    }
    const dom = cache.dom;
    dom.root.style.visibility = '';   // may have been hidden while paint was deferred

    const layoutOne = (seg, i) => {
        const geom = seg.kind === 'display'
            ? layoutDisplaySegment(fontInfo, seg, widthPt, displayModel)
            : layoutTextSegment(fontInfo, seg, widthPt, p, cache);

        // Profiles use actual render coords so collision detection matches real ink positions.
        const profiles = geom.lines.map((ln, j) =>
            lineProfile(fontInfo, ln.nodes, geom.lrp[j].x0, geom.lrp[j].ratio, geom.lrp[j].er)
        );
        const ascent     = (profiles[0] ?? []).reduce((m, it) => Math.max(m, it.h), 0);
        const baselineYs = [ascent];
        for (let j = 1; j < geom.lines.length; j++) {
            const gap = geom.gaps && geom.gaps[j];
            let advance;
            if (gap) {
                // TeX's own spacing between the rows of an alignment. Measured
                // baseline-to-baseline it must clear the previous depth and
                // this row's ascent.
                const prevDepth = profiles[j-1].reduce((m, it) => Math.max(m, it.d), 0);
                const rowAscent = profiles[j].reduce((m, it) => Math.max(m, it.h), 0);
                advance = prevDepth + gap + rowAscent;
            } else {
                const prevDepth = profiles[j-1].reduce((m, it) => Math.max(m, it.d), 0);
                const thisAsc   = profiles[j].reduce((m, it) => Math.max(m, it.h), 0);
                const lm = geom.meta && geom.meta[j];
                if (lm) {
                    // Land the line at exactly the LaTeX baseline-to-baseline.
                    advance = texInterlineAdvance(prevDepth, thisAsc, lm);
                } else {
                    // No captured metrics (older data): adaptive collision leading.
                    const needed = minRequiredAdvance(profiles[j-1], profiles[j]);
                    advance = needed > minGapPx ? needed + padPx : minGapPx;
                }
            }
            baselineYs.push(baselineYs[j-1] + advance);
        }
        const firstAscent = ascent;
        const lastDepth = (profiles[profiles.length-1] ?? []).reduce((m, it) => Math.max(m, it.d), 0);
        const H = baselineYs[baselineYs.length-1] + lastDepth;

        // A segment's box spans its first ascent to its last depth, so stacking
        // segments with margin-top = gap reproduces exactly the baseline-to-
        // baseline advance TeX asked for. firstMeta carries this segment's leading
        // parameters so a text→text join can add TeX's interline glue (see below).
        return { ...geom, seg, profiles, baselineYs, H, firstAscent, lastDepth,
                 firstMeta: (geom.meta && geom.meta[0]) || null, gapBefore: seg.gapBefore || 0 };
    };

    // ── Layout cache ──────────────────────────────────────────────────────────
    // A reflow used to re-break every paragraph, though only the segments near
    // the viewport are ever painted at the new width; the rest were laid out for
    // one number, their height, which sets the block's height and the page's
    // scroll geometry. Now each segment remembers, per width, the geometry its
    // neighbours need (height, first ascent, last depth, surface width), and the
    // full layout for the last few widths. A segment's height is taken to be
    // monotone in the width – the same height at two widths means the same
    // height everywhere between them – so once two observed widths agree, every
    // width in that interval is answered from the cache. A segment that is not
    // near the viewport and whose geometry is cached is then not laid out at all:
    // its layout is *deferred*, and materializeSegment runs it the moment
    // something needs its lines (a paint, once it scrolls into view). Should the
    // real height differ from the cached one, the page adjusts then and the
    // observation is corrected, so the assumption only ever costs a shift, never
    // a wrong render. Segments near the viewport are always laid out for real.
    // The per-segment elements persist across renders; only contents reconcile.
    while (dom.segs.length < segs.length) {
        const seg = segs[dom.segs.length];
        if (seg.kind === 'stream' && keptHostBox(cache, seg.index)) {
            // A host the page draws in (see block-hosts.ts): the same box
            // again, with what the page put in it, when the DOM is rebuilt.
            const gap = document.createElement('div');
            gap.style.cssText = 'height:0px;overflow-anchor:none';
            dom.segs.push({ svg: null, box: keptHostBox(cache, seg.index), gap, wrap: null, pairs: [], sub: null });
            continue;
        }
        if (seg.kind === 'stream') {
            // The box is what the page styles and scripts by kind, and holds
            // the nested layout (layoutStreamSegment) rather than an <svg>.
            // Class and kind are set once, here: the box's style must never
            // change afterwards (scroll anchoring, below).
            const box = document.createElement('div');
            box.className = 'latex-stream';
            box.dataset.kind = seg.stream.kind || '';
            // Its instance (host API): whose text a control pressed in it is.
            const bk = blockKeyOf(cache.blockEl);
            if (bk) box.dataset.instance = `${bk}/s${seg.index}`;
            // The author's parameters (\begin{webstream}[key=value]),
            // for CSS and the kind's behaviour alike.
            // Two keys are special: class adds CSS classes, and a key
            // starting with -- sets that CSS custom property on the box
            // (reflowtex.sty's \DeclareWebBox accent= and background=).
            for (const a of seg.stream.attrs || []) {
                if (!a.key || !/^[a-z0-9-]+$/.test(a.key)) continue;
                if (a.key === 'class') box.classList.add(...(a.value || '').split(/\s+/).filter(Boolean));
                else if (a.key.startsWith('--')) box.style.setProperty(a.key, a.value || '');
                else box.setAttribute('data-' + a.key, a.value || '');
            }
            const gap = document.createElement('div');
            gap.style.cssText = 'height:0px;overflow-anchor:none';
            dom.segs.push({ svg: null, box, gap, wrap: null, pairs: [], sub: null });
            continue;
        }
        // xmlns:xlink is declared so a picture's `<use xlink:href=…>` (dvisvgm
        // emits the xlink form) resolves once its markup is injected via innerHTML.
        const svg = svgEl('svg', { xmlns:'http://www.w3.org/2000/svg', 'xmlns:xlink':'http://www.w3.org/1999/xlink' });
        // Block CSS cascade from prose containers; SVG text uses explicit per-glyph font families.
        // overflow-anchor:none keeps the browser's scroll anchor off the <svg>: its
        // height attribute changes on every reflow, and a change to the anchor
        // node's own computed height is a suppression trigger (see the mounting
        // notes below). The anchor lands on `box` instead, whose style never changes.
        // max-width:none overrides a page's `svg { max-width: 100% }`: the
        // viewer sizes every segment itself, and under that cap a column that
        // narrows shrinks the whole picture (it has a viewBox) for the frame or
        // two before the reflow lands. Uncapped, the lines keep their size and
        // hang past the column until they are re-broken.
        // direction:ltr: every glyph is placed where TeX put it, so the page's
        // direction (an rtl page, whose frames mirror) must not make the
        // browser reorder or re-anchor the text runs.
        svg.style.cssText = 'display:block;overflow:visible;max-width:none;font-weight:normal;font-style:normal;overflow-anchor:none;direction:ltr;unicode-bidi:isolate';
        const box = document.createElement('div');
        box.appendChild(svg);
        const gap = document.createElement('div');
        gap.style.cssText = 'height:0px;overflow-anchor:none';
        dom.segs.push({ svg, box, gap, wrap: null, pairs: [] });
    }

    const paramsKey = JSON.stringify(p);
    cache.layoutCtx = { layoutOne, segs, widthPt, p, columnPx, paramsKey };
    const stats = cache.layoutStats = { computed: 0, reused: 0, deferred: 0, materialized: 0 };
    const prevLaid = cache.layout && cache.layout.laid.length === segs.length ? cache.layout.laid : null;
    const laid = segs.map((seg, i) => {
        const s = dom.segs[i];
        if (seg.kind === 'stream') {
            stats.computed++;
            return layoutStreamSegment(fontInfo, doc, s, seg, widthPt, p, cache);
        }
        const hc = segLayoutCache(s, paramsKey);
        const exact = hc.exact.get(widthPt);
        if (exact) { stats.reused++; return { ...exact, seg }; }
        if (!s.intersecting) {
            // While the width is still changing (see reflowBlock), a segment
            // with nothing cached for this width keeps the geometry it had:
            // its box does not move, and settleBlock lays it out once the
            // resize stops.
            const cached = cachedGeometry(hc, widthPt);
            const g = cached || (quickLayout && prevLaid && prevLaid[i]);
            if (g) {
                stats.deferred++;
                return { seg, deferred: true, held: !cached, lines: [], H: g.H, W: g.W, firstAscent: g.firstAscent,
                         lastDepth: g.lastDepth, firstMeta: g.firstMeta, gapBefore: seg.gapBefore || 0,
                         preDisplaySizeSp: g.preDisplaySizeSp, displayLeftSp: g.displayLeftSp, atSourceWidth: g.atSourceWidth };
            }
        }
        const L = layoutOne(seg, i);
        rememberLayout(hc, widthPt, L);
        stats.computed++;
        return L;
    });

    // ── Mounting, and the browser's scroll anchoring ──────────────────────
    // When a window resize reflows a page, the browser keeps the content at the
    // top of the viewport in place (CSS scroll anchoring): it picks the deepest
    // element partially visible there and, after layout, scrolls so that
    // element's top edge has not moved. It gives up the moment the anchor
    // element is removed from the DOM, or its own computed margin, padding or
    // (in practice) size changes. A reflow here changes every segment's height
    // and spacing, so the DOM is arranged to keep the anchor on something whose
    // style is constant: each segment is a spacer (its height carries the
    // spacing, replacing a margin) followed by a plain `box` holding the <svg>
    // (or the scroll wrapper of an overflowing display). Spacer, <svg> and
    // wrapper are excluded from anchor selection with overflow-anchor:none, so
    // the box – content-sized, never restyled – is what the browser holds on
    // to; the height changes it must compensate for are then all on siblings
    // above it, which is exactly the case anchoring handles. The child list is
    // reconciled in place rather than rebuilt, so nothing is detached.
    const want = [];
    laid.forEach((L, i) => {
        const s = dom.segs[i];
        const { mount, overflows } = sizeSegment(s, L, laid[i-1], columnPx, p);
        s.mount = mount;
        for (const id of L.seg.anchors || []) {
            const label = cache.anchors[id - 1];
            if (!label) continue;
            let a = dom.anchors.get(label);
            if (!a) {
                a = document.createElement('div');
                a.className = 'latex-anchor';
                a.id = label;
                dom.anchors.set(label, a);
                linkTargets.set(label, a);
            }
            want.push(a);
        }
        // (A host the page draws in may be empty: no mount.)
        if (mount && mount.parentNode !== s.box) s.box.replaceChildren(mount);
        want.push(s.gap, s.box);
        if (overflows) {
            // Initial layout may still be detached from the document. Check in
            // the next frame, after the wrapper has a meaningful clientWidth.
            requestAnimationFrame(() => updateDisplayOverflowCue(s.wrap));
        }
    });

    if (segs.trailingGap) {
        if (!dom.trail) {
            dom.trail = document.createElement('div');
            dom.trail.style.cssText = 'overflow-anchor:none';
        }
        setStyle(dom.trail, 'height', `${segs.trailingGap}px`);
        want.push(dom.trail);
    }
    syncChildren(dom.root, want);
    cache.layout = { laid };
    observeSegments(cache);
    return dom.root;
}

// Make parent's children exactly `want`, in order, touching only what differs:
// an element already in place is left alone (see the scroll-anchoring notes in
// layoutDocument), and one that moved is re-inserted before its new successor.
export function syncChildren(parent, want) {
    let k = 0;
    for (const el of want) {
        const cur = parent.childNodes[k];
        if (cur !== el) parent.insertBefore(el, cur || null);
        k++;
    }
    while (parent.childNodes.length > k) parent.lastChild.remove();
}

// Write a style property only when it changes: a rewrite with the same value
// is harmless to layout but an actual change on the anchor element (or one of
// its ancestors) is what cancels scroll anchoring.
export function setStyle(el, prop, v) { if (el.style[prop] !== v) el.style[prop] = v; }

// Per-segment cache, keyed by the layout parameters (a change of alignment or of
// any Knuth–Plass knob starts afresh). `exact` maps a width to its full layout;
// `obs` is the sorted list of observed widths with the geometry seen there.
export function segLayoutCache(s, key) {
    if (!s.hc || s.hc.key !== key) s.hc = { key, exact: new Map(), obs: [] };
    return s.hc;
}
export const EXACT_LAYOUTS_KEPT = 3;

export function rememberLayout(hc, w, L) {
    hc.exact.set(w, L);
    if (hc.exact.size > EXACT_LAYOUTS_KEPT) hc.exact.delete(hc.exact.keys().next().value);
    const o = { w, H: L.H, W: L.W, firstAscent: L.firstAscent, lastDepth: L.lastDepth, firstMeta: L.firstMeta,
                preDisplaySizeSp: L.preDisplaySizeSp, displayLeftSp: L.displayLeftSp, atSourceWidth: L.atSourceWidth };
    const obs = hc.obs;
    let k = 0;
    while (k < obs.length && obs[k].w < w) k++;
    if (k < obs.length && obs[k].w === w) obs[k] = o;   // re-observed: the real value wins
    else obs.splice(k, 0, o);
}

// Geometry for width w without laying out: an exact observation, or – heights
// being monotone in width – the interval between two observations of equal
// height that brackets w (the nearer end supplies the rest of the geometry).
export function cachedGeometry(hc, w) {
    const obs = hc.obs;
    let k = 0;
    while (k < obs.length && obs[k].w < w) k++;
    if (k < obs.length && obs[k].w === w) return obs[k];
    if (k === 0 || k === obs.length) return null;
    const a = obs[k-1], b = obs[k];
    if (a.H !== b.H) return null;
    return (w - a.w <= b.w - w) ? a : b;
}

// Run the deferred layout of segment i now (its lines are needed), size its
// element for the real geometry, and fix the spacing of the segment below it,
// which depends on this one's last depth. If the real height differs from the
// cached one, the following content simply moves; the observation is replaced.
export function materializeSegment(cache, i) {
    const laid = cache.layout && cache.layout.laid;
    const L = laid && laid[i];
    if (!L || !L.deferred) return;
    const ctx = cache.layoutCtx;
    useGlyphMetrics(cache.metrics);
    const s = cache.dom.segs[i];
    const real = ctx.layoutOne(ctx.segs[i], i);
    rememberLayout(segLayoutCache(s, ctx.paramsKey), ctx.widthPt, real);
    laid[i] = real;
    const remount = (seg, R, prev) => {
        const { mount, overflows } = sizeSegment(seg, R, prev, ctx.columnPx, ctx.p);
        if (mount.parentNode !== seg.box) seg.box.replaceChildren(mount);
        seg.mount = mount;
        if (overflows) requestAnimationFrame(() => updateDisplayOverflowCue(seg.wrap));
    };
    remount(s, real, laid[i-1]);
    if (laid[i+1]) remount(cache.dom.segs[i+1], laid[i+1], real);
    if (cache.layoutStats) cache.layoutStats.materialized++;
}
