// SPDX-License-Identifier: AGPL-3.0-or-later

// ── imports (generated by the split tooling; edit freely once the split is done)
import { ZOOM } from '../core.js';
import { layoutDocument } from './document.js';
import { STREAM_KINDS } from '../../index.js';
import { blockData, reflowBlock } from '../../runtime/blocks.js';
import { api } from '../../runtime/page.js';
import { paintVisibleNow } from '../../runtime/visibility.js';
// ── end of imports

// Size and position one segment's element for layout L: the <svg> surface, the
// scroll box a display that overflows the column needs, and the space above it,
// which depends on the previous segment's last depth. Returns what to mount.
// Shared by layoutDocument and materializeSegment; L may be a deferred layout
// (geometry from the height cache, no lines yet).
// ── Streams ───────────────────────────────────────────────────────────────────
// A stream is a separately typeset run of content (Document.streams): a
// footnote's body, or a block the author wrapped in the companion package's
// \begin{webstream}{kind}. Its content is an ordinary content stream
// over the block's shared paragraphs, so it is laid out by layoutDocument
// itself, recursively, into the segment's box – with its own cache, its own
// lazily painted segments, and streams of its own inside if it has them. The
// box is `<div class="latex-stream" data-kind="…">`; the kind decides how the
// page styles it and which behaviour, if any, it gets (STREAM_KINDS).
//
// Never cached at this level (the nested layout has its own cache) and never
// deferred: the box must exist and hold its content's height at once, and a
// hidden part (a collapsed body) is laid out but never painted, which is
// cheap. The width is the box's own inner width – so CSS padding on a kind
// narrows its measure – measured when the box is in the document; on the
// first, detached layout it falls back to the column and asks for one more
// pass (remeasureStreams).
export function layoutStreamSegment(fontInfo, doc, s, seg, widthPt, p, cache) {
    if (!s.sub) {
        s.sub = { bcs: cache.bcs, dom: null, layout: null, stats: null,
                  streamState: cache.streamState };
    }
    // clientWidth includes the padding a kind's CSS may add; the measure is
    // what is left inside it.
    let innerPx = 0, frameTop = false, frameBottom = false;
    if (s.box.isConnected) {
        const cs = getComputedStyle(s.box);
        innerPx = s.box.clientWidth - parseFloat(cs.paddingLeft) - parseFloat(cs.paddingRight);
        // A box whose CSS gives it padding or a border on a side is a frame
        // there (a boxed theorem, a note): TeX's interline glue does not
        // reach across a frame edge – the padding is the space there. A
        // bare stream (an accordion, a pane) stays part of the text.
        frameTop    = parseFloat(cs.paddingTop)    + parseFloat(cs.borderTopWidth)    > 0;
        frameBottom = parseFloat(cs.paddingBottom) + parseFloat(cs.borderBottomWidth) > 0;
    }
    let w = widthPt;
    if (innerPx > 0) w = innerPx / ZOOM;
    else cache.streamsUnmeasured = true;
    // A kind whose child streams are *alternatives* (an accordion's panes:
    // one shows at a time) has them laid out as if each alone stood here –
    // no spacing between them, since none ever follows another on screen.
    const hooks0 = api.streamKinds[seg.stream.kind] || STREAM_KINDS[seg.stream.kind];
    s.sub.alternatives = !!(hooks0 && hooks0.alternatives);
    const root = layoutDocument(fontInfo, { ...doc, content: seg.stream.content }, w, p, s.sub);
    if (root.parentNode !== s.box) s.box.replaceChildren(root);
    if (!s.mounted) {
        // The kind's behaviour gets the box once, after its first nested
        // layout, so whatever it looks for inside (its panes) exists.
        s.mounted = true;
        const kind = seg.stream.kind;
        const hooks = api.streamKinds[kind] || STREAM_KINDS[kind];
        if (hooks && hooks.mount) {
            let state = cache.streamState.get(seg.index);
            if (!state) { state = {}; cache.streamState.set(seg.index, state); }
            const attrs = Object.fromEntries((seg.stream.attrs || []).map(a => [a.key, a.value || '']));
            // paint(): after a behaviour reveals hidden content, draw it now
            // rather than on the IntersectionObserver's next report – so the
            // behaviour can, say, move focus into what it just showed.
            const sub = s.sub;
            const paint = () => paintVisibleNow(fontInfo, sub);
            // relayout(): lay the whole block out again at its current width,
            // for a behaviour that changed the width of its streams (putting
            // two side by side, say) without the block's own width changing.
            const relayout = () => {
                const el = s.box.closest('[data-nodelist-b64]');
                const d = el && blockData.get(el);
                if (!d) return;
                d.lastWidth = -1;
                reflowBlock(el);
            };
            try { hooks.mount(s.box, { kind, index: seg.index, stream: seg.stream, attrs, state, paint, relayout }); }
            catch (e) { console.error(`[latex-viewer] stream kind "${kind}" mount failed:`, e); }
        }
    }
    // What the neighbours need: the nested first line's ascent and leading
    // (for the interline glue above) and the last line's depth (for below).
    const laid = s.sub.layout.laid;
    const first = laid[0];
    let last = laid[laid.length - 1], alts = null;
    // The content's own edges, for CSS that sizes a frame around the ink
    // (the boxed-theorem padding: one x-height above the capitals of the
    // first line and below the last baseline). Written only on change.
    // A box that starts or ends with a display (or a box of its own) is
    // measured from that one's ink, not from a baseline: a fraction reaches far
    // below its baseline, and a rule meant for a line of text would pull the
    // frame onto it. Then the space is a plain x-height above or below.
    const textAt = L => L && L.seg && L.seg.kind === 'text';
    const fa = textAt(first) ? `${first.firstAscent}px` : 'var(--latex-cap-height, 0px)';
    const ld = textAt(last) ? `${last.lastDepth}px` : '0px';
    if (s.box.style.getPropertyValue('--latex-first-ascent') !== fa) s.box.style.setProperty('--latex-first-ascent', fa);
    if (s.box.style.getPropertyValue('--latex-last-depth') !== ld) s.box.style.setProperty('--latex-last-depth', ld);
    if (s.sub.alternatives) {
        // Each alternative's edges, so sizeSegment can give every one the
        // interline glue TeX would give it in this place. The first stands
        // for the group in the spacing computed at this level; the others
        // are offset from it (applyAlternativeOffsets).
        alts = laid.map((Lj, j) => ({ L: Lj, box: s.sub.dom.segs[j].box }))
                   .filter(a => a.L.seg.kind === 'stream');
        last = first;
    }
    return { seg, lines: [], H: root.offsetHeight, W: widthPt * ZOOM,
             firstAscent: first ? first.firstAscent : 0,
             lastDepth:   last  ? last.lastDepth    : 0,
             firstMeta:   first ? first.firstMeta   : null,
             alts, frameTop, frameBottom,
             gapBefore: seg.gapBefore || 0 };
}
