// SPDX-License-Identifier: AGPL-3.0-or-later

// ── imports (generated by the split tooling; edit freely once the split is done)
import { ZOOM } from '../core.js';
import { layoutDocument } from './document.js';
import { layoutHostedSegment } from '../../host/block-hosts.ts';
// ── end of imports

// Size and position one segment's element for layout L: the <svg> surface, the
// scroll box a display that overflows the column needs, and the space above it,
// which depends on the previous segment's last depth. Returns what to mount.
// Shared by layoutDocument and materializeSegment; L may be a deferred layout
// (geometry from the height cache, no lines yet).
// ── Streams ───────────────────────────────────────────────────────────────────
// A stream is a separately typeset run of content (Document.streams): a
// footnote's body, or a block the author wrapped in the companion package's
// \begin{webstream}{kind}. Its content is an ordinary content stream
// over the block's shared paragraphs, so it is laid out by layoutDocument
// itself, recursively, into the segment's box – with its own cache, its own
// lazily painted segments, and streams of its own inside if it has them. The
// box is `<div class="latex-stream" data-kind="…">`, styled by kind. A kind
// the page defines (host.define) draws in the box itself instead
// (host/block-hosts.ts).
//
// Never cached at this level (the nested layout has its own cache) and never
// deferred: the box must exist and hold its content's height at once, and a
// hidden part (a collapsed body) is laid out but never painted, which is
// cheap. The width is the box's own inner width – so CSS padding on a kind
// narrows its measure – measured when the box is in the document; on the
// first, detached layout it falls back to the column and asks for one more
// pass (remeasureStreams).
export function layoutStreamSegment(fontInfo, doc, s, seg, widthPt, p, cache) {
    // A kind the page draws itself (host.define): its host, not a nested layout.
    const hosted = layoutHostedSegment(s, seg, widthPt, cache);
    if (hosted) return hosted;
    if (!s.sub) {
        s.sub = { bcs: cache.bcs, dom: null, layout: null, stats: null,
                  hosts: cache.hosts,
                  blockEl: cache.blockEl, relayout: cache.relayout };
    }
    // clientWidth includes the padding a kind's CSS may add; the measure is
    // what is left inside it.
    let innerPx = 0, frameTop = false, frameBottom = false;
    if (s.box.isConnected) {
        const cs = getComputedStyle(s.box);
        innerPx = s.box.clientWidth - parseFloat(cs.paddingLeft) - parseFloat(cs.paddingRight);
        // A box whose CSS gives it padding or a border on a side is a frame
        // there (a boxed theorem, a note): TeX's interline glue does not
        // reach across a frame edge – the padding is the space there. A
        // bare stream (an accordion, a pane) stays part of the text.
        frameTop    = parseFloat(cs.paddingTop)    + parseFloat(cs.borderTopWidth)    > 0;
        frameBottom = parseFloat(cs.paddingBottom) + parseFloat(cs.borderBottomWidth) > 0;
    }
    let w = widthPt;
    if (innerPx > 0) w = innerPx / ZOOM;
    else cache.streamsUnmeasured = true;
    const root = layoutDocument(fontInfo, { ...doc, content: seg.stream.content }, w, p, s.sub);
    if (root.parentNode !== s.box) s.box.replaceChildren(root);
    // What the neighbours need: the nested first line's ascent and leading
    // (for the interline glue above) and the last line's depth (for below).
    const laid = s.sub.layout.laid;
    const first = laid[0];
    const last = laid[laid.length - 1];
    // The content's own edges, for CSS that sizes a frame around the ink
    // (the boxed-theorem padding: one x-height above the capitals of the
    // first line and below the last baseline). Written only on change.
    // A box that starts or ends with a display (or a box of its own) is
    // measured from that one's ink, not from a baseline: a fraction reaches far
    // below its baseline, and a rule meant for a line of text would pull the
    // frame onto it. Then the space is a plain x-height above or below.
    const textAt = L => L && L.seg && L.seg.kind === 'text';
    const fa = textAt(first) ? `${first.firstAscent}px` : 'var(--latex-cap-height, 0px)';
    const ld = textAt(last) ? `${last.lastDepth}px` : '0px';
    if (s.box.style.getPropertyValue('--latex-first-ascent') !== fa) s.box.style.setProperty('--latex-first-ascent', fa);
    if (s.box.style.getPropertyValue('--latex-last-depth') !== ld) s.box.style.setProperty('--latex-last-depth', ld);
    return { seg, lines: [], H: root.offsetHeight, W: widthPt * ZOOM,
             firstAscent: first ? first.firstAscent : 0,
             lastDepth:   last  ? last.lastDepth    : 0,
             firstMeta:   first ? first.firstMeta   : null,
             frameTop, frameBottom,
             gapBefore: seg.gapBefore || 0 };
}
