// SPDX-License-Identifier: AGPL-3.0-or-later

// ── imports (generated by the split tooling; edit freely once the split is done)
import { buildBreakCandidates, kpBreak } from '../breaker.js';
import { SP_TO_PX, ZOOM, fillInfo, gD, gH, gW, sumWidthSp } from '../core.js';
import { AFFINE_CHILD_LISTS, affineDisplayNode, preDisplaySizeSp } from './display.js';
import { mergeWidgetRuns } from '../../host/widgets.js';
// ── end of imports

// ── Document → SVG element ────────────────────────────────────────────────────
// A block is an ordered stream of paragraphs and displays (see latex.proto).
// The two are laid out very differently but stack identically, so both are
// reduced to the same "line" shape – {nodes, ratio, er, x0} – and the existing
// profiling, spacing, and reconciliation machinery then treats them alike:
//
//   paragraph → Knuth-Plass re-breaks it at the reader's width, many lines
//   display   → one line whose single node is TeX's finished box
//
// Displays are not re-broken or re-packed. The pipeline recovers sparse affine
// width derivatives by matching complete display trees from three increasingly
// wide TeX runs, and those finished dimensions are evaluated at the reader's
// width. The renderer never guesses which node is a gap or activates glue which
// TeX deliberately left slack.
//
// Split into two phases so far-from-viewport blocks can be sized without being
// drawn: layoutDocument runs KP + line spacing and sets the svg's dimensions
// (storing the result in cache.layout); paintDocument materialises the most
// recent layout into glyph/rule elements via the reconciling sink.

// Older blocks carry no content stream; treat them as all-paragraphs.
export function contentStream(doc) {
    if (doc.content && doc.content.length) return doc.content;
    return doc.paragraphs.map((_, i) => ({ kind: 'paragraph', para: i + 1 }));
}

// A block is split into segments rather than drawn as one SVG: runs of text
// share an SVG, but every display gets its own. A display keeps its compiled
// width, so it can be wider than the column – in one shared SVG that overflow
// would scroll the whole block, dragging text that fits perfectly out of view.
// Giving each display its own scroll container (as MathJax and KaTeX do) keeps
// the text still and lets only the maths pan.
//
// Segmentation depends solely on the content stream, never on width, so the
// segment list is stable across reflows and every element stays reusable.
export const HL_ALIGNMENT = 4;   // hlist subtype: one row of an alignment
export const HL_EQUATION  = 6;   // hlist subtype: a display that is not an alignment

// Anchor markers that ended up *inside* what was typeset – a \label written
// mid-sentence, or one amsmath replayed into a display's own box. Their exact
// pen position is known but not useful: an anchor is a scroll destination, and
// the segment is the smallest thing worth scrolling to. Walked once per
// paragraph/box ever, since neither the tree nor the answer changes with width.
export const anchorIdsCache = new WeakMap();
export function anchorIdsOf(key, roots) {
    let ids = anchorIdsCache.get(key);
    if (ids) return ids;
    ids = [];
    (function walk(ns) {
        for (const n of ns || []) {
            if (n.anchor) ids.push(n.anchor);
            walk(n.children); walk(n.pre); walk(n.post); walk(n.replace);
            if (n.leader) walk([n.leader]);
        }
    })(roots);
    anchorIdsCache.set(key, ids);
    return ids;
}

// A \begin{center}\includegraphics..\end{center}-style figure – a paragraph
// whose only ink is one or more pictures, no running text. \mypic in the
// transducers book is the motivating case, but the test is structural (picture
// present, no glyph present) so it holds for any front end's plain centred
// figure. Such a paragraph gets its own segment (isFigure, below) so a picture
// wider than the column can pan independently instead of bleeding into the
// margin, the same reasoning that gives every display its own scroll box.
// Cached per paragraph object, since segmentsOf reruns on every reflow.
export const figureParaCache = new WeakMap();
export function isFigureParagraph(para) {
    let v = figureParaCache.get(para);
    if (v !== undefined) return v;
    let hasPicture = false, hasGlyph = false;
    (function walk(ns) {
        for (const n of ns || []) {
            if (n.type === 'picture') hasPicture = true;
            else if (n.type === 'glyph') hasGlyph = true;
            walk(n.children); walk(n.pre); walk(n.post); walk(n.replace);
            if (n.leader) walk([n.leader]);
        }
    })(para.nodes);
    // No running text, only boxes – a table, a framed box, a picture: it is
    // one unbreakable piece, which scrolls when it is wider than the column.
    // (Glyphs inside the boxes are theirs, not running text; a tabular's box
    // stands between two math nodes, markers of the $...$ LaTeX builds it in.)
    const top = para.nodes || [];
    const boxOnly = !top.some(n => n.type === 'glyph' || n.type === 'disc')
        && top.some(n => (n.type === 'hlist' || n.type === 'vlist') && (n.width || 0) > 0 && (n.children || []).length);
    v = (hasPicture && !hasGlyph) || boxOnly;
    figureParaCache.set(para, v);
    return v;
}

export function segmentsOf(doc) {
    const segs = [];
    const pendingAnchors = [];
    const own = (seg, ids) => { if (ids.length) (seg.anchors ||= []).push(...ids); };
    // `vsp` is the vspace item behind `gap`, kept on what follows it for tools
    // that show what the space is made of (api.inspect); layout reads only gap.
    let text = null, gap = 0, vsp = null;
    for (const item of contentStream(doc)) {
        if (item.kind === 'vspace') { gap = (item.amount || 0) * SP_TO_PX; vsp = item; continue; }
        if (item.kind === 'anchorpoint') {
            // A label that stood between two items – nearly always straight
            // after a sectioning command, which is why it is in vertical mode
            // at all. Attach it to the item it *followed*, so jumping to it
            // lands on the heading rather than below it.
            //
            // Deliberately does not close the open text run or consume `gap`:
            // segmentation must depend only on what is typeset, or adding a
            // label would split a merged paragraph run and change its leading.
            const owner = segs[segs.length - 1];
            if (owner) (owner.anchors ||= []).push(item.anchor);
            else pendingAnchors.push(item.anchor);
            continue;
        }
        if (item.kind === 'stream') {
            // A separately typeset stream embedded here (what the companion
            // package's \begin{webstream} wraps). Its own segment: the
            // content is laid out as a nested block inside the segment's box,
            // at whatever width the page gives that box (see
            // layoutStreamSegment). Like a display it never merges with the
            // prose around it, and its anchors are the nested layout's concern.
            const stream = doc.streams && doc.streams[item.stream - 1];
            if (stream) {
                segs.push({ kind: 'stream', stream, index: item.stream, gapBefore: gap, vspace: vsp });
                text = null; gap = 0; vsp = null;
            }
            continue;
        }
        if (item.kind === 'display') {
            // Consecutive alignment rows are the rows of one align/gather, and
            // must be laid out together: they share a single offset so their
            // & alignment survives, and they pan as one unit rather than each
            // row scrolling separately. A \[..\] display is always its own
            // segment.
            const isAlign = item.box.subtype === HL_ALIGNMENT;
            const last    = segs[segs.length - 1];
            if (isAlign && last && last.kind === 'display' && last.isAlign) {
                last.rows.push({ item, gap, vspace: vsp });
            } else {
                segs.push({ kind: 'display', isAlign, rows: [{ item, gap: 0 }], gapBefore: gap, vspace: vsp });
            }
            own(segs[segs.length - 1], anchorIdsOf(item.box, item.box.children));
            text = null; gap = 0; vsp = null;
            continue;
        }
        const para = doc.paragraphs[item.para - 1];
        if (!para) continue;
        if (isFigureParagraph(para)) {
            // Never merges with neighbouring prose (own(...) + closing the run
            // below), for the same reason a display never does: it needs its own
            // scroll box, and a shared one would let an oversized figure drag
            // perfectly-fitting text out of view with it.
            const fig = { kind: 'text', isFigure: true,
                          items: [{ index: item.para, para }], gapBefore: gap, vspace: vsp };
            segs.push(fig);
            own(fig, anchorIdsOf(para, para.nodes));
            text = null; gap = 0; vsp = null;
            continue;
        }
        // Consecutive paragraphs normally merge into one text segment and stack
        // with adaptive leading. An explicit vspace before this paragraph (from
        // \vspace, or a section heading's before/after skip) breaks that merge:
        // the paragraph starts a new segment whose gapBefore reproduces exactly
        // the space TeX asked for (segment boxes stack baseline-to-baseline).
        if (!text || gap) { text = { kind: 'text', items: [], gapBefore: gap, vspace: vsp }; segs.push(text); vsp = null; }
        text.items.push({ index: item.para, para, vspace: vsp });   // a gap of 0 within the run
        own(text, anchorIdsOf(para, para.nodes));
        gap = 0; vsp = null;
    }
    // A label before anything was typeset has nothing to trail, so it leads.
    if (pendingAnchors.length && segs.length) own(segs[0], pendingAnchors);
    // Space after the last item. The main flow has none worth keeping, but a
    // stream can end with its environment's closing skip (a proof's \topsep
    // inside an accordion pane), which must still separate it from what
    // follows the stream – so layoutDocument ends with a spacer this high.
    segs.trailingGap = gap;
    return segs;
}

// Lay a text segment out: KP-break each paragraph at the reader's width and
// stack the lines with the adaptive collision-based leading.
// A paragraph's nodes at a measure. Boxes the pipeline found set to the
// measure carry *_rate fields (display_model.attach_paragraph_rates); they are
// evaluated like a display's tree, but never narrower than their floors allow –
// a table's column gaps closed, its natural width – and a paragraph without
// rates is returned as it is. The evaluation is kept for the last width asked.
export const paraEval = new WeakMap();
export function nodesHaveRates(ns) {
    for (const n of ns || []) {
        for (const k in n) if (k.endsWith('_rate')) return true;
        if (nodesHaveRates(n.children) || nodesHaveRates(n.pre) || nodesHaveRates(n.post)
            || nodesHaveRates(n.replace) || (n.leader && nodesHaveRates([n.leader]))) return true;
    }
    return false;
}
export function paragraphFloorWidth(n, sourceWidthSp) {
    let minimum = 0;
    for (const field of ['width', 'kern', 'surround']) {
        const rate = n[`${field}_rate`];
        if (n[`${field}_floor`] && rate > 0) minimum = Math.max(minimum, sourceWidthSp - (n[field] || 0) / rate);
    }
    if (n.glue_set_floor && n.glue_set_rate > 0)
        minimum = Math.max(minimum, sourceWidthSp - (n.glue_set || 0) / n.glue_set_rate);
    for (const key of AFFINE_CHILD_LISTS)
        for (const c of n[key] || []) minimum = Math.max(minimum, paragraphFloorWidth(c, sourceWidthSp));
    if (n.leader) minimum = Math.max(minimum, paragraphFloorWidth(n.leader, sourceWidthSp));
    return Math.min(minimum, sourceWidthSp);
}
export function paragraphAtWidth(para, widthSp, sourceWidthSp) {
    if (!(sourceWidthSp > 0)) return para.nodes;
    let memo = paraEval.get(para);
    if (!memo) { memo = { rated: nodesHaveRates(para.nodes) }; paraEval.set(para, memo); }
    if (!memo.rated) return para.nodes;
    const box = { type: 'hlist', children: para.nodes };
    if (memo.floorSp === undefined) memo.floorSp = paragraphFloorWidth(box, sourceWidthSp);
    const deltaSp = Math.max(widthSp, memo.floorSp) - sourceWidthSp;
    if (memo.deltaSp !== deltaSp) { memo.deltaSp = deltaSp; memo.nodes = affineDisplayNode(box, deltaSp).children || para.nodes; }
    return memo.nodes;
}

export function layoutTextSegment(fontInfo, seg, widthPt, p, cache) {
    const widthSp  = Math.round(widthPt * 65536);
    const columnPx = widthPt * ZOOM;
    const lines = [], lrp = [], meta = [];
    const itemStarts = [];            // the first line of each item (paragraph)
    // Right edge of the widest line's ink, tracked alongside the loop below.
    // columnPx-only would be wrong for a figure segment (see isFigureParagraph):
    // its one line is an unbreakable, unshrinkable box that is exactly as wide
    // as the source picture, so an oversized one is genuinely wider than the
    // column rather than merely mis-measured. Harmless for ordinary text, whose
    // segment W is never read (only isFigure's mount logic consults it).
    let maxRightPx = columnPx;

    for (const { index, para } of seg.items) {
        itemStarts.push(lines.length);
        // A paragraph holding a box set to the measure (a tabular*, a figure
        // scaled to \linewidth) carries rates: its nodes follow this width.
        const nodes = paragraphAtWidth(para, widthSp, cache.sourceWidthSp);
        let bcs = nodes === para.nodes ? cache.bcs.get(index) : null;
        if (!bcs) {
            bcs = buildBreakCandidates(nodes, fontInfo, para);
            if (nodes === para.nodes) cache.bcs.set(index, bcs);
        }

        // Alignment is per paragraph: TeX's \centering/\raggedright/\raggedleft
        // set the paragraph's \leftskip/\rightskip, which the serializer reads and
        // records as para.align. A paragraph with none (the common case) inherits
        // the block's alignment (p.align, from --latex-align). This is what centres
        // a \maketitle title inside an otherwise justified document.
        const align   = para.align || p.align;
        const justify = align === 'justify';

        // TeX interline parameters for this paragraph (sp → px). bskip>0 marks
        // "use the LaTeX rule"; absent (old data) falls back to adaptive leading.
        const lineMeta = para.baselineskip ? {
            bskip:      para.baselineskip  * SP_TO_PX,
            lskip:      (para.lineskip || 0) * SP_TO_PX,
            lskiplimit: (para.lineskiplimit || 0) * SP_TO_PX,
        } : null;

        // A list item's indent is a fixed measure (\leftmargin), so it stays
        // put and the text column narrows around it. The item's label hangs a
        // fixed distance to the left of this offset, which is precisely why
        // the indent has to be applied – at x0=0 the label would sit at
        // negative x and be clipped away.
        const indentSp = para.indent || 0;
        const indentPx = indentSp * SP_TO_PX;
        // A paragraph's measure can be narrower than the column on the right
        // too: a quote environment sets \hsize = \textwidth - 2\leftmargin
        // and the serializer records that width with the left indent. The
        // right margin is what remains of the source width, and it is as
        // fixed a measure as the left one, so it narrows the text column the
        // same way. (At the source width, keeping only the left indent set
        // a 295pt quote at 320pt: a line TeX had to shrink came out at its
        // natural width, 22pt wider than in the PDF.)
        const rightSp  = (cache.sourceWidthSp > 0 && para.width > 0)
            ? Math.max(0, cache.sourceWidthSp - indentSp - para.width) : 0;
        // A figure paragraph (a picture, a table, a framed box – no running
        // text) is one piece: wider than the column it scrolls whole, so it is
        // broken against its own width and stays one line, as TeX set it.
        const availSp  = Math.max(1, widthSp - indentSp - rightSp,
                                  seg.isFigure ? sumWidthSp(nodes) : 0);
        const availPx  = columnPx - indentPx - rightSp * SP_TO_PX;

        // Pluggable breaker. A page may install an alternative paragraph
        // breaker as window.reflowtexBreak(nodes, availSp, params, helpers)
        // – e.g. a TeX engine's own line-breaking code compiled to WebAssembly.
        // It returns the same line objects kpBreak does ([{nodes, ratio,
        // fitness, leftProtrusion}]; kpBreak's also carry rightProtrusion,
        // where a TeX engine returns the right margin kern as a node), or
        // null to decline (module still
        // loading, unsupported paragraph), in which case the built-in
        // Knuth–Plass runs. Everything below is agnostic to which breaker ran.
        // A line flagged `exact: true` carries a TeX-exact glue ratio whose
        // stretch pool holds no glyph expandability, so the viewer's own
        // expansion is not applied on top of it; a line carrying `expand` (a
        // fraction: 0.012 = glyphs 1.2 % wider) was expanded by the breaker
        // itself, exactly that much. The helpers also hand over what TeX had
        // for microtypography – each font's protrusion/expansion codes and
        // the paragraph's \adjustspacing/\protrudechars – so an engine can
        // apply them as TeX did.
        const ext = typeof window !== 'undefined' && typeof window.reflowtexBreak === 'function'
            ? window.reflowtexBreak(nodes, availSp, p, {
                  gW, gH, gD, align,
                  bskip: para.baselineskip || 0,
                  lskip: para.lineskip || 0,
                  font: fid => fontInfo[String(fid)] || null,
                  adjustSpacing: para.adjust_spacing || 0,
                  protrudeChars: para.protrude_chars || 0,
              })
            : null;
        for (const ln of (ext || kpBreak(bcs, nodes, availSp, justify ? p : { ...p, ragged: true }))) {
            ln.nodes = mergeWidgetRuns(ln.nodes);
            // For non-justified modes: allow glue shrink (ratio<0) but never stretch.
            // When the line must shrink, rendering and positioning are identical to justify.
            // The alignment offset only applies to lines whose natural width fits the column.
            const ratio = justify ? ln.ratio : Math.min(0, ln.ratio);
            const er    = ln.expand !== undefined ? ln.expand
                        : (p.useExpansion && !ln.exact) ? ratio * p.maxExpand : 0;
            const protX = -(p.useProtrusion ? ln.leftProtrusion * SP_TO_PX : 0);
            const natSp = sumWidthSp(ln.nodes);
            const natPx = natSp * SP_TO_PX;
            let x0, fillRatio = 0, fillOrder = 0;
            if (ratio < 0 || natPx > availPx) {
                // ratio<0 is not a reliable proxy for "too wide to fit" on its
                // own: kpBreak's ratio falls back to exactly 0 (not negative)
                // when a line is overfull but every glue order has zero
                // shrinkability to report a shrink ratio against – exactly
                // \begin{center}'s infinite-stretch, zero-shrink centring
                // glue. Left unguarded, the center/right branch below computes
                // a negative x0 for any centred figure wider than the column,
                // drawing it into negative SVG coordinates: still positioned
                // correctly relative to nothing, but visibly detached to the
                // left of the column instead of flush with its left edge.
                x0 = protX;  // squeezed to fit – same position as justified
            } else {
                // TeX's line box holds its margin kerns, so a centred or
                // right-aligned line is placed by its width less what
                // protrudes, and its first character then hangs out of that
                // place by the left protrusion. (A breaker that returns the
                // right margin kern as a node has it in natPx already; the
                // built-in one reports it as rightProtrusion.)
                const lpPx = -protX;
                const rpPx = p.useProtrusion ? (ln.rightProtrusion || 0) * SP_TO_PX : 0;
                switch (align) {
                    case 'right':  x0 = availPx - natPx + rpPx; break;
                    case 'center': x0 = (availPx - natPx + lpPx + rpPx) / 2 - lpPx; break;
                    default:       x0 = protX; break;
                }
                // A line with an infinite fill and room to spare distributes the
                // slack into that fill (KP left it at ratio 0), flushing whatever
                // follows to the right margin. This is set-once at layout: the fill
                // stretch is a fixed measure, only the available width varies.
                const fi = fillInfo(ln.nodes);
                if (fi.order > 0 && fi.stretch > 0) {
                    // TeX packs the line with its left margin kern in it, so a
                    // protruding first character widens the slack by what it
                    // hangs into the margin – the line still ends at the measure.
                    // (Its right margin kern, when any, is a kern node in ln.nodes.)
                    const leftKernSp = p.useProtrusion ? (ln.leftProtrusion || 0) : 0;
                    const slackSp = availSp - (natSp - leftKernSp);
                    if (slackSp > 0) { fillRatio = slackSp / fi.stretch; fillOrder = fi.order; x0 = protX; }
                }
            }
            maxRightPx = Math.max(maxRightPx, x0 + indentPx + natPx);
            lines.push(ln);
            lrp.push({ ratio, er, x0: x0 + indentPx, fillRatio, fillOrder });
            meta.push(lineMeta);
        }
    }
    return { lines, lrp, meta, itemStarts, W: Math.ceil(maxRightPx),
             preDisplaySizeSp: preDisplaySizeSp(fontInfo, lines, lrp) };
}
