// SPDX-License-Identifier: AGPL-3.0-or-later

// ── imports (generated by the split tooling; edit freely once the split is done)
import { placeMarginNotes } from '../defaults/margin-notes.js';
import { SP_TO_PX, ZOOM, sumWidthSp } from '../engine/core.js';
import { layoutDocument } from '../engine/layout/document.js';
import { paintDocument } from '../engine/paint.js';
import { NATURAL_PROBE_PT, blockData } from '../runtime/blocks.js';
import { api } from '../runtime/page.js';
// ── end of imports

// ── Asides (\webaside) ─────────────────────────────────────────────────────
// Streams typeset out of the flow (marked aside=true by the serializer),
// which a page shows where it likes. A handle per aside, for a widget
// (ctx.asides) or a page script (reflowtex.asides(block)):
//
//   { kind, attrs,                  its kind and parameters (attrs.for, …)
//     block,                        the block element it belongs to
//     width(),                      its natural width in px: every paragraph
//                                   on one line, as TeX would set an \hbox
//     render(el, widthPx?),         lays it out in el, at widthPx or its
//                                   natural width, and paints it; returns
//                                   { width, baseline } – the first
//                                   baseline, px down from el's top
//     anchor() }                    where it stood in the text, if it stood in
//                                   running text and that line is drawn: a
//                                   DOMRect of zero size on the baseline, in
//                                   the window; else null
//
// A query is a kind ('margin'), or an object of which `kind` and any
// parameters must all match ({ kind: 'popover-note', for: '1' }); nothing
// matches every aside. Each render is a layout of its own, so an aside may be
// drawn in several places at once and at any width. After every layout, and
// whenever lines are drawn as they near the window, a block sends
// reflowtex:layout (bubbling), for a page that places asides by their anchors
// to place them again.
export const docData = new WeakMap();          // a block's decoded document → its data
export const allData = [];                     // every block's data, in page order

export function asideMatch(query, kind, attrs) {
    if (!query) return true;
    if (typeof query === 'string') return kind === query;
    return Object.entries(query).every(([k, v]) => (k === 'kind' ? kind : attrs[k]) === String(v));
}
export function asideHandles(data, query) {
    if (!data) return [];
    const out = [];
    (data.doc.streams || []).forEach((s, i) => {
        const attrs = Object.fromEntries((s.attrs || []).map(a => [a.key, a.value]));
        if (attrs.aside === 'true' && asideMatch(query, s.kind, attrs)) out.push(asideHandle(data, s, attrs, i + 1));
    });
    return out;
}
export function asideHandle(data, stream, attrs, index) {
    const doc = { ...data.doc, content: stream.content };
    const lay = widthPx => {
        const cache = { bcs: null, dom: null, layout: null, stats: null };
        const root = layoutDocument(data.fontInfo, doc, widthPx / ZOOM, data.params, cache);
        return { cache, root };
    };
    let natural = null;
    const width = () => {
        if (natural === null) {
            const { cache } = lay(NATURAL_PROBE_PT * ZOOM);
            let w = 0;
            for (const L of cache.layout.laid)
                (L.lines || []).forEach((ln, j) => {
                    w = Math.max(w, ((L.lrp && L.lrp[j]) ? L.lrp[j].x0 : 0) + sumWidthSp(ln.nodes) * SP_TO_PX);
                });
            natural = Math.ceil(w + 0.5);
        }
        return natural;
    };
    return {
        kind: stream.kind, attrs, width, block: data.el, index,
        anchor() {
            // From the mark's own point and transform: WebKit gives an empty
            // rect's box as its <svg>'s corner.
            const m = data.el && data.el.querySelector(`.latex-aside-mark[data-aside="${index}"]`);
            const ctm = m && m.getScreenCTM();
            if (!ctm) return null;
            const p = new DOMPoint(+m.getAttribute('x'), +m.getAttribute('y')).matrixTransform(ctm);
            return new DOMRect(p.x, p.y, 0, 0);
        },
        render(el, widthPx) {
            const w = widthPx || width();
            const { cache, root } = lay(w);
            const box = document.createElement('div');
            box.className = 'latex-block latex-aside';
            // Its own size and nothing else: no margin a page gives its blocks.
            box.style.cssText = `width:${w}px;margin:0`;
            box.appendChild(root);
            el.replaceChildren(box);
            paintDocument(data.fontInfo, cache);
            const first = cache.layout.laid[0], baseline = first ? first.firstAscent : 0;
            box.dataset.baseline = baseline;   // for whoever aligns it (placeMarginNotes)
            return { width: w, baseline };
        },
    };
}
// reflowtex.asides(block, query): one block's asides; asides(query): every block's.
api.asides = (block, query) => block instanceof Element
    ? asideHandles(blockData.get(block), query)
    : allData.flatMap(d => asideHandles(d, block));
export function announceLayout(el) {
    placeMarginNotes(blockData.get(el));
    el.dispatchEvent(new CustomEvent('reflowtex:layout', { bubbles: true, detail: { block: el } }));
}
