// SPDX-License-Identifier: AGPL-3.0-or-later

// ── imports (generated by the split tooling; edit freely once the split is done)
import { placeMarginNotes } from '../defaults/margin-notes.ts';
import { blockData } from '../runtime/blocks.js';
// ── end of imports

// Per-block data the host modules look up. Asides themselves (\webaside:
// streams typeset out of the flow) are detached instances of the host API
// (host/instances.ts): a page finds them with host.instances({ placement:
// 'detached', … }), mounts their parts where it likes and places them by
// instance.anchor().
export const docData = new WeakMap();          // a block's decoded document → its data
export const allData = [];                     // every block's data, in page order

// After every layout, and whenever lines are drawn as they near the window,
// a block places its margin notes again and sends reflowtex:layout
// (bubbling; block.on('layout') in the host API), for a page that places
// things by anchors.
export function announceLayout(el) {
    placeMarginNotes(blockData.get(el));
    el.dispatchEvent(new CustomEvent('reflowtex:layout', { bubbles: true, detail: { block: el } }));
}
