// SPDX-License-Identifier: AGPL-3.0-or-later

// ── imports (generated by the split tooling; edit freely once the split is done)
import { SP_TO_PX, useGlyphMetrics } from '../engine/core.js';
import { paintCount, renderNodes } from '../engine/paint.js';
import { blockData } from '../runtime/blocks.js';
import { api } from '../runtime/page.js';
// ── end of imports

// ── Inspection ───────────────────────────────────────────────────────────────
// For developer tools – a browser extension that shows boxes and glue, a test
// harness. Read-only by convention: the state objects are the renderer's own,
// and their shapes are internal and may change between versions (hence the
// version number).
//
//   blocks()                every initialised block element on the page
//   state(el)               { doc, fontInfo, cache, lastWidth, params, … }
//   spToPx                  scaled points → the svg user units below
//   paints                  a counter, bumped by every segment paint: a tool
//                           polls it to notice a reflow
//   replay(el, i, sink[, cache])
//                           re-runs the drawing of segment i of `cache` (the
//                           block's own by default; a stream's nested one,
//                           cache.dom.segs[k].sub, for its segments) through
//                           `sink`, touching no DOM. sink.line(j, line, x0,
//                           baselineY), sink.node(n, x, baselineY, advance) and
//                           sink.vnode(n, x, top, advance) are all optional;
//                           coordinates are the segment <svg>'s user units
//                           (cache.dom.segs[i].svg). False when the segment has
//                           no lines yet (a stream, or a layout deferred until
//                           it scrolls near).
export const inspectable = new Set();
api.inspect = {
    version: 1,
    spToPx: SP_TO_PX,          // scaled points → svg user units
    blocks: () => [...inspectable].filter(el => el.isConnected),
    state: el => blockData.get(el),
    get paints() { return paintCount; },
    replay(el, i, sink, cache) {
        const data = blockData.get(el);
        cache = cache || (data && data.cache);
        const L = cache && cache.layout && cache.layout.laid[i];
        if (!L || L.deferred || !L.lines || !L.lrp) return false;
        useGlyphMetrics(cache.metrics);
        const noop = () => {};
        const s = { glyph: noop, missing: noop, space: noop, rule: noop, picture: noop,
                    beginTransform: noop, endTransform: noop,
                    node: sink.node, vnode: sink.vnode };
        for (let j = 0; j < L.lines.length; j++) {
            const { ratio, er, x0, fillRatio, fillOrder } = L.lrp[j];
            if (sink.line) sink.line(j, L.lines[j], x0, L.baselineYs[j]);
            renderNodes(data.fontInfo, s, L.lines[j].nodes, x0, L.baselineYs[j],
                        fillOrder ? fillRatio : ratio, er, fillOrder || 0);
        }
        return true;
    },
};
