// SPDX-License-Identifier: AGPL-3.0-or-later

// ── imports (generated by the split tooling; edit freely once the split is done)
import { svgEl } from '../engine/paint.js';
import { dispatchAction } from './actions.ts';
// ── end of imports

// ── Cross-references ─────────────────────────────────────────────────────────
// A \ref stamps every glyph of its printed text with the same document-local id
// (see template.tex), so a reference is a *set* of glyphs, not one. That is what
// makes it possible to light the whole reference up on hover even when the
// browser has broken it across two lines – the pieces never had to stay
// adjacent, they only have to share an id.
//
// Where a label lives is not something this file can know: one LaTeX document
// may be published as one page or, as a book is, as one page per chapter. So
// resolution is split. Labels that some block *on this page* defines are
// resolved here, against what was actually compiled. Everything else is looked
// up in an optional page-supplied map, which is the only place that knows how
// this document was carved into URLs. A label in neither is not a link at all:
// it keeps its text and its ordinary colour, so a reference whose target was
// never published can never masquerade as something to click.
export let linkMap    = {};        // label → href, from the page (#latex-link-map)
export const pageLabels = new Set();  // labels defined by some block on this page
export const linkTargets = new Map(); // label → the anchor element, once one exists
// The directory the viewer was loaded from, which is the site root. Same trick
// as fontBase, and for the same reason: resolving from the script's own URL is
// the one thing that is true whether the site is at a domain root, under a
// subpath, or opened from disk.
export let siteBase = document.currentScript && document.currentScript.src
    ? new URL('.', document.currentScript.src).href
    : (typeof location !== 'undefined' ? location.href : '/');

export function loadLinkMap() {
    const el = document.getElementById('latex-link-map');
    if (!el || !el.textContent.trim()) return;
    try {
        const d = JSON.parse(el.textContent);
        if (d && typeof d === 'object') linkMap = d;
    } catch { /* leave it empty; references simply stay inert */ }
}

// Where a link points, as something the browser can navigate to from wherever
// this page happens to be sitting.
//
// The map holds paths relative to the *site root*, not to the server root, and
// they are resolved against the directory the viewer script itself was loaded
// from. That is what makes a built site portable: the same files work served at
// a domain root, served under a subpath, and opened straight off disk over
// file://, without anything being rewritten between those cases.
export function linkHref(link) {
    if (!link) return null;
    if (link.url) return link.url;
    const label = link.label;
    if (!label) return null;
    if (linkTargets.has(label) || pageLabels.has(label)) return '#' + label;
    const rel = linkMap[label];
    if (!rel) return null;
    try { return new URL(rel, siteBase).href; } catch { return rel; }
}

// Toggle a state class across every glyph of one reference. The group is found
// by data-link, which is block-scoped, so two references printing the same
// number stay independent and one that spans a line break still lights up whole.
export function setLinkState(key, cls, on) {
    if (!key) return;
    const els = document.querySelectorAll(`[data-link="${CSS.escape(key)}"]`);
    for (const el of els) el.classList.toggle(cls, on);
    drawLinkUnderline(key, els);
}

// The underline of a hovered reference. CSS text-decoration would underline
// each glyph on its own – every glyph is a separately placed tspan, and the
// spaces between words are not glyphs at all – so the viewer draws it: one
// line per text line, from the reference's first glyph to its last. Glyphs
// are grouped by their SVG and baseline, so a reference broken across lines
// gets one underline per piece. In the glyphs' current colour, so hover and
// press colours carry over.
export function drawLinkUnderline(key, els) {
    for (const old of document.querySelectorAll('.latex-link-underline')) old.remove();
    // Glyphs only: a hit area (paintLinkHits) spans the same extent, and is
    // transparent – its fill is no colour for the line.
    const hover = [...els].filter(el => el.classList.contains('latex-link-hover')
                                        && !el.classList.contains('latex-link-hit'));
    if (!hover.length) return;
    const lines = [];   // { svg, base, left, right, em, colour }
    for (const el of hover) {
        const svg = el.ownerSVGElement, ctm = el.getScreenCTM(), sctm = svg?.getScreenCTM();
        if (!svg || !ctm || !sctm) continue;
        const r = el.getBoundingClientRect();
        if (!r.width) continue;
        const inv = sctm.inverse();
        const at = (x, y) => new DOMPoint(x, y).matrixTransform(inv);
        // Baseline from the tspan's own position; extent from its ink box.
        const q = new DOMPoint(+el.getAttribute('x'), +el.getAttribute('y')).matrixTransform(ctm);
        const base = at(q.x, q.y).y;
        const left = at(r.left, r.top).x, right = at(r.right, r.top).x;
        const em = (+el.getAttribute('font-size') || 12) * Math.hypot(ctm.a, ctm.b) / Math.hypot(sctm.a, sctm.b);
        let line = lines.find(l => l.svg === svg && Math.abs(l.base - base) < .6 * Math.max(l.em, em));
        if (!line) lines.push(line = { svg, base, left, right, em, colour: getComputedStyle(el).fill });
        line.base = Math.max(line.base, base); line.em = Math.max(line.em, em);
        line.left = Math.min(line.left, left); line.right = Math.max(line.right, right);
    }
    for (const l of lines) {
        const y = l.base + .13 * l.em;
        const u = svgEl('line', { x1: l.left, x2: l.right, y1: y, y2: y, 'stroke-width': Math.max(.065 * l.em, 1) });
        u.setAttribute('class', 'latex-link-underline');
        u.style.cssText = `stroke:${l.colour};pointer-events:none`;
        l.svg.appendChild(u);
    }
}

// The reference under the pointer, and the one being pressed (data-link keys).
// Module-level so a repaint can restore them: a reflow while the pointer rests
// on a reference (a \webtext changing, say) moves its glyphs, may draw them as
// new elements without the state classes, and leaves the drawn underline where
// the glyphs were.
export let hot = null, held = null, linkRestoreQueued = false;
export let hotWidget = null, heldWidget = null;
export function restoreLinkStates() {
    if ((!hot && !held && !hotWidget && !heldWidget) || linkRestoreQueued) return;
    linkRestoreQueued = true;
    queueMicrotask(() => {
        linkRestoreQueued = false;
        setLinkState(held, 'latex-link-active', true);
        setLinkState(hot, 'latex-link-hover', true);
        setWidgetState(heldWidget, 'latex-widget-active', true);
        setWidgetState(hotWidget, 'latex-widget-hover', true);
    });
}

// A widget split across two lines is one widget: pointing at, or pressing,
// either part marks every part of it (latex-widget-hover / -active on the
// foreignObjects), so a widget's CSS styles them together – as a reference
// broken across lines lights up whole.
export function setWidgetState(key, cls, on) {
    if (!key) return;
    for (const el of document.querySelectorAll(`foreignObject[data-widget="${CSS.escape(key)}"]`))
        el.classList.toggle(cls, on);
}
export function installWidgetStates() {
    const keyAt = t => (t && t.closest) ? t.closest('foreignObject[data-widget]')?.dataset.widget || null : null;
    document.addEventListener('pointerover', e => {
        const key = keyAt(e.target);
        if (key === hotWidget) return;
        setWidgetState(hotWidget, 'latex-widget-hover', false);
        hotWidget = key;
        setWidgetState(hotWidget, 'latex-widget-hover', true);
    }, { passive: true });
    document.addEventListener('pointerout', e => {
        if (keyAt(e.relatedTarget) === hotWidget) return;
        setWidgetState(hotWidget, 'latex-widget-hover', false); hotWidget = null;
    }, { passive: true });
    document.addEventListener('pointerdown', e => {
        heldWidget = keyAt(e.target);
        setWidgetState(heldWidget, 'latex-widget-active', true);
    }, { passive: true });
    const release = () => { setWidgetState(heldWidget, 'latex-widget-active', false); heldWidget = null; };
    document.addEventListener('pointerup', release, { passive: true });
    document.addEventListener('pointercancel', release, { passive: true });
}

export function installLinks() {
    loadLinkMap();
    const linkAt = t => (t && t.closest) ? t.closest('[data-link]') : null;

    document.addEventListener('pointerover', e => {
        const el = linkAt(e.target), key = el?.dataset.link || null;
        if (key === hot) return;
        setLinkState(hot, 'latex-link-hover', false);
        hot = key;
        setLinkState(hot, 'latex-link-hover', true);
    }, { passive: true });
    document.addEventListener('pointerout', e => {
        if (linkAt(e.relatedTarget)?.dataset.link === hot) return;
        setLinkState(hot, 'latex-link-hover', false); hot = null;
    }, { passive: true });

    // Pressed state is its own class so a page can colour press differently from
    // hover. Released globally, not on the glyph, or a drag off the reference
    // would leave it stuck looking pressed.
    document.addEventListener('pointerdown', e => {
        held = linkAt(e.target)?.dataset.link || null;
        setLinkState(held, 'latex-link-active', true);
    }, { passive: true });
    const release = () => { setLinkState(held, 'latex-link-active', false); held = null; };
    document.addEventListener('pointerup', release, { passive: true });
    document.addEventListener('pointercancel', release, { passive: true });

    document.addEventListener('click', e => {
        const el = linkAt(e.target);
        if (el && el.dataset.linkAction) {
            // To the instances that handle it, innermost first, then as a
            // DOM event for page scripts (host/actions.ts).
            e.preventDefault();
            dispatchAction(el, el.dataset.linkAction);
            return;
        }
        const href = el && el.dataset.linkHref;
        if (!href) return;
        e.preventDefault();
        const local = el.dataset.linkLabel && linkTargets.get(el.dataset.linkLabel);
        if (local) {
            local.scrollIntoView({ behavior: 'smooth', block: 'start' });
            // Leave the fragment in the address bar so the position is
            // shareable and the back button behaves, without a second jump.
            history.pushState(null, '', href);
        } else {
            window.location.href = href;
        }
    });

    // Keyboard: a reference is focusable (see registerLinkGlyph), so Enter and
    // Space must do what a click does.
    document.addEventListener('keydown', e => {
        if (e.key !== 'Enter' && e.key !== ' ') return;
        const el = linkAt(e.target);
        if (!el) return;
        e.preventDefault();
        el.dispatchEvent(new MouseEvent('click', { bubbles: true }));
    });
}

// Tag one glyph of a reference. Only a reference we can actually resolve is
// marked – an unresolvable one is left as plain text (see the note above).
// Attached once, at element creation, so the reconciler's reuse keeps it.
export function registerLinkGlyph(el, id, cache) {
    const link = cache.links?.[id - 1];
    // An action (\webaction) is a control rather than a destination: it
    // has no href, is always live, and is announced as a button.
    const action = link && link.action;
    const href = action ? null : linkHref(link);
    if (!href && !action) return;
    el.classList.add('latex-link');
    el.dataset.link = `${cache.blockKey}:${id}`;
    if (action) { el.classList.add('latex-action'); el.dataset.linkAction = action; }
    else el.dataset.linkHref = href;
    if (link.label) el.dataset.linkLabel = link.label;
    // One glyph of the reference carries the accessible name and the tab stop;
    // the rest are decoration, so a screen reader reads "Section 2", not "2 2 2".
    if (!document.querySelector(`[data-link="${CSS.escape(el.dataset.link)}"]`)) {
        el.setAttribute('role', action ? 'button' : 'link');
        el.setAttribute('tabindex', '0');
    }
}
