// SPDX-License-Identifier: AGPL-3.0-or-later

// ── imports (generated by the split tooling; edit freely once the split is done)
import { SP_TO_PX, gD, gH, useGlyphMetrics } from '../engine/core.js';
import { layoutDocument } from '../engine/layout/document.js';
import { widgetNodes } from './widgets.js';
import { blockData } from '../runtime/blocks.js';
import { api } from '../runtime/page.js';
import { paintVisibleNow } from '../runtime/visibility.js';
// ── end of imports

// ── Slots (\webtext) ──────────────────────────────────────────────────────────
// reflowtex.sty's \webtext{name}{default} leaves a run of glyphs and spaces in a
// paragraph, each carrying the slot's id (Node.slot → Document.slots). Until a
// page gives the name a text, TeX's typesetting of the default is shown as is.
// Once it does – reflowtex.setText(name, text) – the run is replaced by the
// text set the way a browser sets it: split at breakable white space, each
// word one glyph-like node measured by the browser in the slot's font (no
// kerning, ligatures or expansion between words, which the browser's own
// shaping handles within them), and between words the interword glue of that
// font as TeX recorded it. The paragraph then re-breaks around the new text,
// and only the segments holding it are laid out and painted again.
export const slotValues = new Map();          // name → string (absent: the default)
export const slotBlocks = new Set();          // blocks whose document has slots
export let slotMeasure = null;                // a canvas context, made on first use
export let slotScheduled = false;

// The width of `text` in font `fi`, in sp, as the browser draws it.
export function measureSlotText(fi, text) {
    slotMeasure = slotMeasure || document.createElement('canvas').getContext('2d');
    slotMeasure.font = `${fi.size_px}px ${JSON.stringify(fi.family)}`;
    return Math.round(slotMeasure.measureText(text).width / SP_TO_PX);
}

// The nodes a slot's text becomes. The font and colour are those of the
// default's first glyph; height and depth the default's own, so replacing a
// text never moves the line's baseline.
export function slotNodes(fontInfo, slot, id, run, text) {
    const glyphs = [];
    const walk = ns => { for (const n of ns) { if (n.type === 'glyph') glyphs.push(n); else if (n.type === 'disc') walk(n.replace || []); } };
    walk(run);
    const t = glyphs[0];
    if (!t) return run;                // nothing to take the font from: keep the default
    const fi = fontInfo[String(t.font)];
    if (!fi || fi.unresolved) return run;
    const height = Math.max(...glyphs.map(gH)), depth = Math.max(...glyphs.map(gD));
    const spec = `${fi.size_px}px ${JSON.stringify(fi.family)}`;
    // Measured again once the face has loaded, if it had not yet.
    if (document.fonts && !document.fonts.check(spec, text)) {
        document.fonts.load(spec, text).then(() => scheduleSlots(), () => {});
    }
    const out = [];
    // Breakable white space separates words; no-break spaces stay inside one.
    for (const part of String(text).split(/([^\S\u00A0\u202F]+)/)) {
        if (!part) continue;
        if (/^[^\S\u00A0\u202F]+$/.test(part)) {
            out.push({ type: 'glue', subtype: 13, width: slot.space || 0,
                       stretch: slot.stretch || 0, shrink: slot.shrink || 0, slot: id });
        } else {
            out.push({ type: 'glyph', text: part, font: t.font, color: t.color, slot: id,
                       width: measureSlotText(fi, part), height, depth });
        }
    }
    return out;
}

// Rebuild the node list of every paragraph holding a slot from its original
// list, substituting the runs whose name has a text. Returns the indices of
// the paragraphs whose list changed.
export function applySlots(fontInfo, doc) {
    const slots = doc.slots || [];
    if (!doc.slotParas) {
        doc.slotParas = [];
        (doc.paragraphs || []).forEach((para, i) => {
            if ((para.nodes || []).some(n => n.slot)) doc.slotParas.push({ index: i + 1, para, orig: para.nodes, made: [] });
        });
    }
    useGlyphMetrics(doc.glyph_metrics);
    const changed = new Set();
    for (const sp of doc.slotParas) {
        const orig = sp.orig, out = [], made = [];
        for (let i = 0; i < orig.length; i++) {
            const id = orig[i].slot, slot = id && slots[id - 1];
            const isWidget = slot && slot.kind === 'widget';
            const text = slot && !isWidget ? slotValues.get(slot.name) : undefined;
            if (!slot || (!isWidget && text === undefined)) { out.push(orig[i]); continue; }
            // The run: from here to the last node of this slot (a disc or a
            // font kern between its glyphs carries no id of its own).
            let j = i;
            for (let k = i + 1; k < orig.length; k++) if (orig[k].slot === id) j = k;
            const run = orig.slice(i, j + 1);
            const nodes = isWidget ? widgetNodes(fontInfo, slot, id, run, orig.slice(0, i), orig.slice(j + 1), doc)
                                   : slotNodes(fontInfo, slot, id, run, text);
            if (!nodes) { out.push(orig[i]); continue; }
            out.push(...nodes); made.push(...nodes);
            i = j;
        }
        // What was substituted, with its measured widths: a text measured
        // again once its font has loaded counts as a change.
        const key = made.map(n => n.text !== undefined ? n.text + '\u0002' + n.width
                                : n.type === 'wdisc' || n.type === 'widget' ? 'w' + JSON.stringify([n.slot, n.version ?? (n.run && n.run.version) ?? n.replace[0].version, n.width ?? n.replace[0].width, n.options && n.options.map(o => [o.pre[0].width, o.post[0].width])])
                                : n.type === 'disc' && n.slot ? 'd' + JSON.stringify([n.slot, n.penalty, n.pre.map(x => x.width), n.post.map(x => x.width), n.replace.map(x => x.width)])
                                : ' ').join('\u0001');
        if (key === sp.key && sp.made.length === made.length) continue;
        sp.key = key;
        sp.stale = sp.made; sp.made = made;
        sp.para.nodes = made.length ? out : orig;
        changed.add(sp.index);
    }
    return changed;
}

// Forget the layouts of the segments holding those paragraphs (in the nested
// layouts of streams too), and the drawn elements of the words replaced.
export function invalidateParagraphs(cache, changed, stale) {
    if (!cache || !cache.dom || !cache.layoutCtx) return;
    for (const i of changed) cache.bcs && cache.bcs.delete(i);
    for (const n of stale) cache.dom.byNode.delete(n);
    cache.layoutCtx.segs.forEach((seg, i) => {
        const s = cache.dom.segs[i];
        if (!s) return;
        if (s.sub) invalidateParagraphs(s.sub, changed, stale);
        if (seg.items && seg.items.some(it => changed.has(it.index))) {
            s.hc = null;
            if (s.painted) s.dirty = true;
        }
    });
}

export function refreshSlots(el) {
    const data = blockData.get(el);
    if (!data || !data.cache.dom) return;
    const changed = applySlots(data.fontInfo, data.doc);
    if (!changed.size) return;
    // (a widget's drawn parts sit inside its wdisc: the whole and each split's two)
    const parts = n => n.type === 'wdisc'
        ? [...n.replace, ...n.options.flatMap(o => [...o.pre, ...o.post])]
        : n.run ? [...n.run.merged.values()] : [n];
    const stale = data.doc.slotParas.flatMap(sp => (sp.stale || []).flatMap(parts));
    data.doc.slotParas.forEach(sp => { sp.stale = null; });
    invalidateParagraphs(data.cache, changed, stale);
    const params = { ...data.params, align: data.lastAlign };
    layoutDocument(data.fontInfo, data.doc, data.lastWidth, params, data.cache);
    paintVisibleNow(data.fontInfo, data.cache);
}

export function scheduleSlots() {
    if (slotScheduled) return;
    slotScheduled = true;
    requestAnimationFrame(() => {
        slotScheduled = false;
        for (const el of slotBlocks) refreshSlots(el);
    });
}

// The page's side: give a slot a text (any value; it is shown as a string),
// or null/undefined to show the default again. Every \webtext of that name,
// in every block, follows. Updates within one frame are applied together.
api.setText = function (name, text) {
    if (text === null || text === undefined) slotValues.delete(String(name));
    else slotValues.set(String(name), String(text));
    scheduleSlots();
};
api.getText = name => slotValues.get(String(name));
