// SPDX-License-Identifier: AGPL-3.0-or-later

// ── imports (generated by the split tooling; edit freely once the split is done)
import { SP_TO_PX } from '../engine/core.js';
import { asideHandles, docData } from './asides.js';
import { scheduleSlots } from './slots.js';
import { colorFill } from '../runtime/colour.js';
import { api } from '../runtime/page.js';
// ── end of imports

// ── Widgets (\webwidget) ───────────────────────────────────────────────────
// A page draws HTML at a \webwidget with a widget it registers:
//
//   reflowtex.widgets['name'] (or a prefix: 'lean:*') = {
//     measure(ctx) → { width, height, depth,          // px, the whole widget
//                      splits: [{ first: {width, height, depth, overhang?},
//                                 second: {…}, penalty? }, …] },
//     (overhang: how far a piece reaches past the margin, px)
//     render(el, part, ctx),   // part: 'whole', or { split: i, piece: 'first' | 'second' }
//   };
//
// Or, to break across any number of lines: measure returns { segments:
// [{width, height, depth}], gaps: [{width, penalty}] between each two,
// ends: { left: {cap, cut, overhang?}, right: {…} } } and render is given
// { from, to, left: 'cap'|'cut', right: 'cap'|'cut' } (widgetSegmentNodes).
// A split is one way to break the widget between two lines, as a hyphen
// breaks a word: the first part ends a line, the second starts the next. The
// line breaker weighs every split, with its penalty (default 100, twice a
// hyphen's), against the rest of the paragraph, and the widget then draws
// the part the chosen layout puts on each line. ctx carries the name, the
// text's font size and colour, a per-name `state`, `measure(html)` – the
// width, height and depth of some HTML at that size and baseline – and
// `invalidate()`, which measures again and re-breaks the paragraph when the
// widget's content changes. Registering after the viewer has run: call
// reflowtex.refreshWidgets().
api.widgets = api.widgets || {};
export const widgetVersion = new Map();       // name → bumped by ctx.invalidate()
export const widgetState   = new Map();       // name → the widget's own state object
export const widgetMeasure = new Map();       // `${name}|${fontPx}|${version}` → measurement
export function widgetFor(name) {
    const w = api.widgets || {};
    if (w[name]) return w[name];
    let best = null;
    for (const k of Object.keys(w))
        if (k.endsWith('*') && name.startsWith(k.slice(0, -1)) && (!best || k.length > best.length)) best = k;
    return best ? w[best] : null;
}

// Size some HTML the way it sits in a line: its box against the baseline.
export function measureHTML(html, fontPx) {
    const probe = document.createElement('div');
    probe.style.cssText = `position:absolute;left:-10000px;top:0;visibility:hidden;white-space:nowrap;font-size:${fontPx}px;line-height:normal`;
    const mark = document.createElement('span');
    mark.style.cssText = 'display:inline-block;width:0;height:0;vertical-align:baseline';
    const body = document.createElement('span');
    body.style.cssText = 'display:inline-block;vertical-align:baseline';
    if (typeof html === 'string') body.innerHTML = html; else body.appendChild(html);
    probe.append(mark, body);
    document.body.appendChild(probe);
    // The widget's own boxes, not the wrapper's: the wrapper's line box is
    // as tall as a line of text at this size, which would count space above
    // the widget as its height and so draw it too high. (Text straight in
    // the HTML, with no element around it, falls back to the wrapper.)
    const base = mark.getBoundingClientRect().top;
    const rs = [...body.children].map(c => c.getBoundingClientRect());
    const r = rs.length ? { left: Math.min(...rs.map(x => x.left)), right: Math.max(...rs.map(x => x.right)),
                            top: Math.min(...rs.map(x => x.top)), bottom: Math.max(...rs.map(x => x.bottom)) }
                        : body.getBoundingClientRect();
    probe.remove();
    return { width: r.right - r.left, height: Math.max(0, base - r.top), depth: Math.max(0, r.bottom - base) };
}
api.refreshWidgets = () => scheduleSlots();

export function widgetNodes(fontInfo, slot, id, run, before, after, doc) {
    const widget = widgetFor(slot.name);
    if (!widget || typeof widget.measure !== 'function') return null;
    // The text's size and colour: the default's first glyph, else the nearest
    // glyph of the paragraph around it.
    const glyph = ns => { for (const n of ns) { if (n.type === 'glyph') return n; if (n.type === 'disc') { const g = glyph(n.replace || []); if (g) return g; } } return null; };
    const t = glyph(run) || glyph([...before].reverse()) || glyph(after);
    const fi = t && fontInfo[String(t.font)];
    const fontPx = fi ? fi.size_px : 20;
    const version = widgetVersion.get(slot.name) || 0;
    if (!widgetState.has(slot.name)) widgetState.set(slot.name, {});
    const ctx = {
        name: slot.name, fontSize: fontPx, color: t && t.color ? colorFill(t.color) : null,
        state: widgetState.get(slot.name),
        measure: html => measureHTML(html, fontPx),
        // The asides of this widget's block (\webaside) that match a query.
        asides: query => asideHandles(docData.get(doc), query),
        invalidate: () => { widgetVersion.set(slot.name, (widgetVersion.get(slot.name) || 0) + 1); scheduleSlots(); },
    };
    // Per block too: a widget may draw its block's own asides.
    const key = `${(docData.get(doc) || {}).seq}|${slot.name}|${fontPx}|${version}`;
    let m = widgetMeasure.get(key);
    if (!m) {
        try { m = widget.measure(ctx); } catch (e) { console.warn(`[latex-viewer] widget ${slot.name}:`, e); return null; }
        if (!m) return null;
        widgetMeasure.set(key, m);
    }
    const sp = v => Math.round((+v || 0) / SP_TO_PX);
    const part = (dims, which) => ({ type: 'widget', slot: id, part: which, widget, ctx, fontPx,
        color: t && t.color, width: sp(dims.width), height: sp(dims.height), depth: sp(dims.depth),
        version });
    if (m.segments && m.segments.length) return widgetSegmentNodes(m, slot, id, widget, ctx, fontPx, t, version, sp);
    const whole = part(m, 'whole');
    if (!m.splits || !m.splits.length) return [whole];
    // A piece may reach past the margin by its `overhang` (px), as hanging
    // punctuation does: a negative kern after the first piece, which ends a
    // line, and before the second, which starts one, so the text is set to
    // the margin and the piece extends beyond it (a cut-edge mark on it can
    // then sit exactly on the margin).
    const hang = o => o && +o.overhang ? [{ type: 'kern', subtype: 1, kern: -sp(o.overhang) }] : [];
    return [{ type: 'wdisc', slot: id, replace: [whole],
              options: m.splits.map((s, i) => ({
                  penalty: s.penalty ?? 100,
                  pre:  [part(s.first,  { split: i, piece: 'first'  }), ...hang(s.first)],
                  post: [...hang(s.second), part(s.second, { split: i, piece: 'second' })] })) }];
}

// The segments form: the widget's content as a row of segments, a break
// point between each two, and its ends measured closed ('cap') and cut
// ('cut'). It becomes what a hyphenated word is to TeX – boxes with a
// discretionary between each two, whose pre is the cut end of the line
// before, post the cut end of the line after, and replace the gap shown when
// unbroken – so it may break at any number of its points, one line after
// another. Each line's run of pieces is then drawn as one part
// (mergeWidgetRuns): { from, to, left: 'cap'|'cut', right: 'cap'|'cut' }.
export function widgetSegmentNodes(m, slot, id, widget, ctx, fontPx, t, version, sp) {
    const segs = m.segments, gaps = m.gaps || [];
    const H = Math.max(...segs.map(g => sp(g.height))), D = Math.max(...segs.map(g => sp(g.depth)));
    const run = { slot: id, widget, ctx, fontPx, color: t && t.color, version, merged: new Map(), height: H, depth: D };
    const piece = (role, w, seg) => ({ type: 'widget', run, role, seg, width: sp(w), height: H, depth: D });
    const ends = m.ends || {};
    const L = ends.left || {}, R = ends.right || {};
    const hang = e => e && +e.overhang ? [{ type: 'kern', subtype: 1, kern: -sp(e.overhang) }] : [];
    const out = [piece('capL', L.cap || 0, 0)];
    segs.forEach((g, i) => {
        out.push(piece('seg', g.width, i));
        if (i < segs.length - 1) {
            const gap = gaps[i] || {};
            out.push({ type: 'disc', penalty: gap.penalty ?? 100, slot: id,
                       replace: gap.width ? [piece('gap', gap.width, i)] : [],
                       pre:  [piece('cutR', R.cut || 0, i), ...hang(R)],
                       post: [...hang(L), piece('cutL', L.cut || 0, i + 1)] });
        }
    });
    out.push(piece('capR', R.cap || 0, segs.length - 1));
    return out;
}
// One line's consecutive pieces of a segments widget, as one part to draw.
// Kept per run and shape, so an unchanged part keeps its element across
// reflows.
export function mergeWidgetRuns(nodes) {
    if (!nodes.some(n => (n.type === 'widget' && n.run) || (n.type === 'disc' && n.slot))) return nodes;
    // A break point the line did not break at is its replacement (the gap):
    // unfold it, so the pieces either side join into one part.
    nodes = nodes.flatMap(n => n.type === 'disc' && n.slot ? n.replace : [n]);
    const out = [];
    for (let i = 0; i < nodes.length; i++) {
        const n = nodes[i];
        if (!(n.type === 'widget' && n.run)) { out.push(n); continue; }
        let j = i, w = 0;
        while (j < nodes.length && nodes[j].type === 'widget' && nodes[j].run === n.run) { w += nodes[j].width; j++; }
        const run = nodes.slice(i, j), segs = run.filter(x => x.role === 'seg').map(x => x.seg);
        const part = { from: segs.length ? Math.min(...segs) : run[0].seg, to: segs.length ? Math.max(...segs) : run[0].seg,
                       left: run[0].role === 'cutL' ? 'cut' : 'cap',
                       right: run[run.length - 1].role === 'cutR' ? 'cut' : 'cap' };
        const key = `${part.from}|${part.to}|${part.left}|${part.right}|${w}`;
        let merged = n.run.merged.get(key);
        if (!merged) {
            merged = { type: 'widget', slot: n.run.slot, part, widget: n.run.widget, ctx: n.run.ctx,
                       fontPx: n.run.fontPx, color: n.run.color, version: n.run.version,
                       width: w, height: n.run.height, depth: n.run.depth };
            n.run.merged.set(key, merged);
        }
        out.push(merged);
        i = j - 1;
    }
    return out;
}
