// SPDX-License-Identifier: AGPL-3.0-or-later

// ── imports (generated by the split tooling; edit freely once the split is done)
import { ZOOM } from '../engine/core.js';
import { layoutDocument } from '../engine/layout/document.js';
import { paintDocument } from '../engine/paint.js';
import { blockData } from '../runtime/blocks.js';
// ── end of imports

// ── Footnotes ────────────────────────────────────────────────────────────────
// Footnote bodies are ordinary ContentItem streams stored outside the document's
// main flow. Hover/focus previews them; click pins the popover for touch users and
// so links/citations inside the fully rendered LaTeX body remain interactive.
export let footnotePop = null;
export let footnoteBody = null;
export let footnoteArrow = null;
export let pinnedFootnote = null;   // { block, id, anchor } or null
export let hoverFootnote = null;

export function installFootnotes() {
    if (footnotePop) return;
    const style = document.createElement('style');
    style.textContent = `
      .latex-footnote-source { cursor: pointer; pointer-events: auto; }
      /* A frosted panel: the page's colour, mostly opaque, over a blur of
         what lies behind (a page may set --latex-popover-background). No
         arrow: the panel opens right by its mark. */
      #latex-footnote-pop { position: fixed; z-index: 2147483000; display: none;
        width: max-content; max-width: calc(100vw - 16px); max-height: calc(100vh - 16px);
        overflow: auto; box-sizing: border-box; padding: 1.05rem 1.25rem 1.15rem;
        border: .5px solid color-mix(in srgb, currentColor 16%, transparent); border-radius: 16px;
        background: var(--latex-popover-background,
          color-mix(in srgb, var(--latex-page-bg, Canvas) 84%, transparent));
        -webkit-backdrop-filter: saturate(180%) blur(20px); backdrop-filter: saturate(180%) blur(20px);
        color: inherit;
        box-shadow: 0 18px 50px rgb(0 0 0 / .18), 0 2px 6px rgb(0 0 0 / .08); }
      #latex-footnote-pop.latex-footnote-open { display: block;
        animation: latex-footnote-in .16s cubic-bezier(.2, .9, .25, 1.05); }
      @keyframes latex-footnote-in { from { opacity: 0; transform: translateY(-4px) scale(.98); } }
      @media (prefers-reduced-motion: reduce) { #latex-footnote-pop.latex-footnote-open { animation: none; } }
      #latex-footnote-pop .latex-footnote-arrow { display: none; }
      #latex-footnote-pop .latex-footnote-content { margin: 0; overflow: visible; }
      #latex-footnote-pop .latex-footnote-content svg { max-width: 100%; }
    `;
    document.head.appendChild(style);

    footnotePop = document.createElement('div');
    footnotePop.id = 'latex-footnote-pop';
    footnotePop.setAttribute('role', 'tooltip');
    footnoteArrow = document.createElement('div');
    footnoteArrow.className = 'latex-footnote-arrow';
    footnoteBody = document.createElement('div');
    footnoteBody.className = 'latex-block latex-footnote-content';
    footnotePop.append(footnoteArrow, footnoteBody);
    document.body.appendChild(footnotePop);

    const sourceAt = t => (t && t.closest) ? t.closest('[data-footnote]') : null;
    document.addEventListener('pointerover', e => {
        if (pinnedFootnote) return;
        const el = sourceAt(e.target);
        if (el) openFootnote(el, false);
    });
    document.addEventListener('pointerout', e => {
        if (pinnedFootnote) return;
        const from = sourceAt(e.target);
        if (!from) return;
        const to = sourceAt(e.relatedTarget);
        if (!to || to.dataset.footnote !== from.dataset.footnote) closeFootnote();
    });
    document.addEventListener('focusin', e => {
        if (!pinnedFootnote) {
            const el = sourceAt(e.target);
            if (el) openFootnote(el, false);
        }
    });
    document.addEventListener('focusout', e => {
        if (!pinnedFootnote && !footnotePop.contains(e.relatedTarget)) closeFootnote();
    });
    document.addEventListener('click', e => {
        const el = sourceAt(e.target);
        if (el) {
            e.preventDefault();
            const block = el.closest('[data-nodelist-b64]');
            const id = el.dataset.footnote;
            if (pinnedFootnote && pinnedFootnote.block === block && pinnedFootnote.id === id) {
                closeFootnote();
            } else {
                openFootnote(el, true);
            }
        } else if (pinnedFootnote && !footnotePop.contains(e.target)) {
            closeFootnote();
        }
    });
    document.addEventListener('keydown', e => {
        const el = sourceAt(e.target);
        if (el && (e.key === 'Enter' || e.key === ' ')) {
            e.preventDefault();
            openFootnote(el, true);
        } else if (e.key === 'Escape' && (pinnedFootnote || hoverFootnote)) {
            closeFootnote();
        }
    });
    const reposition = () => {
        const active = pinnedFootnote || hoverFootnote;
        if (active) positionFootnote(active.anchor);
    };
    const reflow = () => {
        const active = pinnedFootnote || hoverFootnote;
        if (active) {
            renderFootnote(active.block, active.id);
            positionFootnote(active.anchor);
        }
    };
    window.addEventListener('scroll', reposition, { passive: true });
    window.addEventListener('resize', reflow);
}

export function footnoteGroupRect(el) {
    const id = el.dataset.footnote;
    const same = e => e && e.dataset && e.dataset.footnote === id;
    const kin = [el];
    for (let p = el.previousElementSibling; same(p); p = p.previousElementSibling) kin.push(p);
    for (let n = el.nextElementSibling; same(n); n = n.nextElementSibling) kin.push(n);
    let L = Infinity, T = Infinity, R = -Infinity, B = -Infinity;
    for (const k of kin) {
        const b = glyphScreenRect(k);
        L = Math.min(L, b.left); T = Math.min(T, b.top);
        R = Math.max(R, b.right); B = Math.max(B, b.bottom);
    }
    return isFinite(L) ? { left:L, top:T, right:R, bottom:B, width:R-L, height:B-T }
                       : el.getBoundingClientRect();
}

export function renderFootnote(block, id) {
    const data = blockData.get(block);
    if (!data) return false;
    const note = (data.doc.streams || [])[Number(id) - 1];
    // A footnote, or an aside opened from its mark (placeMarginNotes).
    if (!note || (note.kind !== 'footnote' && !(note.attrs || []).some(a => a.key === 'aside'))) return false;
    data.footnoteCaches = data.footnoteCaches || new Map();
    let fc = data.footnoteCaches.get(String(id));
    if (!fc) {
        fc = { bcs:null, dom:null, layout:null, stats:null };
        data.footnoteCaches.set(String(id), fc);
    }
    const widthPx = Math.min(420, Math.max(220, document.documentElement.clientWidth - 32));
    // The body is the stream's own content over the block's shared tables
    // (paragraphs, fonts, pictures, streams – and source_width: a footnote's
    // displays are modelled per scaled point of the measure they were compiled
    // at, so the popover must carry that measure across too).
    const noteDoc = { ...data.doc, content: note.content };
    footnoteBody.style.width = widthPx + 'px';
    footnoteBody.replaceChildren(layoutDocument(
        data.fontInfo, noteDoc, widthPx / ZOOM, data.params, fc));
    paintDocument(data.fontInfo, fc);
    return true;
}

export function positionFootnote(anchor) {
    const r = footnoteGroupRect(anchor);
    const gap = 9, vw = document.documentElement.clientWidth, vh = window.innerHeight;
    const pw = footnotePop.offsetWidth, ph = footnotePop.offsetHeight;
    const cx = r.left + r.width / 2;
    const left = Math.max(8, Math.min(cx - pw / 2, vw - pw - 8));
    const above = (r.bottom + gap + ph > vh) && (r.top - gap - ph > 0);
    const rawTop = above ? r.top - ph - gap : r.bottom + gap;
    const top = Math.max(8, Math.min(rawTop, vh - ph - 8));
    footnotePop.classList.toggle('latex-footnote-above', above);
    footnotePop.style.left = left + 'px';
    footnotePop.style.top = top + 'px';
    const box = footnotePop.getBoundingClientRect();
    footnoteArrow.style.left = Math.max(12, Math.min(box.width - 12, cx - box.left)) + 'px';
}

export function openFootnote(anchor, pin) {
    const block = anchor.closest('[data-nodelist-b64]');
    const id = anchor.dataset.footnote;
    if (!block || !renderFootnote(block, id)) return;
    footnotePop.classList.add('latex-footnote-open');
    footnotePop.classList.toggle('latex-footnote-pinned', pin);
    positionFootnote(anchor);
    const active = { block, id, anchor };
    if (pin) { pinnedFootnote = active; hoverFootnote = null; }
    else hoverFootnote = active;
}

export function closeFootnote() {
    pinnedFootnote = null; hoverFootnote = null;
    if (footnotePop) footnotePop.classList.remove(
        'latex-footnote-open', 'latex-footnote-pinned', 'latex-footnote-above');
}

export function registerFootnoteSource(el, id) {
    el.classList.add('latex-footnote-source');
    el.dataset.footnote = id;
    el.setAttribute('role', 'button');
    el.setAttribute('tabindex', '0');
    el.setAttribute('aria-describedby', 'latex-footnote-pop');
}

// A glyph that refers to a stream (Node.stream, a 1-based index into
// Document.streams). What that means depends on the stream's kind: a footnote
// marker opens its body in the popover above. Other kinds referenced from a
// glyph are reserved for later (a term's definition on hover, say) and get no
// behaviour yet – the glyph renders as plain text.
export function registerStreamSource(el, idx, cache) {
    const stream = (cache.streams || [])[idx - 1];
    if (!stream) return;
    if (stream.kind === 'footnote') registerFootnoteSource(el, idx);
}

// The on-screen box of a single glyph <tspan>. Neither getBoundingClientRect()
// nor getBBox() works: for an SVG <tspan> both return the box of the whole
// enclosing <text> run, which would anchor every citation to the centre of its
// line. But each glyph carries its own baseline position as x/y attributes, so
// build the box from those (width ~half an em, height from the font size – rough
// is fine, it only anchors a popover) and map it through getScreenCTM(), which
// folds in every ancestor transform and the SVG's own screen position.
export function glyphScreenRect(el) {
    const svg = el.ownerSVGElement;
    const ctm = el.getScreenCTM && el.getScreenCTM();
    const x = parseFloat(el.getAttribute('x'));
    const y = parseFloat(el.getAttribute('y'));
    const fs = parseFloat(el.getAttribute('font-size'));
    if (!svg || !ctm || !svg.createSVGPoint || !isFinite(x) || !isFinite(y) || !isFinite(fs)) {
        return el.getBoundingClientRect();
    }
    // Glyph box in user units: from the baseline up by ~cap height and a hair
    // below it, half an em wide (numerals).
    const x0 = x, x1 = x + fs * 0.5, y0 = y - fs * 0.72, y1 = y + fs * 0.10;
    const pt = svg.createSVGPoint();
    let L = Infinity, T = Infinity, R = -Infinity, B = -Infinity;
    for (const [px, py] of [[x0, y0], [x1, y0], [x0, y1], [x1, y1]]) {
        pt.x = px; pt.y = py;
        const p = pt.matrixTransform(ctm);
        L = Math.min(L, p.x); R = Math.max(R, p.x); T = Math.min(T, p.y); B = Math.max(B, p.y);
    }
    return { left: L, top: T, right: R, bottom: B, width: R - L, height: B - T };
}
