// SPDX-License-Identifier: AGPL-3.0-or-later

// ── imports (generated by the split tooling; edit freely once the split is done)
import { registerFootnoteSource } from './footnotes.js';
import { allData, asideHandles } from '../host/asides.js';
import { api } from '../runtime/page.js';
// ── end of imports

// ── Margin notes ────────────────────────────────────────────────────────────
// Asides with place=margin (\marginpar; \webaside[place=margin]) go in the
// right margin, each with its first baseline on the baseline of the line its
// mark is on, in a layer inside the block, so they move with it; one close
// below another is pushed down. Where the window leaves less than
// MARGIN.min beside the block, the note is hidden and its mark becomes a
// small button (.latex-margin-mark) opening it in the footnote popover.
// A page styles notes by .latex-margin-note[data-kind=…], or draws a kind
// itself: reflowtex.marginNotes[kind] = (el, aside, widthPx) => …, filling el
// (with aside.render(…) somewhere in it, whose baseline is then the one set
// on the line). A page may set the margin itself, on the block, in px:
// --latex-margin-width (the notes' width, taken as given – 0 for marks
// only) and --latex-margin-gap (from the text); else the margin is what the
// window leaves beside the block, up to MARGIN.max. Placed again after every
// layout, drawing and resize.
export const MARGIN = { gap: 28, min: 150, max: 260 };   // px, by default
api.marginNotes = api.marginNotes || {};
export function placeMarginNotes(data) {
    const el = data && data.el;
    if (!el || !el.isConnected) return;
    const notes = asideHandles(data, { place: 'margin' });
    if (!notes.length) return;
    const M = data.margin = data.margin || { layer: document.createElement('div'), items: new Map() };
    M.layer.className = 'latex-margin';
    if (M.layer.parentNode !== el) el.appendChild(M.layer);
    if (getComputedStyle(el).position === 'static') el.style.position = 'relative';
    const br = el.getBoundingClientRect(), k = br.width / el.offsetWidth || 1;   // CSS zoom above
    const cs = getComputedStyle(el), px = (v, d) => { const n = parseFloat(v); return isFinite(n) ? n : d; };
    const gap = px(cs.getPropertyValue('--latex-margin-gap'), MARGIN.gap);
    const set = px(cs.getPropertyValue('--latex-margin-width'), null);
    const room = set !== null ? set : (document.documentElement.clientWidth - br.right) / k - gap;
    const width = Math.floor(Math.min(set !== null ? set : MARGIN.max, room));
    const wide = set !== null ? width > 0 : room >= MARGIN.min;
    const placed = [];
    for (const a of notes) {
        let it = M.items.get(a.index);
        if (!it) {
            const note = document.createElement('div');
            note.className = 'latex-margin-note';
            note.dataset.kind = a.kind;
            const mark = document.createElement('button');
            mark.type = 'button';
            mark.className = 'latex-margin-mark';
            mark.textContent = '*';
            mark.setAttribute('aria-label', 'Note');
            registerFootnoteSource(mark, a.index);
            it = { note, mark, width: 0 };
            M.items.set(a.index, it);
            M.layer.append(note, mark);
        }
        const at = a.anchor();
        it.note.hidden = !(wide && at);
        it.mark.hidden = !(!wide && at);
        if (!at) continue;
        const x = (at.left - br.left) / k, y = (at.top - br.top) / k;
        if (!wide) { it.mark.style.left = x + 'px'; it.mark.style.top = y + 'px'; continue; }
        if (it.width !== width) {
            const draw = api.marginNotes[a.kind];
            if (draw) draw(it.note, a, width); else a.render(it.note, width);
            it.width = width;
        }
        it.note.style.left = el.offsetWidth + gap + 'px';
        it.note.style.width = width + 'px';
        const box = it.note.querySelector('.latex-aside');
        const baseline = box ? (box.getBoundingClientRect().top - it.note.getBoundingClientRect().top) / k
                               + parseFloat(box.dataset.baseline || 0) : 0;
        placed.push({ note: it.note, top: y - baseline });
    }
    placed.sort((p, q) => p.top - q.top);
    let bottom = -Infinity, reach = 0;
    for (const p of placed) {
        const top = Math.max(p.top, bottom);
        p.note.style.top = top + 'px';
        bottom = top + p.note.offsetHeight + 8;
        reach = Math.max(reach, top + p.note.offsetHeight);
    }
    // Notes reaching below the block's text: room for them under it.
    el.style.paddingBottom = '';
    const over = reach - el.offsetHeight;
    el.style.paddingBottom = over > 0 ? Math.ceil(over) + 'px' : '';
}
window.addEventListener('resize', () => { for (const d of allData) if (d.margin) placeMarginNotes(d); });
